### ISSUE TITLE
Convert dgxie config-map to inline config

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#10]
Use Helm config to supply extra dnsmasq via inline config map vs separate file

i.e.

```sh
dnsmasq: |-
dhcp-host=00:01:02:03:04:05,login01,192.168.1.10
dhcp-host=01:02:03:04:05:06,dgx01,192.168.1.20
cname=registry,mgmt01
cname=registry.local,mgmt01.local
```

**Comment by supertetelman** [comment]
We're moving towards MAAS and won't be addressing this improvement as it is currently working.
