### ISSUE TITLE
Question about DeepOps Requirement

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/deepops#1018]
DeepOps Kubernetes  requires at least 1 management server and 1 worker. i.e. it does not share management server and worker? 

Reference
https://github.com/NVIDIA/deepops/blob/21.06/docs/deepops/dgx-pod.md#hardware-requirements

**Comment by mkunin-nvidia** [comment]
In general, it is possible to run everything on the same server (DGX node). However, it is better to follow those requirements. The outcome of the all-in-one installation might be unexpected, and I wouldn't suggest this for any reasonable use case.  

Management hosts are possible to run as virtual machines when other options are not available. However, once again, I wouldn't suggest this for a multi-user environment, if all the virtual machines run on the same DGX/worker node.

During the installation, the slurm-nodes are rebooted, so it is better to run ansible playbooks from a host that is not part of the slurm-cluster.
