### ISSUE TITLE
NFS over RDMA

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#1053]
Is there an option to Configure NFS over RDMA (RoCE) if you have everything running over fiber with the mellanox adapters? Or is the only way to disable default client and server NFS and configure it yourself for every node?

**Comment by ajdecon** [comment]
We don't currently have an NFS over RDMA configuration in DeepOps. We'd definitely welcome a contribution which included this 😄 but today, you'll have to configure this outside of DeepOs.
