### ISSUE TITLE
Automate the GPU Operator installation NVIDIA AI Enterprise special cases

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#1055]
NVIDIA AI Enterprise relies on special NVIDIA drivers that enable GPUs in a virtualized environment (vGPU). This is part of the product offerings that are delivered through NGC.

In order for NVIDIA AI Enterprise to function properly with the GPU Operator, there are a few special steps required. This includes using special helm packages for the operator, providing NGC keys to access private container resources, and using special configuration variables.

I propose we do the following:

- [ ] Break the current GPU Operator install path into a standard install and NVIDIA AI Enterprise install path
- [ ] Implement the NVIDIA AI Enterprise role tasks
- [ ] Introduce several new variables to support installing the NVIDIA AI Enterprise path and optionally, support the new NVIDIA License Server used in AI Enterprise (NLS)
- [ ] Document the new variables, install path, etc.

**Comment by ajdecon** [comment]
This should be addressed by #1059

**Comment by supertetelman** [comment]
We should tested this end-to-end today in master and it looks good!
