### ISSUE TITLE
Other recommended distributed storage other than the deprecated Ceph?

### ISSUE THREAD

**Issue by ghilman27** [NVIDIA/deepops#1060]
Hi,

I looked up and found that Ceph is deprecated (no support and no longer guaranteed to work) in this commit https://github.com/NVIDIA/deepops/pull/846/commits/677ca19a505c056b093fd44cf38816ba44360e19

Currently, I'm looking for a certain storage solution that could replicate data across worker nodes (like Longhorn and Ceph). Do you have any recommendations that could work with deepops, and how to integrate that to deepops?

**Comment by ajdecon** [comment]
Based on our experience with production deployments of DeepOps-type clusters, we find that running storage external to the cluster seems to work best and present fewer challenges than running storage within the cluster. This is why we currently recommend using the [NFS Client Provisioner](https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#nfs-client-provisioner), or working with a storage vendor on their preferred solution. Several storage vendors have published [reference architectures](https://www.nvidia.com/en-us/data-center/dgx-pod/) for integrating their storage with NVIDIA DGX clusters, which may provide a good idea of what such an architecture would look like.

We don't currently have a recommendation for a distributed storage system running within the cluster, and don't have any plans to integrate a new storage system in DeepOps.

If you're still interested in trying Ceph, it's worth noting that DeepOps made use of the upstream [Rook](https://rook.io/) project for setting up Ceph within the cluster. It might be worth consulting the Rook documentation for guidance on setting this up on your cluster, outside the DeepOps workflow.
