### ISSUE TITLE
Different types of graphic cards supported?

### ISSUE THREAD

**Issue by DevZiegler** [NVIDIA/deepops#1064]
Hi, are different graphics cards supported on one node with one mainboard in the Deepops system? For example, two RTX 3090 Turbo and two RTX A6000. And if yes, can I then choose between the graphics cards at startup of a pod, so pod one gets both 3090 and pot two and three each an A6000.
Thx

**Comment by ajdecon** [comment]
We don't generally recommend mixing different GPU types on the same server. Neither the NVIDIA driver or DeepOps will block this, but most server OEMs only [test and qualify](https://www.nvidia.com/en-us/data-center/data-center-gpus/qualified-system-catalog/) a single GPU type at a time, and don't do any testing of mixed configurations. Mixed configurations may therefore run into unforeseen issues, depending on the server model.

Kubernetes also doesn't support targeting a specific GPU type at pod startup, and only exposes each GPU as a generic `nvidia.com/gpu` resource. The Kubernetes documentation recommends [putting different types of GPUs in different nodes, and using node labels to distinguish the node types](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#clusters-containing-different-types-of-gpus).

With current versions of the [GPU feature discovery plugin](https://github.com/NVIDIA/gpu-feature-discovery), these node-level labels will be applied automatically (e.g., `nvidia.com/gpu.product=Tesla-P100-SXM2-16GB`), but individual pods can still only request a number of GPU resources (e.g., `nvidia.com/gpu=2`).

**Comment by DevZiegler** [comment]
Thanks for the quick help.
btw: I find the support here really great 👍
