### ISSUE TITLE
Update DeepOps to support GPU Operator 1.9

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#1069]
New GPU Operator version adds DGX OS support to GPU Operator: https://developer.nvidia.com/blog/gpu-operator-1-9-adds-support-for-dgx-a100-with-dgx-os/

It also adds some functionality which will allow us to simplify install/configuration:
* Automatically detect/disable Nouveau (something we are doing as a pre-step and can remove)
* Automatically detect container runtime (currently we are configuring it as a ansible variable)
* Supports DGX OS (but requires the flags mentioned here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-pre-installed-drivers-and-nvidia-container-toolkit)
* Support for MIG-manager on DGX: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-operator-mig.html#mig-with-preinstalled-drivers (with this, we should consider introducing a ansible variable to define MIG configs in K8s)

**Comment by supertetelman** [comment]
https://github.com/NVIDIA/deepops/pull/1074

**Comment by supertetelman** [comment]
Bad bot.

**Comment by ajdecon** [comment]
Addressed by #1074
