### ISSUE TITLE
 During the deepops installation `ensure docker packages are installed` task fails.

### ISSUE THREAD

**Issue by mkunin-nvidia** [NVIDIA/deepops#1076]
It is DGX OS 5.1.0 related issue. DGX OS 5.1.0 has 20.10.7 docker version.

During the deepops installation `ensure docker packages are installed` task fails. Even if `docker_version: "20.10"` is configured. Putting `"20.10.7"` doesn't work. 
![image](https://user-images.githubusercontent.com/86852992/145771723-936a1544-aa2a-4ff5-9561-55abe8a5cba7.png)

Workaround: downgrade manually the docker to 20.10.5 and then re-run the playbooks again.

**Comment by nomadicpeople** [comment]
additionall need to install containerd.io.

**Comment by ajdecon** [comment]
Closing in fabor of #1110 which documents a work-around until we have a fix in (upgrading Kubespray).
