### ISSUE TITLE
How to change kubespray group_vars

### ISSUE THREAD

**Issue by ghilman27** [NVIDIA/deepops#1082]
We can configure setting in kubespray using their `group_vars`. Like this one [`k8s-cluster.yaml`](https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml).

How can we set it in deepops config? For example, how can I set [`auto_renew_certificates`](https://github.com/kubernetes-sigs/kubespray/blob/ed3932b7d52f5de892a66010cb342c9c754e3655/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml#L322) to `true`?

**Comment by ajdecon** [comment]
@ghilman27 : You should be able to set any Kubespray variables in the DeepOps config under [`group_vars/k8s-cluster.yml`](https://github.com/NVIDIA/deepops/blob/master/config.example/group_vars/k8s-cluster.yml).

These variables should all be passed through to Kubespray when DeepOps executes the Kubespray `cluster.yml`.
