### ISSUE TITLE
Setup.sh showed ERROR Unexpected Exception

### ISSUE THREAD

**Issue by agungfazrulhaq** [NVIDIA/deepops#1091]
Hi,
I met the following error while run the setup.sh :
`Updating Ansible Galaxy roles...
[WARNING]: - dependency gantsign.golang (2.0.4) (2.0.4) from role lecorguille.singularity differs from already installed version (2.4.0), skipping
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable`
Here is the environment detail : 
OS : Ubuntu 20.04
deepops : tag/21.09
ansible: 2.9.21

Regards,
Agung

**Comment by agungfazrulhaq** [comment]
it didn't cause the setup.sh to fail, it proceed the installation. We are not sure if it's installed correctly and we wanted to know if it going to affect any configuration in the future.

**Comment by supertetelman** [comment]
If it proceeded you should be fine. This is an intermittent error that shows up sometimes when downloading Ansible packages.

Depending on the installation path you take, this may not be an issue. I would run the setup.sh again then proceed with the install.  Are you installing K8s or Slurm or something else?
