### ISSUE TITLE
Document and/or probe the networking ports required for deepops connectivity

### ISSUE THREAD

**Issue by jasonguy** [NVIDIA/deepops#1092]
In cases where users have automated deployment of hosts, where the default security settings are restrictive, it would help to document the TCP/UDP ports that need to be open between nodes. For example, in a k8s deployment, we found we had to - permit port 6443 into the data center, for the connectivity test from the admin node -> kube master.

Obviously, with security it really depends on the topology, but perhaps a section in the docs indicating the network connections that will be tested by the playbook. The kubectl test happens fairly deep in the playbook, so re-running takes a while to test. An enhancement would be to poke the required ports at the beginning of the playbooks. This would be a more deterministic way to quickly test the connectivity based on the users configuration, and ensure the external network will support the deployment.

**Comment by ajdecon** [comment]
I don't think we can necessarily do this directly in the DeepOps documentation, given that we frequently update our dependencies and the docs could get stale quickly.

However, I think we can probably add links from our documentation, to the firewall documentation for our major components.

For example: I don't think it's reasonable to list all the necessary Kubernetes ports directly in the DeepOps documentation, and keep that up to date. But we can certainly link to the Kubernetes [ports and protocols](https://kubernetes.io/docs/reference/ports-and-protocols/) page.

I'll look at adding a docs page along these lines.

**Comment by ajdecon** [comment]
Addressed by #1126
