### ISSUE TITLE
deepops on disconnected network

### ISSUE THREAD

**Issue by narincohen** [NVIDIA/deepops#1108]
Hi,
I would like to use deepops to install slurm on a disconnected network. I wonder if there is documenting procedure that can help with this process. Maybe a list of all the dependencies that need to be moves to the disconnected network, or some other action that need to be taken before the intallation.

Thanks in advance
Narin Cohen

**Comment by ajdecon** [comment]
In general, all the external URLs used by DeepOps are managed using variables, so you can mirror the artifacts in question and override the URL for DeepOps to use. For example, you can set:

```
slurm_src_url: "https://my.internal.site/slurm.tgz
```

And DeepOps will perform the download from your preferred server.

Unfortunately, we don't currently have any docs specifically for building a Slurm cluster in a disconnected network. We do have some [documentation on dealing with offline deployments in general](https://github.com/NVIDIA/deepops/tree/master/docs/airgap), but haven't cataloged the specific list of dependencies and changes for Slurm.

You should be able to identify most of the variable names of interest by running:

```
grep http roles/*
```

Hope this helps!
