### ISSUE TITLE
Docker install task fails on DGX OS 5.1.x

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#1110]
This is actually a dupe of #1076, but opening a separate issue for easier visibility of the issue and the work-around.

DGX OS 5.1.x currently installs Docker by default at version `20.10.11~3-0~ubuntu-focal`. However, the pinned version of Docker branch `20.10` in Kubespray v2.17.1 is `20.10.8~3-0~ubuntu-focal`. This leads to our Docker install tasks failing, as it would result in a downgrade.

Kubespray v2.18.0 pins to the new version of Docker, which should resolve this issue. We'll look at bumping the version number in the next DeepOps release.

In the mean time, it should be possible to work-around this issue by setting the following in the DeepOps config:

```
docker_version: "latest"
containerd_version: "latest"
```

**Comment by jungyh0218** [comment]
I manually installed docker to my gpu server with the following command.
` sudo apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'containerd.io=1.4.9-1' 'docker-ce-cli=5:20.10.8~3-0~ubuntu-focal' 'docker-ce=5:20.10.8~3-0~ubuntu-focal' --allow-downgrades`
Then it works fine, but I think this can only be a temporary work-around.

**Comment by ajdecon** [comment]
This should be resolved by #1043 , which both upgrades Kubespray to a version which uses more recent versions, and defaults us to using `containerd`-only as the container runtime.

Closing issue.
