### ISSUE TITLE
notebook password

### ISSUE THREAD

**Issue by neda777** [NVIDIA/deepops#1119]
How can I set a password for the notebook servers which I created using kubeflow?

**Comment by supertetelman** [comment]
I do not believe this is a feature built into the Kubeflow version currently supported by DeepOps.

I believe in the newer version this can be accomplished by configuring environment-specific Notebook launchers, but I do not believe this can be done per-user.

In the current version you can accomplish this by baking it into your container images via the Jupyter startup command. But I do not know that there is any way to change the password at startup time or set it per-user within Kubeflow.
