### ISSUE TITLE
deploy_kubeflow.sh -x, Dex error

### ISSUE THREAD

**Issue by tyan001** [NVIDIA/deepops#1122]
Hello, I am having issues in my kubeflow deployment on Ubuntu 20.04. I am using the deploy_kubeflow.sh -x command. 
I install Kubernetes as shown in the k8s Deployment guide, and deploy ingress using the NodePort config.

After installation and receiving the link to the Kubeflow dashboard, I waited to let it finish setting up, after trying regularly the link just stays blank. I ran the kubctl get pods -n kubeflow and all pods seems to be fine.

![kubeflow_pods](https://user-images.githubusercontent.com/29807150/156056143-3cc69ea0-6a59-4a04-9a38-c1c4a9233bbb.png)

Upon further inspection I found two problems through the k8s dashboard. 
One is the pod authservice-0 in the istio-system namespace In which at the end I get this error: "Warning  Unhealthy  48s (x362 over 60m)  kubelet Readiness probe failed: HTTP probe failed with statuscode: 503"

The other is the dex pod that resides in the auth namespace which I get this error: Back-off restarting failed container

I try changing the dex image and it didn't change. I am not sure what else to share so please advise me what other information you want.

I have also used this command. 
kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80 and it still showed a blank page.

Thanks

**Comment by supertetelman** [comment]
We have a PR currently in the works to address some of the current deployment issues and upgrade to Kubeflow version 1.4.
