### ISSUE TITLE
Nvidia driver 450

### ISSUE THREAD

**Issue by jzumaya** [NVIDIA/deepops#1123]
Hello
I have a problem with the nvidia-driver. Delete all nvidia packages for the script to install and it didn't work. 
Run apt autoremove
apt clean and nothing
Can you help me?
Server Lambda labs
 NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4 
 
 Error
 TASK [nvidia.nvidia_driver : install driver packages] ***************************************************************************************************************************************
task path: /home/user/instalacionDeepOps/deepops/roles/galaxy/nvidia.nvidia_driver/tasks/install-ubuntu.yml:7
Using module file /opt/deepops/env/lib/python3.8/site-packages/ansible/modules/packaging/os/apt.py
Pipelining is enabled.
<172.16.31.140> ESTABLISH SSH CONNECTION FOR USER: user
<172.16.31.140> SSH: EXEC sshpass -d10 ssh -vvv -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'User="user"' -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' 172.16.31.140 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=idtnpezqtvkosmghqaeurygosvmmedqy] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-idtnpezqtvkosmghqaeurygosvmmedqy ; http_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' HTTP_PROXY='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' https_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' HTTPS_PROXY='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' no_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' NO_PROXY='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<172.16.31.140> (1, b'\n{"msg": "\'/usr/bin/apt-get -y -o \\"Dpkg::Options::=--force-confdef\\" -o \\"Dpkg::Options::=--force-confold\\"      install \'nvidia-headless-450-server\' \'nvidia-utils-450-server\'\' failed: E: Unable to correct problems, you have held broken packages.\\n", "stdout": "Reading package lists...\\nBuilding dependency tree...\\nReading state information...\\nSome packages could not be installed. This may mean that you have\\nrequested an impossible situation or if you are using the unstable\\ndistribution that some required packages have not yet been created\\nor been moved out of Incoming.\\nThe following information may help to resolve the situation:\\n\\nThe following packages have unmet dependencies:\\n nvidia-headless-450-server : Depends: nvidia-headless-no-dkms-450-server (= 450.51.06-0lambda0~20.04.2) but it is not going to be installed\\n                              Depends: nvidia-dkms-450-server (= 450.51.06-0lambda0~20.04.2)\\n nvidia-utils-450-server : Depends: libnvidia-compute-450-server but it is not going to be installed\\n", "stderr": "E: Unable to correct problems, you have held broken packages.\\n", "rc": 100, "cache_updated": false, "cache_update_time": 1645740464, "failed": true, "invocation": {"module_args": {"state": "present", "autoremove": false, "purge": false, "name": ["nvidia-headless-450-server", "nvidia-utils-450-server"], "package": ["nvidia-headless-450-server", "nvidia-utils-450-server"], "cache_valid_time": 0, "force": false, "dpkg_options": "force-confdef,force-confold", "autoclean": false, "only_upgrade": false, "force_apt_get": false, "allow_unauthenticated": false, "update_cache": null, "deb": null, "default_release": null, "install_recommends": null, "upgrade": null, "policy_rc_d": null}}}\n', b'OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 172.16.31.140 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 86723\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<172.16.31.140> Failed to connect to the host via ssh: OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 172.16.31.140 is address
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 86723
debug3: mux_client_request_session: session request sent
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
failed: [lambdagdl01] (item=['nvidia-headless-450-server', 'nvidia-utils-450-server']) => changed=false
  ansible_loop_var: item
  cache_update_time: 1645740464
  cache_updated: false
  invocation:
    module_args:
      allow_unauthenticated: false
      autoclean: false
      autoremove: false
      cache_valid_time: 0
      deb: null
      default_release: null
      dpkg_options: force-confdef,force-confold
      force: false
      force_apt_get: false
      install_recommends: null
      name:
      - nvidia-headless-450-server
      - nvidia-utils-450-server
      only_upgrade: false
      package:
      - nvidia-headless-450-server
      - nvidia-utils-450-server
      policy_rc_d: null
      purge: false
      state: present
      update_cache: null
      upgrade: null
  item:
  - nvidia-headless-450-server
  - nvidia-utils-450-server
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'nvidia-headless-450-server' 'nvidia-utils-450-server'' failed: E: Unable to correct problems, you have held broken packages.
  rc: 100
  stderr: |-
    E: Unable to correct problems, you have held broken packages.
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     nvidia-headless-450-server : Depends: nvidia-headless-no-dkms-450-server (= 450.51.06-0lambda0~20.04.2) but it is not going to be installed
                                  Depends: nvidia-dkms-450-server (= 450.51.06-0lambda0~20.04.2)
     nvidia-utils-450-server : Depends: libnvidia-compute-450-server but it is not going to be installed
  stdout_lines: <omitted>

**Comment by ajdecon** [comment]
What exactly are you trying to achieve?

Based on this:

> NVIDIA-SMI 470.103.01 Driver Version: 470.103.01 CUDA Version: 11.4

It looks like you already have an NVIDIA driver installed. If that's the case, and if you don't want to change the NVIDIA driver version, you can probably skip the task for installing the driver when running DeepOps.

**Comment by ajdecon** [comment]
Closing due to lack of reply; if you're still seeing this issue, please feel free to reopen and we can continue to debug.
