### ISSUE TITLE
Deep Learning Examples automation isn't compatible with containerd-based Kubernetes

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#1144]
The [Deep Learning Examples automation](https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/deep-learning-examples.md) relies on access to the host Docker daemon in order to build images on demand.

Unfortunately, with the move to using `containerd` by default, there is no Docker daemon on the host! And so therefore the deployment process doesn't work. 😢 

We should determine if we can re-work the automation to use a different container build method. Or if not, at least document that the Docker-based deployment mechanism is needed for this use case.

**Comment by ajdecon** [comment]
cc @tuttlebr

**Comment by supertetelman** [comment]
Would simply installing docker/nvidia-docker on all nodes and not using in in K8s resolve this issue? I know we had an internal thread going around whether or not this would be a good deployment mechanism with containerd for debugging/image building or just bloat.

**Comment by ajdecon** [comment]
Fixed by #1145
