### ISSUE TITLE
Upgrade to Kubeflow v1.6 when it is available, until then Kubeflow is unsupported.

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#1147]
We recently updated to Kubernetes v1.22.

We are currently on Kubeflow v1.4. Kubeflow v1.4 and v1.5 only support up to v1.21 of Kubernetes.

Kubeflow v1.6 should be coming out in a few weeks and is due to support v1.22. We need to upgrade when available. Until then the latest DeepOps K8s cannot support Kubeflow deployments.

Kubeflow issue tracking some of this: https://github.com/kubeflow/kubeflow/issues/6353

**Comment by hexonxonx4** [comment]
any idea when kubeflow will show on the radar again?

**Comment by supertetelman** [comment]
Merging the PR through now.
