### ISSUE TITLE
Clarify the gpu_operator configuration flags and HOW to set them for different scenarios

### ISSUE THREAD

**Issue by jasonguy** [NVIDIA/deepops#1174]
The comments and documentation around the gpu_operator flags is not clear. Reading the documentation for gpu_operator indicates it is an alternative to natively-installed GPU drivers. However that is not very clear for users to understand when to set the flags false.

Looking at the code:
- The **deepops_gpu_operator_enabled** flag only applies to Docker runtime, since the first task in k8s-cluster.yml sets it true if the container runtime is not docker.
- The **gpu_operator_preinstalled_nvidia_software** flag appears to primarily disable the install of the gpu_operator driver-container, and only installing the tooling container. 

Perhaps explaining scenarios when the flags would be set true or false?

**Comment by supertetelman** [comment]
Yes, I agree that we could fix some the documentation here or how the vars are structured. Would this make more sense for a config flag?

```
deepops_gpu_operator:
    enabled: true # Use GPU Operator path, set to false to just use device plugin
    install_nvidia_software: false # Skip driver container and install local drivers, set to false to leverage driver containers in GPU Operator
```

**Comment by supertetelman** [comment]
Hopefully we will be addressing this issue in the next week or two. The latest release of the GPU Operator now is a bit more dynamic making some of these flags unncessary.
