### ISSUE TITLE
reboot after a nvidia-smi error

### ISSUE THREAD

**Issue by georgettica** [NVIDIA/deepops#1186]
while installing on a machine, I got an error stated in https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch

(the step it failed for me is lost forever now)
but I found a reboot did solve this issue.

hopefully I can create a PR to mitigate this for the next runner up

**Comment by ajdecon** [comment]
Closing because this isn't a DeepOps issue. That said, if you want to open a PR at some point and include logic to work around the driver issue with a reboot, I'd be happy to review it. 😄
