### ISSUE TITLE
NFS mount protocol error 

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#1189]
In the documentation it mentions that nfs mount supports all mount options that the system normally does. I am able to manually do an nfs rdma mount in the terminal but when I update the mount options in the group_vars/slurm-cluster.yml it fails with the error:
Error mounting /home: mount.nfs: Protocol error
failed: [gpu01] (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3,rsize=1048576,wsize=1048576,rdma,port=20049'}) => changed=false 
Here are my mount options:
options: async,vers=3,rsize=1048576,wsize=1048576,rdma,port=20049

**Comment by ajdecon** [comment]
Can you check that the option list looks correct when configured in `/etc/fstab`? Are you using an identical set of options when mounting manually in the terminal?

All that Ansible is really doing here is configuring the `fstab` and using standard Linux tooling to issue the mount command. So if a mount works manually, and all the options are identical, it should also work via Ansible.

Unfortunately I don't have an RDMA-enabled setup handy to test this on right now.

**Comment by arnoldas500** [comment]
Identical set of options when mounting manually in the terminal. It also works fine if I add it to /etc/fstab and /etc/exports and reboot. For now I have disabled NFS mount in deepops and doing it myself since I am not sure what else to try.

**Comment by ajdecon** [comment]
That's definitely a weird behavior!

DeepOps is just calling the underling Ansible `mount` module to configure NFS, so I'll dig into the underlying Ansible tooling to see if it's doing something unusual.

In the mean time, I agree that configuring the mount manually in `/etc/fstab` is the best work-around.
