### ISSUE TITLE
OOD internal server error

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#1190]
I am having issues running OOD over a public network. I have my cluster setup using an internal private network (the IPs used in inventory file are all private). I have updated config/group_vars/slurm-cluster.yml with the following:

servername: publicIP
httpd_port: 9050
httpd_listen_addr_port:
  - 9050
DIDNT WORK

servername: public hostname 
httpd_port: 9050
httpd_listen_addr_port:
  - 9050
DIDNT WORK

servername: public hostname 
httpd_port: 80
httpd_listen_addr_port:
  - 80
Login page works, after login page I get redirected to an internal server error.

I have also tired updating the /etc/ood/config/ood_portal.yml file directly after reading the OOD official docs and updating using the command $ sudo /opt/ood/ood-portal-generator/sbin/update_ood_portal
that also fails with:
Generating new Apache config at: '/opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf'
sh: 1: cannot create /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf: Directory nonexistent
chown root:www-data /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
No such file or directory @ apply2files - /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
Run 'update_ood_portal --help' to see a full list of available options.

I would imagine there is a way to have the slurm cluster run on private management ports but have OOD run on a public IP?

**Comment by ajdecon** [comment]
This isn’t a configuration we’ve tested, to be honest!

My own inclination would not be to expose this service directly on a public IP, but instead put it behind a reverse proxy (nginx or apache2) for TLS and better control over the configuration.

In any case, I’d recommend opening an issue with the upstream OOD project, or contacting them via their Discourse server. (https://discourse.openondemand.org/) They’re more likely to have seen configurations like this before and offer good suggestions.

———
Typed with thumbs, please excuse typos!
________________________________
From: arnoldas kurbanovas ***@***.***>
Sent: Tuesday, June 28, 2022 3:44:33 PM
To: NVIDIA/deepops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NVIDIA/deepops] OOD internal server error (Issue #1190)


I am having issues running OOD over a public network. I have my cluster setup using an internal private network (the IPs used in inventory file are all private). I have updated config/group_vars/slurm-cluster.yml with the following:

servername: publicIP
httpd_port: 9050
httpd_listen_addr_port:

  *   9050
DIDNT WORK

servername: public hostname
httpd_port: 9050
httpd_listen_addr_port:

  *   9050
DIDNT WORK

servername: public hostname
httpd_port: 80
httpd_listen_addr_port:

  *   80
Login page works, after login page I get redirected to an internal server error.

I have also tired updating the /etc/ood/config/ood_portal.yml file directly after reading the OOD official docs and updating using the command $ sudo /opt/ood/ood-portal-generator/sbin/update_ood_portal
that also fails with:
Generating new Apache config at: '/opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf'
sh: 1: cannot create /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf: Directory nonexistent
chown root:www-data /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
No such file or directory @ apply2files - /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
Run 'update_ood_portal --help' to see a full list of available options.

I would imagine there is a way to have the slurm cluster run on private management ports but have OOD run on a public IP?
