### ISSUE TITLE
Deepops vs NAT issues

### ISSUE THREAD

**Issue by andrevianadf** [NVIDIA/deepops#1202]
Hi there,
I'm trying to deploy Deepops in 3 VMs, but two in one host and another in a different host.
I didn't want to use the local network, so I created three internal LANs, each LAN per VM, like 10.20.30.0/28, 10.20.40.0/28 and 10.20.50.0/28. So I added routes on each hypervisor to make the communication between my VMs.
When I deployed the Deepops, Etcd failed on the third VM. I checked the logs I noticed that Etcd was trying to connect to a wrong remote address; instead of using the VMs IP that I added to Ansible hosts, the Etcd used the hypervisor IP as Etcd's remote address.
Please, can you help me to set the Etcd IP address on DeepOps?
I tried to change the file deepops/submodules/kubespray/roles/kubespray-defaults/defaults/main.yaml the variable Kube_apiserver_ip to kube_apiserver_ip: "{{ ansible_ssh_host }}" but that didn't work.
Where can I change the apiserver-advertise-address?

**Comment by ajdecon** [comment]
We generally assume that all nodes in a DeepOps cluster will be on the same network, and haven't tested any configuration which uses this kind of more complex routing. This also seems like it's getting into some pretty deep Kubespray configuration, and I'm personally not sure exactly how to get the behavior you want. 

After a short review of the [Kubespray config variables](https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubespray-defaults/defaults/main.yaml#L568), I'd suggest that you might want to try setting `etcd_address` or `etcd_access_address` on a per-host basis in the inventory file. But this is just a guess -- I don't have a test platform that looks like this right now, and this isn't a configuration we plan to add as part of a regular test plan.

To get better guidance, I'd recommend opening an issue on the [Kubespray project](https://github.com/kubernetes-sigs/kubespray/issues) as well. The upstream project is more likely to have seen configurations that look like this before, and has a better understanding of exactly how they set up and configure etcd.

**Comment by andrevianadf** [comment]
@ajdecon Thanks for your help!
I changed those paramenters but didn't make any difference.
I'm getting the same error:

Jul 28 00:16:37 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:16:37.793Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"10.230.42.41:60224","server-name":"","ip-addresses":["10.20.30.2","10.20.50.4","10.20.40.6","127.0.0.1"],"dns-names":["localhost","b0a1ca2509ba","a1af6c1b5efb","32e1ba5f60d1","lb-apiserver.kubernetes.local","etcd.kube-system.svc.cluster.local","etcd.kube-system.svc","etcd.kube-system","etcd"],"error":"tls: \"10.230.42.41\" does not match any of DNSNames [\"localhost\" \"b0a1ca2509ba\" \"a1af6c1b5efb\" \"32e1ba5f60d1\" \"lb-apiserver.kubernetes.local\" \"etcd.kube-system.svc.cluster.local\" \"etcd.kube-system.svc\" \"etcd.kube-system\" \"etcd\"] (lookup etcd on 127.0.0.53:53: server

root@32e1ba5f60d1:~# systemctl status etcd.service
● etcd.service - etcd docker wrapper
     Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-07-28 00:14:43 UTC; 35min ago
    Process: 48845 ExecStartPre=/usr/bin/docker rm -f etcd3 (code=exited, status=0/SUCCESS)
   Main PID: 48868 (etcd)
      Tasks: 22 (limit: 137736)
     Memory: 20.6M
     CGroup: /system.slice/etcd.service
             ├─48868 /bin/bash /usr/local/bin/etcd
             └─48871 /usr/bin/docker run --restart=on-failure:5 --env-file=/etc/etcd.env --net=host -v /etc/ssl/certs:/etc/ssl/certs:ro -v /etc/ssl/etcd/ssl:/etc/ssl/etcd/ssl:ro -v /var/lib>

Jul 28 00:50:25 32e1ba5f60d1 etcd[48871]: {"level":"info","ts":"2022-07-28T00:50:25.710Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"e9725356d753fdb0 received MsgPreVoteRes>
Jul 28 00:50:25 32e1ba5f60d1 etcd[48871]: {"level":"info","ts":"2022-07-28T00:50:25.710Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"e9725356d753fdb0 [logterm: 1, index: 3]>
Jul 28 00:50:25 32e1ba5f60d1 etcd[48871]: {"level":"info","ts":"2022-07-28T00:50:25.710Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"e9725356d753fdb0 [logterm: 1, index: 3]>
Jul 28 00:50:25 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:25.710Z","caller":"rafthttp/peer.go:267","msg":"dropped internal Raft message since sending buffer is full (>
Jul 28 00:50:25 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:25.710Z","caller":"rafthttp/peer.go:267","msg":"dropped internal Raft message since sending buffer is full (>
Jul 28 00:50:28 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:28.885Z","caller":"etcdserver/server.go:2048","msg":"failed to publish local member to cluster through raft">
Jul 28 00:50:29 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:29.096Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-na>
Jul 28 00:50:29 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:29.096Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-na>
Jul 28 00:50:29 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:29.107Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-na>
Jul 28 00:50:29 32e1ba5f60d1 etcd[48871]: {"level":"warn","ts":"2022-07-28T00:50:29.107Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-na>
root@32e1ba5f60d1:~#

**Comment by ajdecon** [comment]
Got it. Yep, would definitely recommend asking for help in the Kubespray project for this.

**Comment by andrevianadf** [comment]
Thanks @ajdecon !
