### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by anateshan** [NVIDIA/deepops#1203]
Error running script ./scripts/setup.sh

Current version of Ansible is 2.9.27
cp: cannot create directory './config': Permission denied
Copied default configuration to ./config
Updating Ansible Galaxy roles...
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/deepops/collections'
ERROR! Unexpected Exception, this is probably a bug: list index out of range
ERROR! The requirements file '/deepops/config/requirements.yml' does not exist.
ERROR! The requirements file 'config/requirements.yml' does not exist.
error: could not lock config file .git/config: Permission denied
error: could not lock config file .git/config: Permission denied
fatal: Failed to register url for submodule path 'submodules/charts'
[WARNING]: Unable to parse /deepops/config/inventory as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

PLAY [Ansible Ad-Hoc] ***********************************************************************************************************************************************************************

TASK [lineinfile] ***************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by ajdecon** [comment]
You probably want to check the file permissions on your DeepOps checkout. You should generally clone the DeepOps repository and run DeepOps scripts as the same user.

**Comment by anateshan** [comment]
Tried  clone and run script as the same user, worked for me :)
