### ISSUE TITLE
Rootless docker not working with slurm 

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#1206]
Steps to reproduce:

(env) arnoldas@XCITEMAIN:~/deepops$ ansible-playbook -K --limit slurm-cluster playbooks/container/docker-rootless.yml
Installation completes successfully without any errors

Info:
(env) arnoldas@dgx-a100:/sw/software/rootless-docker/bin$ /sw/software/rootless-docker/bin/docker -v
Docker version 20.10.17, build 100c701
(env) arnoldas@dgx-a100:/sw/software/rootless-docker/bin$ docker -v
Docker version 20.10.17, build 100c701

Test with slurm:
(env) arnoldas@XCITEMAIN:~/deepops$ srun --ntasks=1 --gpus-per-task=1 --cpus-per-task=5 --gres-flags=enforce-binding --pty bash
(env) arnoldas@dgx-a100:~/deepops$ module load rootless-docker
(env) arnoldas@dgx-a100:~/deepops$ start_rootless_docker.sh
+ [ -w /var/tmp/xdg_runtime_dir_1000 ]
+ [ -d /home/arnoldas ]
+ rootlesskit=
+ command -v docker-rootlesskit
+ command -v rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ : 
+ : 
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z  ]
+ command -v slirp4netns
+ [ -z  ]
+ command -v vpnkit
+ net=vpnkit
+ [ -z  ]
+ mtu=1500
+ [ -z  ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ id -u
+ [ 1000 = 0 ]
+ command -v selinuxenabled
+ exec rootlesskit --net=vpnkit --mtu=1500 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /sw/software/rootless-docker/bin/dockerd-rootless.sh --experimental --data-root=/var/tmp/docker-container-storage-1000 --storage-driver overlay2
+ [ -w /var/tmp/xdg_runtime_dir_1000 ]
+ [ -d /home/arnoldas ]
+ rootlesskit=
+ command -v docker-rootlesskit
+ command -v rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ : 
+ : 
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z  ]
+ command -v slirp4netns
+ [ -z  ]
+ command -v vpnkit
+ net=vpnkit
+ [ -z  ]
+ mtu=1500
+ [ -z 1 ]
+ [ 1 = 1 ]
+ rm -f /run/docker /run/containerd /run/xtables.lock
+ [ -n  ]
+ stat -c %T -f /etc
+ [ tmpfs = tmpfs ]
+ [ -L /etc/ssl ]
+ realpath /etc/ssl
+ realpath_etc_ssl=/etc/.ro4023754510/ssl
+ rm -f /etc/ssl
+ mkdir /etc/ssl
+ mount --rbind /etc/.ro4023754510/ssl /etc/ssl
+ exec dockerd --experimental --data-root=/var/tmp/docker-container-storage-1000 --storage-driver overlay2
Cannot connect to the Docker daemon at unix:///var/tmp/xdg_runtime_dir_1000/docker.sock. Is the docker daemon running?
INFO[2022-08-02T18:25:13.425485562Z] Starting up                                  
WARN[2022-08-02T18:25:13.458101347Z] Running experimental build                   
WARN[2022-08-02T18:25:13.477482978Z] Running in rootless mode. This mode has feature limitations. 
INFO[2022-08-02T18:25:13.493072017Z] Running with RootlessKit integration         
WARN[2022-08-02T18:25:19.484317619Z] could not change group /var/tmp/xdg_runtime_dir_1000/docker.sock to docker: group docker not found 
INFO[2022-08-02T18:25:20.508545007Z] libcontainerd: started new containerd process  pid=931470
INFO[2022-08-02T18:25:20.627170450Z] parsed scheme: "unix"                         module=grpc
INFO[2022-08-02T18:25:20.685412267Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-08-02T18:25:20.786317690Z] ccResolverWrapper: sending update to cc: {[{unix:///var/tmp/xdg_runtime_dir_1000/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-08-02T18:25:20.850775453Z] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2022-08-02T18:25:22.188559397Z] grpc: addrConn.createTransport failed to connect to {unix:///var/tmp/xdg_runtime_dir_1000/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/tmp/xdg_runtime_dir_1000/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
[rootlesskit:child ] error: command [/sw/software/rootless-docker/bin/dockerd-rootless.sh --experimental --data-root=/var/tmp/docker-container-storage-1000 --storage-driver overlay2] exited: signal: killed
Cannot connect to the Docker daemon at unix:///var/tmp/xdg_runtime_dir_1000/docker.sock. Is the docker daemon running?
[rootlesskit:parent] error: child exited: exit status 255
Cannot connect to the Docker daemon at unix:///var/tmp/xdg_runtime_dir_1000/docker.sock. Is the docker daemon running?

**Comment by avolkov1** [comment]
For rootless docker to work a few things have to be setup correctly. Which OS are you running on? It should work on any recent Ubuntu (18 or above) or CentOS/RHEL 8. On CentOS/RHEL 7 it doesn't work very well.

Check for br_netfilter kernel module. Refer to doc here:
https://github.com/NVIDIA/deepops/blob/master/docs/container/docker-rootless.md
```
lsmod | grep br_netfilter
```

Also, your user id needs to be added to /etc/subuid and /etc/subgid. Usually this is done via Slurm prolog, or do it permanently via:
```
echo ${userid}:${mysubuid}:65536 >> /etc/subuid
echo ${userid}:${mysubgid}:65536 >> /etc/subgid
```
If you setup Slurm via deepops there should be a prolog "95-all-rootless" that does this. It's actually done indirectly via "singularity".
https://github.com/NVIDIA/deepops/blob/master/roles/slurm/templates/etc/slurm/prolog.d/95-all-rootless

**Comment by arnoldas500** [comment]
I am running this on Ubuntu 20.04.
br_netfilter kernel module is running:
$ lsmod | grep br_netfilter
br_netfilter           28672  0
bridge                176128  1 br_netfilter

My user ids have already been added to /etc/subuid & /etc/subgid:
$ more /etc/subuid
lxd:100000:65536
root:100000:65536
arnoldas:165536:65536
ood:231072:65536
test:296608:65536

$ more /etc/subgid
lxd:100000:65536
root:100000:65536
arnoldas:165536:65536
ood:231072:65536
test:296608:65536

**Comment by avolkov1** [comment]
Can you check if this directory: `/var/tmp/xdg_runtime_dir_1000/` exists and if there are any contents in it?

**Comment by arnoldas500** [comment]
Directory is there, here are the content:
/var/tmp/xdg_runtime_dir_1000$ ls
docker    docker.sock

**Comment by avolkov1** [comment]
The one odd thing I see is you get this warning:
```
WARN[2022-08-02T18:25:19.484317619Z] could not change group /var/tmp/xdg_runtime_dir_1000/docker.sock to docker: group docker not found
```

Try adding docker group on your system:
```
$ sudo groupadd docker
```
Then try starting up rootless docker again. Do you still get that warning?

**Comment by arnoldas500** [comment]
That seems to have fixed the issue for the primary user. Now the issue I am having is if I add a new system and slurm user I am getting bash: module: command not found

Steps to reproduce:
headnode$ sudo su testuser
headnodde$ srun --ntasks=1 --gpus-per-task=1 --cpus-per-task=5 --gres-flags=enforce-binding --pty bash
compute01$ module avail
module: command not found

**Comment by arnoldas500** [comment]
That did the trick, thank you!

**Comment by avolkov1** [comment]
Great!

Regarding the module stuff, I am not sure how the various files are sourced. It's either via bashrc or one of the profile files. Sometimes if the user is added without one of those files they won't get the modules loaded automatically. But you should be able to explicitly init modules via:
```
source /etc/profile.d/lmod.sh
```
Which in turns does something like this:
```
source /usr/share/lmod/lmod/init/${SHELL}
# for bash it should be: source /usr/share/lmod/lmod/init/bash
```
So either one above, I think will enable module function.
