### ISSUE TITLE
Per OS Settings

### ISSUE THREAD

**Issue by ryanolson** [NVIDIA/deepops#121]
@dholt @lukeyeager 

Proposal:

Add OS specific group_var files in `config/group_vars`, e.g. 
- `config/group_vars/coreos.yml`
- `config/group_vars/ubuntu.yml`
- `config/group_vars/ubuntu1804.yml`

In `config/inventory`, add OS groups where hosts can be listed
```
[coreos]
core01
core02
core03

[ubuntu1804]
login # this machine would inherit from both ubuntu and ubuntu1804 group vars

[ubuntu:children]
ubuntu1804
```

This has worked well for my CoreOS + Ubuntu hybrid cluster.

**Comment by dholt** [comment]
What does this get us? Ansible is usually organized by roles/tasks, not OS, so it's up to the role to support various OSes.

**Comment by ryanolson** [comment]
There have been a few rare occurrences when I have needed to sent an os-specific value of a variable. 

The one that comes to mind is the location of the python interpreter.  Specifically, I had to set that variable for CoreOS/ContaineLinux.

**Comment by lukeyeager** [comment]
I can see how that could be useful in theory. But at this point, without some real use-cases, it just seems like extra clutter in the inventory and the config dir.

**Comment by supertetelman** [comment]
We've managed to control this in roles/playbooks. Closing this issue.
