### ISSUE TITLE
verify all GPU nodes plug-ins in the Kubernetes cluster Fails

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#1211]
running ./scripts/k8s/verify_gpu.sh fails:

Steps to reproduce:
kubectl get nodes
NAME                        STATUS   ROLES                  AGE     VERSION
dgx-a100                    Ready    <none>                 6m6s    v1.22.8
xcitemain                   Ready    control-plane,master   7m16s   v1.22.8

Starting './scripts/k8s/verify_gpu.sh';  DeepOps version ''
job_name=cluster-gpu-tests
total_gpus=0
Creating/Deleting sandbox Namespace
updating test yml
downloading containers ...
job.batch/cluster-gpu-tests condition met
executing ...
No resources found in cluster-gpu-verify namespace.
GPU verification can't be executed, please check GPU node directly

Other important info:
Compute node is a dgx a100
deepops_gpu_operator_enabled and gpu_operator_preinstalled_nvidia_software flags are set to true

running an example workload like kubectl create -f tensorflow-notebook.yml fails with 0/2 nodes are available: 2 Insufficient nvidia.com/gpu.

kubectl describe node dgx-a100 does not list any gpus

After running ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml pods are stuck in CrashLoopBackOff:
nvidia-gpu-operator-node-feature-discovery-worker-fwrnv        -On headnode (not sure if this is even suppose to try to run on the headnode since it doesn't have any GPUs)
Pod logs:
I0811 20:54:50.804182 1 component.go:36] [core]Subchannel picks a new address "nvidia-gpu-operator-node-feature-discovery-master:8080" to connect
I0811 20:54:50.804305 1 component.go:36] [core]Channel Connectivity change to CONNECTING
I0811 20:55:08.122219 1 component.go:36] [core]Channel Connectivity change to SHUTDOWN
I0811 20:55:08.122280 1 component.go:36] [core]Subchannel Connectivity change to SHUTDOWN
F0811 20:55:08.122354 1 main.go:64] failed to connect: context deadline exceeded

nvidia-gpu-operator-node-feature-discovery-worker-hfq8w        -On dgx-a100
Pod Logs:
W0811 20:55:01.098875 1 component.go:41] [core]grpc: addrConn.createTransport failed to connect to {nvidia-gpu-operator-node-feature-discovery-master:8080 nvidia-gpu-operator-node-feature-discovery-master:8080 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout". Reconnecting...
I0811 20:55:01.098891 1 component.go:36] [core]Subchannel Connectivity change to TRANSIENT_FAILURE
I0811 20:55:01.098907 1 component.go:36] [core]Channel Connectivity change to TRANSIENT_FAILURE
I0811 20:55:02.929894 1 component.go:36] [core]Subchannel Connectivity change to CONNECTING
I0811 20:55:02.929915 1 component.go:36] [core]Subchannel picks a new address "nvidia-gpu-operator-node-feature-discovery-master:8080" to connect
I0811 20:55:02.929967 1 component.go:36] [core]Channel Connectivity change to CONNECTING
I0811 20:55:20.097361 1 component.go:36] [core]Channel Connectivity change to SHUTDOWN
I0811 20:55:20.097382 1 component.go:36] [core]Subchannel Connectivity change to SHUTDOWN
F0811 20:55:20.097395 1 main.go:64] failed to connect: context deadline exceeded

nvidia-smi returns gpus correctly with docker run --gpus=all flag

contents of docker daemon.json 
{
    "default-runtime": "nvidia",
    "default-shm-size": "1G",
    "default-ulimits": {
        "memlock": {
            "hard": -1,
            "name": "memlock",
            "soft": -1
        },
        "stack": {
            "hard": 67108864,
            "name": "stack",
            "soft": 67108864
        }
    },
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

**Comment by supertetelman** [comment]
This seems like a legitimate issue with this installation of the gpu operator. 

Is this running DGX OS and can you share the version from /etc/dgx-release?

It may be that you have installed something odd into the node or an uninstall reinstall of the operator may fix this.  Your configuration looks correct.

**Comment by arnoldas500** [comment]
Yes running DGX OS, Here is the output of /etc/dgx-release:
DGX_NAME="DGX Server"
DGX_PRETTY_NAME="NVIDIA DGX Server"
DGX_SWBUILD_DATE="2020-10-26-11-53-11"
DGX_SWBUILD_VERSION="5.0.0"
DGX_COMMIT_ID="7501dff"
DGX_PLATFORM="DGX Server for DGX A100"
DGX_SERIAL_NUMBER="***"

DGX_OTA_VERSION="5.3.1"
DGX_OTA_DATE="Fri 24 Jun 2022 02:09:07 PM EDT"

I have tried removing the node and re adding it without success. Even tried resetting the cluster running ansible-playbook submodules/kubespray/reset.yml but still no luck.

**Comment by arnoldas500** [comment]
not sure if this is related but cannot access kubectl on compute node:
(env) arnoldas@dgx-a100:~$ which kubectl
(env) arnoldas@dgx-a100:~$ /usr/local/bin/kubectl
-bash: /usr/local/bin/kubectl: No such file or directory

**Comment by arnoldas500** [comment]
> 

Any fix for this yet? Or known release version that works?

**Comment by TranThanh96** [comment]
HI ? any update please ? I have meet an issue like this

**Comment by supertetelman** [comment]
The Kubectl binary is only downloaded on a subset of nodes, so that is not an issue here.

I have been unable to reproduce this behavior on my internal DGX and EGX test nodes doing a fresh install of the last 2 DeepOps releases on Ubuntu 20.04 using the default config variables.

If you are still having this issue would you be able to share the list of running Pods in the `gpu-operator-resources` namespace and the logs of any failing Pods?
