### ISSUE TITLE
OpenOnDemand 2.0 releasing .deb files today

### ISSUE THREAD

**Issue by johrstrom** [NVIDIA/deepops#1212]
Hi - we've backported support for Ubuntu 18.04 and 20.04 in OnDemand 2.0 now such that we're releasing `.deb` files so folks don't have to install by source anymore (which is a pain and quite flaky).

We should be releasing `2.0.28` today to the general public, with ansible updates to boot. So you likely shouldn't use `install_from_src` anymore.

related to/could fix #1210

**Comment by johrstrom** [comment]
`2.0.28` is now on our public 2.0 repository. Version `v2.0.7` of `osc.open_ondemand` on galaxy has the updates that'll handle installing on Ubuntu 18.04 and 20.04.

**Comment by arnoldas500** [comment]
Before installing using .deb files, is there an easy way to uninstall onDemand if you had previously installed it from source (cant seem to find any ansible playbook to do it)? So far I have deleted: /etc/ood  /etc/sudoers.d/ood  /opt/ood  /var/www/ood

**Comment by johrstrom** [comment]
> So far I have deleted: /etc/ood /etc/sudoers.d/ood /opt/ood /var/www/ood

That's a pretty good start. I also found this `.so` that we built that you'll want to get rid of. I don't know if this will be 2.5.0 or 2.7.0 for you.

```
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/passenger_native_support.so
```

**Comment by arnoldas500** [comment]
I have ruby 2.7.0 but that file does not seem to be present. Here is a list of what I currently have in that directory:
`bigdecimal.so    coverage.so   digest     etc.so    fiddle.so  json        objspace.so  psych.so  rbconfig     ripper.so  stringio.so  zlib.so
cgi              date_core.so  digest.so  fcntl.so  gdbm.so    monitor.so  openssl.so   pty.so    rbconfig.rb  sdbm.so    strscan.so
continuation.so  dbm.so        enc        fiber.so  io         nkf.so      pathname.so  racc      readline.so  socket.so  syslog.so
`

**Comment by johrstrom** [comment]
ping to keep open. installing the .deb is likely much more stable than compiling it.
