### ISSUE TITLE
DeepOps deploys 510.85.02 driver graphics card by default for both k8s and slurm

### ISSUE THREAD

**Issue by SupermicroML** [NVIDIA/deepops#1215]
When a cluster is deployed with **nvidia_driver_ubuntu_branch: "510"**, DeepOps pulls up  510.85.02. This is graphics card driver for RTX GPUs, and doesn't work with A100 GPUs.

Perhaps one should change to nvidia_driver_ubuntu_branch: "515".

root@as-4124gs-tnr:~# nvidia-smi
Thu Aug 18 21:48:28 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  On   | 00000000:01:00.0 Off |                    0 |
| N/A   54C    P0    59W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80G...  On   | 00000000:25:00.0 Off |                    0 |
| N/A   55C    P0    61W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80G...  On   | 00000000:41:00.0 Off |                    0 |
| N/A   55C    P0    66W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80G...  On   | 00000000:61:00.0 Off |                    0 |
| N/A   50C    P0    63W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100 80G...  On   | 00000000:81:00.0 Off |                    0 |
| N/A   52C    P0    59W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100 80G...  On   | 00000000:A1:00.0 Off |                    0 |
| N/A   52C    P0    60W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100 80G...  On   | 00000000:C1:00.0 Off |                    0 |
| N/A   51C    P0    58W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100 80G...  On   | 00000000:E1:00.0 Off |                    0 |
| N/A   47C    P0    56W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by dholt** [comment]
This should be fixed by #1216

**Comment by SupermicroML** [comment]
Yes, after I checked on NVIDIA web page 510.85.02 is supporting A100.
