### ISSUE TITLE
Openshift install fails Ubuntu 20.04

### ISSUE THREAD

**Issue by dewilkin** [NVIDIA/deepops#1221]
TASK [openshift : install openshift python client for k8s_raw module]
fatal: [mgmt01]: FAILED! => changed=false 
  cmd:
  - /opt/deepops/env/bin/pip3
  - install
  - openshift
  msg: |2-
  
    :stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fadf36e68b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openshift/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fadf3ecdaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openshift/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fadf3e970d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openshift/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fadf36e2fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openshift/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fadf36e2490>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openshift/
    ERROR: Could not find a version that satisfies the requirement openshift (from versions: none)
    ERROR: No matching distribution found for openshift

**Comment by ajdecon** [comment]
This looks like the external network is not reachable from the host where you're running the command.

First: do you get the same result with a retry of the playbook?

Second: do you see errors like this if you try to manually run the command `pip3 install openshift` on the host?

**Comment by dewilkin** [comment]
I think the issue is all these servers are behind a proxy.  I thought that setting up scripts/deepops/proxy.sh would be sufficient?   Do I need to set up the proxy environment variables on every host as well?
