### ISSUE TITLE
Deploy Kubernetes and SLRUM Offline

### ISSUE THREAD

**Issue by jittu11** [NVIDIA/deepops#1227]
Hi Team,

I need to know the feasibility of implementing DGX A 100 with deepops as a clustermanager in an air gapped environment. can we able to implement kubernetes and Slrum offline. Can i get some idea on this?

**Comment by ajdecon** [comment]
DeepOps has very limited support for air-gapped deployments, and we don't currently have tested procedures for either Kubernetes or Slurm in this model. We have some additional documentation on this [here](https://github.com/NVIDIA/deepops/tree/master/docs/airgap).

[NVIDIA Bright Cluster Manager](https://www.nvidia.com/en-us/data-center/bright-cluster-manager/) does provide air gap support, including a [documented procedure for Kubernetes deployments](https://kb.brightcomputing.com/knowledge-base/installing-kubernetes-on-air-gapped-systems/). If you're looking for a well-tested process, I'd probably suggest using Bright for this.

**Comment by jittu11** [comment]
Hi Team,

I am planning to use RHEL , can we able to implement hybrid cluster with Deepops on RHEL.
