### ISSUE TITLE
Deploy hybrid cluster with DeeopOps on RHEL

### ISSUE THREAD

**Issue by jittu11** [NVIDIA/deepops#1228]
Hi Team,

I am planning to use RHEL , can we able to implement hybrid cluster with Deepops on RHEL.

**Comment by ajdecon** [comment]
From the [README](https://github.com/NVIDIA/deepops#hybrid-clusters):

> DeepOps does not test or support a configuration where both Kubernetes and Slurm are deployed on the same physical cluster.
> 
> [NVIDIA Bright Cluster Manager](https://www.brightcomputing.com/brightclustermanager) is recommended as an enterprise solution which enables managing multiple workload managers within a single cluster, including Kubernetes, Slurm, Univa Grid Engine, and PBS Pro.
> 
> DeepOps does not test or support a configuration where nodes have a heterogenous OS running. Additional modifications are needed if you plan to use unsupported operating systems such as RHEL.
