### ISSUE TITLE
Cluster creation getting failed

### ISSUE THREAD

**Issue by saingithub** [NVIDIA/deepops#1230]
I was deployed mater node and it is ready and running.

But the cluster creation step got exciting at the below task
TASK [rsyslog-client : configure syslog forwarding] *************************************************************************************

No error also getting in debug mode.

Please help me on this

**Comment by ajdecon** [comment]
> But the cluster creation step got exciting at the below task

While I often find syslog exciting :wink: it's not clear to me what the actual issue you're seeing is. There is no error in your description, and you don't describe how the failure is occurring.

Can you please provide a full log of your Ansible run (preferably in a [gist](https://gist.github.com/)) and describe the problem you're facing?

**Comment by saingithub** [comment]
After the below task which was completed as ok
TASK [rsyslog-client : configure syslog forwarding] ********************************************************************************************************************************************************************************************************************************************
task path: /root/deepops/roles/rsyslog-client/tasks/main.yml:7

The ansible execution get stopped
PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************************************
dgx                        : ok=5    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
dgxmgt                     : ok=676  changed=49   unreachable=0    failed=0    skipped=1250 rescued=0    ignored=0
