### ISSUE TITLE
Deepops upgrade issue v21.06

### ISSUE THREAD

**Issue by subasathees** [NVIDIA/deepops#1233]
Unable to upgrade deepops , tried multiple ways and getting failed with different errors, below are the details.

Current Setup:

> OS: Ubuntu 18.04.6 LTS
> Deepops: tags/21.06
> Kubernet_Version: v1.19.9

**Question 1:** can we upgrade deepops in order like from 21.06 to 21.09 then , from  21.09 to  22.01 , or can we directly move from 21.06 to 22.01

**Question 2:**  Following below procedure and getting errors:
   ### Upgrade Deepops:
```
   cd deepops
   git checkout tags/21.09
   ./scripts/setup.sh
   ansible all -m raw -a "hostname" -K
   ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml -K
```
   
   ERROR:
<sup>   TASK [download : prep_kubeadm_images | Check kubeadm version matches kubernetes version] *******************************************************************************
fatal: [ml-m1]: FAILED! => 
  msg: |-
    The conditional check 'not kubeadm_version == downloads.kubeadm.version' failed. The error was: error while evaluating conditional (not kubeadm_version == downloads.kubeadm.version): {'netcheck_server': {'enabled': '{{ deploy_netchecker }}', 'container': True, 'repo': '{{ netcheck_server_image_repo }}', 'tag': '{{ netcheck_server_image_tag }}', 'sha256': '{{ netcheck_server_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'netcheck_agent': {'enabled': '{{ deploy_netchecker }}', 'container': True, 'repo': '{{ netcheck_agent_image_repo }}', 'tag': '{{ netcheck_agent_image_tag }}', 'sha256': '{{ netcheck_agent_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'etcd': {'container': "{{ etcd_deployment_type != 'host' }}", 'file': "{{ etcd_deployment_type == 'host' }}", 'enabled': True, 'version': '{{ etcd_version }}', 'dest': '{{ local_release_dir }}/etcd-{{ etcd_version }}-linux-{{ image_arch }}.tar.gz', 'repo': '{{ etcd_image_repo }}', 'tag': '{{ etcd_image_tag }}', 'sha256': "{{ etcd_binary_checksum if (etcd_deployment_type == 'host') else etcd_digest_checksum|d(None) }}", 'url': '{{ etcd_download_url }}', 'unarchive': "{{ etcd_deployment_type == 'host' }}", 'owner': 'root', 'mode': '0755', 'groups': ['etcd']}, 'cni': {'enabled': True, 'file': True, 'version': '{{ cni_version }}', 'dest': '{{ local_release_dir }}/cni-plugins-linux-{{ image_arch }}-{{ cni_version }}.tgz', 'sha256': '{{ cni_binary_checksum }}', 'url': '{{ cni_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'kubeadm': {'enabled': True, 'file': True, 'version': '{{ kubeadm_version }}', 'dest': '{{ local_release_dir }}/kubeadm-{{ kubeadm_version }}-{{ image_arch }}', 'sha256': '{{ kubeadm_binary_checksum }}', 'url': '{{ kubeadm_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'kubelet': {'enabled': True, 'file': True, 'version': '{{ kube_version }}', 'dest': '{{ local_release_dir }}/kubelet-{{ kube_version }}-{{ image_arch }}', 'sha256': '{{ kubelet_binary_checksum }}', 'url': '{{ kubelet_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'kubectl': {'enabled': True, 'file': True, 'version': '{{ kube_version }}', 'dest': '{{ local_release_dir }}/kubectl-{{ kube_version }}-{{ image_arch }}', 'sha256': '{{ kubectl_binary_checksum }}', 'url': '{{ kubectl_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['kube_control_plane']}, 'crictl': {'file': True, 'enabled': "{{ container_manager in ['crio', 'cri', 'containerd'] }}", 'version': '{{ crictl_version }}', 'dest': '{{ local_release_dir }}/crictl-{{ crictl_version }}-linux-{{ image_arch }}.tar.gz', 'sha256': '{{ crictl_binary_checksum }}', 'url': '{{ crictl_download_url }}', 'unarchive': True, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'crun': {'file': True, 'enabled': '{{ crun_enabled }}', 'version': '{{ crun_version }}', 'dest': '{{ local_release_dir }}/crun', 'sha256': '{{ crun_binary_checksum }}', 'url': '{{ crun_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'kata_containers': {'enabled': '{{ kata_containers_enabled }}', 'file': True, 'version': '{{ kata_containers_version }}', 'dest': '{{ local_release_dir }}/kata-static-{{ kata_containers_version }}-{{ image_arch }}.tar.xz', 'sha256': '{{ kata_containers_binary_checksum }}', 'url': '{{ kata_containers_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'nerdctl': {'file': True, 'enabled': '{{ nerdctl_enabled }}', 'version': '{{ nerdctl_version }}', 'dest': '{{ local_release_dir }}/nerdctl-{{ nerdctl_version }}-linux-{{ image_arch }}.tar.gz', 'sha256': '{{ nerdctl_archive_checksum }}', 'url': '{{ nerdctl_download_url }}', 'unarchive': True, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'cilium': {'enabled': "{{ kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool }}", 'container': True, 'repo': '{{ cilium_image_repo }}', 'tag': '{{ cilium_image_tag }}', 'sha256': '{{ cilium_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'cilium_init': {'enabled': "{{ kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool }}", 'container': True, 'repo': '{{ cilium_init_image_repo }}', 'tag': '{{ cilium_init_image_tag }}', 'sha256': '{{ cilium_init_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'cilium_operator': {'enabled': "{{ kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool }}", 'container': True, 'repo': '{{ cilium_operator_image_repo }}', 'tag': '{{ cilium_operator_image_tag }}', 'sha256': '{{ cilium_operator_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'multus': {'enabled': '{{ kube_network_plugin_multus }}', 'container': True, 'repo': '{{ multus_image_repo }}', 'tag': '{{ multus_image_tag }}', 'sha256': '{{ multus_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'flannel': {'enabled': "{{ kube_network_plugin == 'flannel' or kube_network_plugin == 'canal' }}", 'container': True, 'repo': '{{ flannel_image_repo }}', 'tag': '{{ flannel_image_tag }}', 'sha256': '{{ flannel_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'calicoctl': {'enabled': "{{ kube_network_plugin == 'calico' or kube_network_plugin == 'canal' }}", 'file': True, 'version': '{{ calico_ctl_version }}', 'dest': '{{ local_release_dir }}/calicoctl', 'sha256': '{{ calicoctl_binary_checksum }}', 'url': '{{ calicoctl_download_url }}', 'unarchive': False, 'owner': 'root', 'mode': '0755', 'groups': ['k8s_cluster']}, 'calico_node': {'enabled': "{{ kube_network_plugin == 'calico' or kube_network_plugin == 'canal' }}", 'container': True, 'repo': '{{ calico_node_image_repo }}', 'tag': '{{ calico_node_image_tag }}', 'sha256': '{{ calico_node_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'calico_cni': {'enabled': "{{ kube_network_plugin == 'calico' or kube_network_plugin == 'canal' }}", 'container': True, 'repo': '{{ calico_cni_image_repo }}', 'tag': '{{ calico_cni_image_tag }}', 'sha256': '{{ calico_cni_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'calico_policy': {'enabled': "{{ enable_network_policy and kube_network_plugin in ['calico', 'canal'] }}", 'container': True, 'repo': '{{ calico_policy_image_repo }}', 'tag': '{{ calico_policy_image_tag }}', 'sha256': '{{ calico_policy_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'calico_typha': {'enabled': '{{ typha_enabled }}', 'container': True, 'repo': '{{ calico_typha_image_repo }}', 'tag': '{{ calico_typha_image_tag }}', 'sha256': '{{ calico_typha_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'calico_crds': {'file': True, 'enabled': "{{ kube_network_plugin == 'calico' and calico_datastore == 'kdd' }}", 'version': '{{ calico_version }}', 'dest': '{{ local_release_dir }}/calico-{{ calico_version }}-kdd-crds/{{ calico_version }}.tar.gz', 'sha256': '{{ calico_crds_archive_checksum }}', 'url': '{{ calico_crds_download_url }}', 'unarchive': True, 'unarchive_extra_opts': ['--strip=6', '--wildcards', '*/_includes/charts/calico/crds/kdd/'], 'owner': 'root', 'mode': '0755', 'groups': ['kube_control_plane']}, 'weave_kube': {'enabled': "{{ kube_network_plugin == 'weave' }}", 'container': True, 'repo': '{{ weave_kube_image_repo }}', 'tag': '{{ weave_kube_image_tag }}', 'sha256': '{{ weave_kube_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'weave_npc': {'enabled': "{{ kube_network_plugin == 'weave' }}", 'container': True, 'repo': '{{ weave_npc_image_repo }}', 'tag': '{{ weave_npc_image_tag }}', 'sha256': '{{ weave_npc_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'ovn4nfv': {'enabled': "{{ kube_network_plugin == 'ovn4nfv' }}", 'container': True, 'repo': '{{ ovn4nfv_k8s_plugin_image_repo }}', 'tag': '{{ ovn4nfv_k8s_plugin_image_tag }}', 'sha256': '{{ ovn4nfv_k8s_plugin_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'kube_ovn': {'enabled': "{{ kube_network_plugin == 'kube-ovn' }}", 'container': True, 'repo': '{{ kube_ovn_container_image_repo }}', 'tag': '{{ kube_ovn_container_image_tag }}', 'sha256': '{{ kube_ovn_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'kube_router': {'enabled': "{{ kube_network_plugin == 'kube-router' }}", 'container': True, 'repo': '{{ kube_router_image_repo }}', 'tag': '{{ kube_router_image_tag }}', 'sha256': '{{ kube_router_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'pod_infra': {'enabled': True, 'container': True, 'repo': '{{ pod_infra_image_repo }}', 'tag': '{{ pod_infra_image_tag }}', 'sha256': '{{ pod_infra_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'install_socat': {'enabled': "{{ ansible_os_family in ['Flatcar Container Linux by Kinvolk'] }}", 'container': True, 'repo': '{{ install_socat_image_repo }}', 'tag': '{{ install_socat_image_tag }}', 'sha256': '{{ install_socat_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'nginx': {'enabled': "{{ loadbalancer_apiserver_localhost and loadbalancer_apiserver_type == 'nginx' }}", 'container': True, 'repo': '{{ nginx_image_repo }}', 'tag': '{{ nginx_image_tag }}', 'sha256': '{{ nginx_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'haproxy': {'enabled': "{{ loadbalancer_apiserver_localhost and loadbalancer_apiserver_type == 'haproxy' }}", 'container': True, 'repo': '{{ haproxy_image_repo }}', 'tag': '{{ haproxy_image_tag }}', 'sha256': '{{ haproxy_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'coredns': {'enabled': "{{ dns_mode in ['coredns', 'coredns_dual'] }}", 'container': True, 'repo': '{{ coredns_image_repo }}', 'tag': '{{ coredns_image_tag }}', 'sha256': '{{ coredns_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}, 'nodelocaldns': {'enabled': '{{ enable_nodelocaldns }}', 'container': True, 'repo': '{{ nodelocaldns_image_repo }}', 'tag': '{{ nodelocaldns_image_tag }}', 'sha256': '{{ nodelocaldns_digest_checksum|default(None) }}', 'groups': ['k8s_cluster']}, 'dnsautoscaler': {'enabled': "{{ dns_mode in ['coredns', 'coredns_dual'] }}", 'container': True, 'repo': '{{ dnsautoscaler_image_repo }}', 'tag': '{{ dnsautoscaler_image_tag }}', 'sha256': '{{ dnsautoscaler_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}, 'helm': {'enabled': '{{ helm_enabled }}', 'file': True, 'version': '{{ helm_version }}', 'dest': '{{ local_release_dir }}/helm-{{ helm_version }}/helm-{{ helm_version }}-linux-{{ image_arch }}.tar.gz', 'sha256': '{{ helm_archive_checksum }}', 'url': '{{ helm_download_url }}', 'unarchive': True, 'owner': 'root', 'mode': '0755', 'groups': ['kube_control_plane']}, 'krew': {'enabled': '{{ krew_enabled }}', 'file': True, 'version': '{{ krew_version }}', 'dest': '{{ local_release_dir }}/krew.tar.gz', 'sha256': '{{ krew_archive_checksum }}', 'url': '{{ krew_download_url }}', 'unarchive': True, 'owner': 'root', 'mode': '0755', 'groups': ['kube_control_plane']}, 'registry': {'enabled': '{{ registry_enabled }}', 'container': True, 'repo': '{{ registry_image_repo }}', 'tag': '{{ registry_image_tag }}', 'sha256': '{{ registry_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'registry_proxy': {'enabled': '{{ registry_enabled }}', 'container': True, 'repo': '{{ registry_proxy_image_repo }}', 'tag': '{{ registry_proxy_image_tag }}', 'sha256': '{{ registry_proxy_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'metrics_server': {'enabled': '{{ metrics_server_enabled }}', 'container': True, 'repo': '{{ metrics_server_image_repo }}', 'tag': '{{ metrics_server_image_tag }}', 'sha256': '{{ metrics_server_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}, 'addon_resizer': {'enabled': '{{ metrics_server_enabled }}', 'container': True, 'repo': '{{ addon_resizer_image_repo }}', 'tag': '{{ addon_resizer_image_tag }}', 'sha256': '{{ addon_resizer_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}, 'local_volume_provisioner': {'enabled': '{{ local_volume_provisioner_enabled }}', 'container': True, 'repo': '{{ local_volume_provisioner_image_repo }}', 'tag': '{{ local_volume_provisioner_image_tag }}', 'sha256': '{{ local_volume_provisioner_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'cephfs_provisioner': {'enabled': '{{ cephfs_provisioner_enabled }}', 'container': True, 'repo': '{{ cephfs_provisioner_image_repo }}', 'tag': '{{ cephfs_provisioner_image_tag }}', 'sha256': '{{ cephfs_provisioner_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'rbd_provisioner': {'enabled': '{{ rbd_provisioner_enabled }}', 'container': True, 'repo': '{{ rbd_provisioner_image_repo }}', 'tag': '{{ rbd_provisioner_image_tag }}', 'sha256': '{{ rbd_provisioner_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'local_path_provisioner': {'enabled': '{{ local_path_provisioner_enabled }}', 'container': True, 'repo': '{{ local_path_provisioner_image_repo }}', 'tag': '{{ local_path_provisioner_image_tag }}', 'sha256': '{{ local_path_provisioner_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'ingress_nginx_controller': {'enabled': '{{ ingress_nginx_enabled }}', 'container': True, 'repo': '{{ ingress_nginx_controller_image_repo }}', 'tag': '{{ ingress_nginx_controller_image_tag }}', 'sha256': '{{ ingress_nginx_controller_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'ingress_ambassador_controller': {'enabled': '{{ ingress_ambassador_enabled }}', 'container': True, 'repo': '{{ ingress_ambassador_image_repo }}', 'tag': '{{ ingress_ambassador_image_tag }}', 'sha256': '{{ ingress_ambassador_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'ingress_alb_controller': {'enabled': '{{ ingress_alb_enabled }}', 'container': True, 'repo': '{{ alb_ingress_image_repo }}', 'tag': '{{ alb_ingress_image_tag }}', 'sha256': '{{ ingress_alb_controller_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'cert_manager_controller': {'enabled': '{{ cert_manager_enabled }}', 'container': True, 'repo': '{{ cert_manager_controller_image_repo }}', 'tag': '{{ cert_manager_controller_image_tag }}', 'sha256': '{{ cert_manager_controller_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'cert_manager_cainjector': {'enabled': '{{ cert_manager_enabled }}', 'container': True, 'repo': '{{ cert_manager_cainjector_image_repo }}', 'tag': '{{ cert_manager_cainjector_image_tag }}', 'sha256': '{{ cert_manager_cainjector_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'cert_manager_webhook': {'enabled': '{{ cert_manager_enabled }}', 'container': True, 'repo': '{{ cert_manager_webhook_image_repo }}', 'tag': '{{ cert_manager_webhook_image_tag }}', 'sha256': '{{ cert_manager_webhook_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'csi_attacher': {'enabled': '{{ cinder_csi_enabled or aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ csi_attacher_image_repo }}', 'tag': '{{ csi_attacher_image_tag }}', 'sha256': '{{ csi_attacher_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'csi_provisioner': {'enabled': '{{ cinder_csi_enabled or aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ csi_provisioner_image_repo }}', 'tag': '{{ csi_provisioner_image_tag }}', 'sha256': '{{ csi_provisioner_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'csi_snapshotter': {'enabled': '{{ cinder_csi_enabled or aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ csi_snapshotter_image_repo }}', 'tag': '{{ csi_snapshotter_image_tag }}', 'sha256': '{{ csi_snapshotter_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'snapshot_controller': {'enabled': '{{ cinder_csi_enabled }}', 'container': True, 'repo': '{{ snapshot_controller_image_repo }}', 'tag': '{{ snapshot_controller_image_tag }}', 'sha256': '{{ snapshot_controller_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'csi_resizer': {'enabled': '{{ cinder_csi_enabled or aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ csi_resizer_image_repo }}', 'tag': '{{ csi_resizer_image_tag }}', 'sha256': '{{ csi_resizer_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'csi_node_driver_registrar': {'enabled': '{{ cinder_csi_enabled or aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ csi_node_driver_registrar_image_repo }}', 'tag': '{{ csi_node_driver_registrar_image_tag }}', 'sha256': '{{ csi_node_driver_registrar_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'cinder_csi_plugin': {'enabled': '{{ cinder_csi_enabled }}', 'container': True, 'repo': '{{ cinder_csi_plugin_image_repo }}', 'tag': '{{ cinder_csi_plugin_image_tag }}', 'sha256': '{{ cinder_csi_plugin_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'aws_ebs_csi_plugin': {'enabled': '{{ aws_ebs_csi_enabled }}', 'container': True, 'repo': '{{ aws_ebs_csi_plugin_image_repo }}', 'tag': '{{ aws_ebs_csi_plugin_image_tag }}', 'sha256': '{{ aws_ebs_csi_plugin_digest_checksum|default(None) }}', 'groups': ['kube_node']}, 'dashboard': {'enabled': '{{ dashboard_enabled }}', 'container': True, 'repo': '{{ dashboard_image_repo }}', 'tag': '{{ dashboard_image_tag }}', 'sha256': '{{ dashboard_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}, 'dashboard_metrics_scrapper': {'enabled': '{{ dashboard_enabled }}', 'container': True, 'repo': '{{ dashboard_metrics_scraper_repo }}', 'tag': '{{ dashboard_metrics_scraper_tag }}', 'sha256': '{{ dashboard_digest_checksum|default(None) }}', 'groups': ['kube_control_plane']}}: {{ helm_archive_checksums[image_arch][helm_version] }}: 'dict object' has no attribute 'v3.5.3'
  
    The error appears to be in '/home/sathees/deepops/submodules/kubespray/roles/download/tasks/prep_kubeadm_images.yml': line 2, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
    ---
    - name: prep_kubeadm_images | Check kubeadm version matches kubernetes version
      ^ here
</sup>

**Comment by teramucho** [comment]
missing .git/submodules

cat deepops/.gitmodules
```
[submodule "kubespray"]
path = submodules/kubespray
url = https://github.com/kubernetes-sigs/kubespray.git
[submodule "packer-maas"]
path = submodules/packer-maas
url = https://github.com/DeepOps/packer-maas.git
```


$ git submodule init
$ git submodule update

**Comment by subasathees** [comment]
> missing .gitmodules
> 
> https://github.com/NVIDIA/deepops/blob/3ff29429e8e9925e4107270730a14b2cc69ee73e/.gitmodules
> 
> cat deepops/.gitmodules
> 
> ```
> [submodule "kubespray"]
> path = submodules/kubespray
> url = https://github.com/kubernetes-sigs/kubespray.git
> [submodule "packer-maas"]
> path = submodules/packer-maas
> url = https://github.com/DeepOps/packer-maas.git
> ```
> 
> $ git submodule init $ git submodule update
> 
> or
> 
> $ git submodule add https://github.com/kubernetes-sigs/kubespray.git submodule/kubespray

Thanks @teramucho for your reply, but this .gitmodules are already present and throwing the same error

**Comment by dholt** [comment]
Have you compared your existing configuration with the configuration in the new version (`config.example` directory)? It should be  possible to skip versions when upgrading, but you'll likely have a greater number of changed variables, so you'll want to do a side-by-side comparison to make sure you've updated things like version numbers

**Comment by subasathees** [comment]
> Have you compared your existing configuration with the configuration in the new version (`config.example` directory)? It should be possible to skip versions when upgrading, but you'll likely have a greater number of changed variables, so you'll want to do a side-by-side comparison to make sure you've updated things like version numbers

Thanks for the reply. This issue is resolved now. did comparison of the config.example and updated required files. Upgrade completed successfully now. we can close this.

**Comment by dholt** [comment]
Following up on this older issue as part of the resumed DeepOps release cadence: direct in-place upgrades across many releases (such as 21.06 to current) are not a supported single step. Since the 26.05 release, the upgrade documentation explicitly describes the staged-upgrade / redeploy path for much older clusters (see `docs/deepops/update-deepops.md` on current master). If you are still operating an older deployment, the practical route is a staged upgrade or a fresh deploy on a current release (26.07 at the time of writing). If you hit concrete problems on a current release, please open a new issue.
