### ISSUE TITLE
2 slurm clusters in Deepops

### ISSUE THREAD

**Issue by meeshel78** [NVIDIA/deepops#1236]
I would like to run 2 Slurm clusters in Deepops.
Each cluster is configured with one login node and 2 computing nodes. 
Cluster 1 is configured with login01, gpu01, gpu02.
Cluster 2 is configured with login02, gpu03, gpu04.
Each login node in each cluster has the role of controller node in Slurm.

And I'd like to connect to each cluster via one Open Ondemand and run jobs in each interactive application for each cluster.
(Ex. Connect to Open Ondemand and run job for Cluster 1 in jupyter interactive app and run other job for Cluster 2 in jupyter interactive app.)

I search the Deepops documentation and Open Ondeamd site but can't find how to do it.
Could you help me?

**Comment by dholt** [comment]
I think the easiest way to do this would be to create two inventory files, one for each cluster, and then run ansible with the `-i` flag to specify each inventory when you're creating the clusters. You can read more about inventory here: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

**Comment by meeshel78** [comment]
> I think the easiest way to do this would be to create two inventory files, one for each cluster, and then run ansible with the `-i` flag to specify each inventory when you're creating the clusters. You can read more about inventory here: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

Thanks a lot. I'll read and try it.
