### ISSUE TITLE
 msg: apt cache update failed

### ISSUE THREAD

**Issue by TranThanh96** [NVIDIA/deepops#1238]
![image](https://user-images.githubusercontent.com/26323599/200815967-bf75252f-83e0-4d87-8036-5e9dbbbf13a2.png)

Hi, I am getting an error as image below:
How can I fix this?

**Comment by dholt** [comment]
Hi, you can re-run ansible with `-vvv` for verbose output or try running `sudo apt cache update` manually on the failing node to see the errors

**Comment by TranThanh96** [comment]
@dholt 
sudo apt cache update

E: Invalid operation cache
