### ISSUE TITLE
./scripts/k8s/verify_gpu.sh fail

### ISSUE THREAD

**Issue by TranThanh96** [NVIDIA/deepops#1240]
version: tag/22.08
ubuntu: Ubuntu 20.04.5 LTS

```
Starting './scripts/k8s/verify_gpu.sh';  DeepOps version ''
job_name=cluster-gpu-tests
total_gpus=0
Creating/Deleting sandbox Namespace
updating test yml
downloading containers ...
job.batch/cluster-gpu-tests condition met
executing ...
No resources found in cluster-gpu-verify namespace.
GPU verification can't be executed, please check GPU node directly
```
check k9s:
![image](https://user-images.githubusercontent.com/26323599/201257456-3b281d83-a818-4cfb-8765-fba93fe42939.png)

How can I fix this.
someime k9s not error:
![image](https://user-images.githubusercontent.com/26323599/201257546-0a5f3a37-7f84-40d0-80a2-8e703434aa4b.png)

**Comment by TranThanh96** [comment]
nvidia-driver still work:
![image](https://user-images.githubusercontent.com/26323599/201257632-8cf1d7d7-7c73-458f-aef5-56f1a3e25617.png)

**Comment by supertetelman** [comment]
It looks like the cluster eventually came up in a health state. Are you still having problems with this? It look like the node labeler was having issues that eventually cleared up. It is hard to debug this issue without any logs from the failing POD or the output from describe nodes.
