### ISSUE TITLE
Uninstalling SLURM

### ISSUE THREAD

**Issue by mfruhner** [NVIDIA/deepops#1242]
Hello,
are there any instructions on how to remove the SLURM-Installation completely?
I installed the single-node version and we are running into a couple of problems in our team, so we would like to debug.

Thanks,
Maik

**Comment by dholt** [comment]
Unfortunately we don't have uninstall documentation. You should be able to go into the build directory (I think `/opt/deepops/slurm` by default) and run `make uninstall`

**Comment by jungyh0218** [comment]
The default build directory of Slurm is `/opt/deepops/build/slurm`. You can see there is a Makefile in the folder. Generally, a package installed via `make install` can be uninstalled by the command `make uninstall`. I think it would be helpful if there is a documentaion about the uninstallation of Slurm.

**Comment by adimukewar** [comment]
@mfruhner We are facing the same issue, were you able to uninstall slurm with the suggested method?

**Comment by adimukewar** [comment]
Thanks for the reply, I guess I'll go through the similar painful process as you did and uninstall everything manually. Just out of curiosity how long did it take? Did you find any other alternatives?
