### ISSUE TITLE
Bump Network Operator

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#1251]
We need to bump the network operator to the latest release and run through all the appropriate testing.

https://github.com/Mellanox/network-operator/releases

**Comment by dholt** [comment]
Following up on this older request as part of the resumed DeepOps release cadence: the Network Operator default has been bumped in the modern releases — 26.07 ships `nvidia_network_operator_version: "26.4.0"` installed from the NVIDIA NGC Helm repository (updated in #1357). Version refreshes are now part of every release train. If a newer version is needed for your deployment, the role accepts a version override, and new requests are welcome as fresh issues.
