### ISSUE TITLE
NVIDIA deepops is support GPU Time Slicing ?

### ISSUE THREAD

**Issue by jjsair0412** [NVIDIA/deepops#1254]
Deepops is support MIG mode but I'd not found GPU Time Slicing .

NVIDIA deepops is support GPU Time Slicing ?

If deepops is not support time slicing , Do you have any support plans?

Thank you for your help !

**Comment by supertetelman** [comment]
You can find the documentation around MIG support in Kubernetes here: https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/nvidia-mig.md

If you are using Slurm, MIG is also supported, but you need to configure your MIG devices using the mig-parted tool that is installed and managed by this playbook: https://github.com/NVIDIA/deepops/blob/master/playbooks/nvidia-software/nvidia-mig.yml

**Comment by jjsair0412** [comment]
hello , ! 

Thank you for your answer . !

Then deepops is not support nvidia GPU Time slicing ??

I found GPU Time slicing docs from nvidia offlical document. So i thought deepops also support Time-slicing founction.

**Comment by jungyh0218** [comment]
@jjsair0412 
DeepOps provides ansible modules to set up cluster and install SOTA programs. It's just an infrastructure automation tool. DeepOps does not provide any GPU sharing functionality by itself. If you are interested in GPU Time slicing, read [this article](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-sharing.html) please. Once you create your own k8s cluster, you can try GPU time slicing by configuring in the k8s cluster.

**Comment by jjsair0412** [comment]
Thank you for your answer @jungyh0218  !
