### ISSUE TITLE
the role 'kubespray-defaults' was not found

### ISSUE THREAD

**Issue by sagigithubcorner** [NVIDIA/deepops#1260]

**Comment by supertetelman** [comment]
Do you have any additional logs or output? This should work assuming you ran the `./scripts/setup.sh` script and are on a supported OS.

**Comment by dholt** [comment]
Following up on this older issue as part of the resumed DeepOps release cadence: the `kubespray-defaults role not found` error occurs when the Kubespray git submodule is not initialized. This is now covered in current master: `AGENTS.md` documents `git submodule update --init --recursive` as required first-time setup, and the new preflight tool (`python3 scripts/validation/deepops_doctor.py`, added in #1359 / release 26.07) explicitly checks for an initialized Kubespray submodule and tells you the fix. If you hit this on a current release after submodule init, please open a new issue.
