### ISSUE TITLE
Slurm build deps on Ubuntu missing libdbus-1-dev

### ISSUE THREAD

**Issue by jsharpe** [NVIDIA/deepops#1266]
In order for cgroup support to work correctly the libdbus-1-dev package needs to be installed when building slurm. This is missing from the list of build deps for ubuntu.

**Comment by morsoinferno** [comment]
Hi, I could reproduce the same problem installing on a fresh Ubuntu 22.04. Once I add the dependency, the slurm playbook runs smoothly.

**Comment by dholt** [comment]
Fixed in #1294
