### ISSUE TITLE
Deos Deepops support NVIDIA driver version 515 or 525?

### ISSUE THREAD

**Issue by Meeshel7** [NVIDIA/deepops#1274]
Hi,

I can find that Deepops support NVIDIA driver version  515 with Kubernetes.
But I cannot find which NVIDIA version is supported with Slurm.
Is it support NVIDIA driver version 515 or 525 if I use Slurm?
I plan to use it in A100 with NVIDIA DGX Server version 5.5.0.
And I check out the Deepops 22.08 tag.

**Comment by dholt** [comment]
Following up on this older question as part of the resumed DeepOps release cadence: yes — the NVIDIA driver role installs a selectable driver branch via `nvidia_driver_branch`, and modern branches are the default on current releases (26.07 defaults to branch `580`, with open-kernel-module selection via `nvidia_driver_ubuntu_use_open_kernel_modules` for the GPU generations that support it). Driver 515/525-era branches were selectable the same way. Driver defaults are refreshed as part of every release train now.
