### ISSUE TITLE
Error: alpine-glibc-shim was not installed 

### ISSUE THREAD

**Issue by paoloaq** [NVIDIA/deepops#1276]
> HW: DGX A100
> OS: DGX-OS6/Ubuntu 22.04 (fresh install)
> Issue: `andrewrothstein.alpine-glibc-shim was NOT installed successfully`

Hello everyone, 

We'd like to install Deepops on our DGX-A100 server to make accounting and workload management with Slurm. 
We just upgraded to DGX-OS6/Ubuntu 22.04.  Anyway it is a standard clean installation. 

We tried to follow the installation tutorial at https://developer.nvidia.com/blog/deploying-rich-cluster-api-on-dgx-for-multi-user-sharing.

As suggested in issue https://github.com/NVIDIA/deepops/issues/1201#issuecomment-1517975158 we renamed the dependency lib from `libmariadbclient-dev` to `libmariadbclient-dev-compat`.

We found problems just at the beginning of installation, when we run `setup.sh`. We had the following error:
```
Updating Ansible Galaxy roles...
[WARNING]: - andrewrothstein.alpine-glibc-shim was NOT installed successfully:
- sorry, andrewrothstein.alpine-glibc-shim was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list."
```

We noted that the ansible role is not anymore available on the https://galaxy.ansible.com/andrewrothstein - neither `alpine-glibc-shim` nor `alpine_glibc_shim`.

Could you suggest solutions to complete the installation, or updated guides we could folllow? 

Thanks

**Comment by dholt** [comment]
should be fixed in #1287
