### ISSUE TITLE
Building Slurm with Lua

### ISSUE THREAD

**Issue by rkevk** [NVIDIA/deepops#1277]
Slurm can be built with Lua support, which is a requirement for Lua plugins in Slurm: https://slurm.schedmd.com/quickstart_admin.html#build_install

However, I can't find an option to enable Lua support when building Slurm using DeepOps. Since doing so depends on having Lua installed when building Slurm, it seems that Lua would somehow have to be added to DeepOps beforehand?

**Comment by rkevk** [comment]
Ah, the simple solution is probably just to ensure that `liblua<version>` (at least that's the name on Ubuntu) is installed system-wide prior to configuring Slurm. That seems to solve the problem, I don't know if there's a DeepOps-internal way of doing it instead.

**Comment by clemsgrs** [comment]
hi, i'm re-opening this issue as i didn't manage to build slurm with lua.
here what i did:

1. updated `config/group_vars/all.yml ` to add installation of lua dev package

``` 
################################################################################
# SOFTWARE                                                                     #
################################################################################
# Extra software to install or remove
# Playbook: software
software_extra_packages:
  - liblua5.2-dev
```

2. updated `roles/slurm/defaults/main.yml` to add the `--with-lua` flag in `slurm_configure`:

```
slurm_configure:  './configure --prefix={{ slurm_install_prefix }} --disable-dependency-tracking --disable-debug --disable-x11 --enable-really-no-cray --enable-salloc-kill-cmd --with-hdf5=no --sysconfdir={{ slurm_config_dir }} --enable-pam --with-pam_dir={{ slurm_pam_lib_dir }} --with-shared-libslurm --without-rpath --with-pmix={{ pmix_install_prefix }} --with-hwloc={{ hwloc_install_prefix }} --with-lua'
```

3. update `slurm.conf` to add the following:

```
# SUBMISSION FILTERS
JobSubmitPlugins=lua
```

4. deploy the cluster through ansible:

```
ansible-playbook -l slurm-cluster playbooks/slurm-cluster.yml -k -K
```

Once the cluster deployed, i check `/var/log/slurm/slurmctld.log` where i can see the following error:

```
slurmctld version 23.02.2 started on cluster deepops
error: Couldn't find the specified plugin name for job_submit/lua looking at all files
error: cannot find job_submit plugin for job_submit/lua
error: cannot create job_submit context for job_submit/lua
fatal: failed to initialize job_submit plugin
```

If i check under `/usr/local/lib/slurm/`, there is no `job_submit_lua.so`!
I'm a bit lost as to what i should do now.
