### ISSUE TITLE
Is this proyect alive?

### ISSUE THREAD

**Issue by morsoinferno** [NVIDIA/deepops#1280]
Hi, somebody knows if is this project still alive or if there is an active fork anywhere?

**Comment by jungyh0218** [comment]
PRs were merged to the master branch 2 weeks ago, so it seems like the project is still alive and being updated continuously. I am also waiting for a new release version eagerly!

**Comment by morsoinferno** [comment]
Yes! Thanks for the answer. But as I see it, is active for the K8s deployment, not for the slurm playbooks u_u

**Comment by dholt** [comment]
yup
