### ISSUE TITLE
Update the Network Operator

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#1291]
We should update the Network Operator to use the latest release available on GitHub.

Update this:
https://github.com/NVIDIA/deepops/blob/master/roles/nvidia-network-operator/vars/main.yaml

To use this:

https://github.com/Mellanox/network-operator/releases/tag/v23.5.0

And then test it on a multinode system that is RDMA and RoCE compatible.

**Comment by dholt** [comment]
Following up on this older request as part of the resumed DeepOps release cadence: done — the Network Operator default is `26.4.0` as of release 26.07 (#1357), installed from the NVIDIA NGC Helm repository, and component versions are now audited against upstream sources every release train. Future bump requests are welcome as fresh issues, though the regular cadence should generally keep this current.
