### ISSUE TITLE
It's seem miss galaxy folder

### ISSUE THREAD

**Issue by v-ducnt69** [NVIDIA/deepops#1310]
roles/galaxy/
total 84
drwxrwxr-x 21 vinai vinai 4096 Aug 13  2021 ./
drwxrwxr-x 49 vinai vinai 4096 Jul 19  2021 ../
drwxrwxr-x  9 vinai vinai 4096 Jul 19  2021 DeepOps.chrony/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 DeepOps.hosts/
drwxrwxr-x  6 vinai vinai 4096 Jul 19  2021 DeepOps.users/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 andrewrothstein.bash/
drwxrwxr-x 10 vinai vinai 4096 Jul 19  2021 andrewrothstein.miniconda/
drwxrwxr-x  6 vinai vinai 4096 Jul 19  2021 andrewrothstein.unarchive-deps/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 ansible-maas/
drwxrwxr-x 10 vinai vinai 4096 Jul 19  2021 gantsign.golang/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 geerlingguy.elasticsearch/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 geerlingguy.filebeat/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 geerlingguy.java/
drwxrwxr-x  8 vinai vinai 4096 Jul 19  2021 geerlingguy.kibana/
drwxrwxr-x  9 vinai vinai 4096 Jul 19  2021 geerlingguy.logstash/
drwxrwxr-x  9 vinai vinai 4096 Jul 19  2021 geerlingguy.ntp/
drwxrwxr-x  7 vinai vinai 4096 Jul 19  2021 lecorguille.singularity/
drwxrwxr-x  6 vinai vinai 4096 Jul 19  2021 nvidia.enroot/
drwxrwxr-x  9 vinai vinai 4096 Jul 19  2021 nvidia.nvidia_docker/
drwxrwxr-x  9 vinai vinai 4096 Jul 19  2021 nvidia.nvidia_driver/
drwxrwxr-x 11 vinai vinai 4096 Jul 19  2021 ood-ansible/

**Comment by dholt** [comment]
Following up on this older issue as part of the resumed DeepOps release cadence: the Ansible Galaxy roles directory (`roles/galaxy`) is created by running `./scripts/setup.sh`, which installs all pinned Galaxy roles and collections from `roles/requirements.yml`. This is now also documented as required first-time setup in `AGENTS.md`, and the preflight tool added in release 26.07 (`python3 scripts/validation/deepops_doctor.py`) checks for it explicitly and prints the fix. If setup.sh fails to create it on a current release, please open a new issue with the error output.
