### ISSUE TITLE
Unable to install some galaxy collections using ./scripts/setup.sh

### ISSUE THREAD

**Issue by alldino** [NVIDIA/deepops#1312]
ansible-galaxy is failing to download collections with error:

`
Updating Ansible Galaxy roles...
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.general: '/api/v3/plugin/ansible/content/published/collections/index/
community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
`

**Comment by paoloaq** [comment]
Same issue

**Comment by dholt** [comment]
Following up on this older issue as part of the resumed DeepOps release cadence: Galaxy dependency installation has been reworked and re-pinned as part of the modern releases (26.05+), and it is exercised on every release train — both in public CI and in live GPU deployment QA. Current `./scripts/setup.sh` installs collections and roles from the pinned `roles/requirements.yml` cleanly on supported OSes. If a specific collection still fails to install on a current release, please open a new issue with the ansible-galaxy error.
