### ISSUE TITLE
deepops 24.08?

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/deepops#1313]
I want to deploy a new Slurm Cluster with NVIDIA GPU HW as a follow up to the deepops 21.09 Cluster I deployed in 2021/2022. I see that the last release was exactly one year ago and since then there was suspicious little activity in the repo. Will there be a new release? Is deepops alive?

Sorry to ask these blunt questions in the bug tracker, but I really liked deepops and relied on it being available when I would need it (which is now).
If deepops is discontinued please tell me what Slurm deployment/management method is recommended currently.

Thank you

**Comment by ccbt87** [comment]
I have the same question regarding the liveness of the DeepOps.

Looks like there's `NVIDIA Base Command Manager (BCM)` available from NVIDIA for Slurm cluster deployment. However, the BCM requires a license.

**Comment by sassyn** [comment]
Same here. 
I would like to deploy a new Kubeflow cluster using the deepops tools - but the version seems old.

Is there any fork to this?

**Comment by michael-balint** [comment]
Hey everyone, it's great to hear that there's interest in DeepOps. While DeepOps is still available as an open source project, our primary focus for NVIDIA GPU cluster management has shifted to Base Command Manager (BCM), following the acquisition of Bright Computing.

DeepOps served as a valuable tool for deploying GPU clusters using open source components. However, BCM now provides a more comprehensive, enterprise-grade solution for GPU cluster management, including Slurm & K8s integration. It builds on the learnings from DeepOps while providing additional enterprise features, state management, and ongoing support.

For those looking to deploy new Slurm or K8s clusters with NVIDIA GPUs, we recommend evaluating BCM as the preferred solution going forward. You can try BCM to see if it suits your needs by obtaining a [free evaluation license](https://customer.brightcomputing.com/Customer-Portal?p=easy8License) for up to 16 GPUs (max of 16 nodes) available for one year. Users who sign up can access this through the customer portal account (see section 4.3.9 in [installation manual](https://support.brightcomputing.com/manuals/10/installation-manual.pdf)).

The DeepOps repository remains available for those who wish to use or extend it. While we don't have concrete plans for new releases, the existing playbooks can still be used as a starting point. The community is also welcome to fork and maintain the project if there is interest.
