### ISSUE TITLE
Enable LDAP client authentication

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#147]
Nodes provisioned by DeepOps should be capable of authenticating to an organizational LDAP domain.

**Comment by mattlevan** [comment]
Seconded, this would be excellent.

**Comment by scaredmushroom** [comment]
This is still a wanted feature. @ajdecon @mattlevan did someone of you created their own solution?

**Comment by matthew-levan** [comment]
> This is still a wanted feature. @ajdecon @mattlevan did someone of you created their own solution?

No, sorry!

**Comment by arnoldas500** [comment]
@ajdecon did you ever get this working?

**Comment by ajdecon** [comment]
This is not something we decided to pursue, as it didn’t prove to be needed for our immediate use cases. We also found that most DeepOps users had existing mechanisms to include their clusters in central auth systems, and didn’t want to conflict with those.

However, if someone chose to open a PR to add this to DeepOps with good CI tests, it would probably be accepted :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
