### ISSUE TITLE
MPI Operator K8s Example

### ISSUE THREAD

**Issue by michael-balint** [NVIDIA/deepops#185]
Add an example to the `examples` directory that follows the [MPI Operator documentation](https://github.com/kubeflow/mpi-operator).

**Comment by supertetelman** [comment]
I'm working on a notebook that covers installing the MPI Operator and running a basic MPIJob through a Kubeflow pipeline.

**Comment by supertetelman** [comment]
Just merged a PR through with a single example. I still have a partial PR that includes a notebook with Kubeflow, but Kubeflow blocks it from working.

https://github.com/supertetelman/deepops/tree/kubeflow-mpi/workloads/examples/k8s/kubeflow-mpi
