### ISSUE TITLE
Integrate KONG (Kubernetes on NVIDIA GPUs)

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#2]
Update Kubespray deployment to use KONG (https://github.com/nvidia/kubernetes) instead of upstream Kubernetes

**Comment by jlefman** [comment]
Note to self: Be sure to test functionality on RHEL/Centos

**Comment by k82cn** [comment]
The link of KONG is broken, do you know the new link?

**Comment by ajdecon** [comment]
@k82cn : KONG is no longer supported if I understand correctly. We just use regular upstream Kubernetes at this point.

**Comment by k82cn** [comment]
> @k82cn : KONG is no longer supported if I understand correctly. We just use regular upstream Kubernetes at this point.

ok, got that; thanks :)
