### ISSUE TITLE
Nvidia OS Server 4.0.5 Compatibility

### ISSUE THREAD

**Issue by NoahDolev** [NVIDIA/deepops#202]
Hi, 

Are there any known compatibility issues using deepops with the latest Nvidia OS Server? I want to upgrade my DGX-2 to [4.0.5](https://docs.nvidia.com/dgx/pdf/DGX-OS-server-4.0.5-relnotes-update-guide.pdf) but before I proceed I want to make sure deepops has been tested in this environment?

Thank you.

Best,
Noah

**Comment by ajdecon** [comment]
@NoahDolev : AFAIK, there are no known compatibility issues between the latest DeepOps release [(19.03)](https://github.com/NVIDIA/deepops/tree/19.03) and DGX 4.0.5. I'm verifying if we've tested this explicitly on a DGX-2, but looking at the release notes there are no obvious problems.

**Comment by ajdecon** [comment]
I successfully added a DGX-2 with 4.0.5 to one of our DeepOps test instances and didn't run into any obvious issues, so I think this should be fine. I'm going to close this issue, but feel free to re-open if you run into problems or have any other questions!
