### ISSUE TITLE
Add information for provisioning non-DGX Tesla GPU nodes

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#21]

**Comment by upronix** [comment]
Are there any plans or time lines considered at this point? That would be very helpful because we've got systems with V100 and P100 from different vendors.

**Comment by mfoco** [comment]
Even DGX Station nodes (non-infiniband) need some special attention. Here's the list of packages I had to comment out of `ansible/roles/dgx-software/defaults/main.yml` to provision the nodes:
- dgx-oem-config-bmc
- ibacm-dev
- ibsim
- ibsim-doc
- ibutils
- ibverbs-utils
- infiniband-diags
- iser-dkms
- kernel-mft-dkms
- mft
- libibcm-dev
- libibmad-devel
- libibmad-static
- libibumad-devel
- libibumad-static
- libibverbs1-dbg
- libmlx4-1-dbg
- libmlx4-dev
- libmlx5-1-dbg
- libmlx5-dev
- librdmacm-dev
- librdmacm-utils
- knem
- knem-dkms
- mlnx-ethtool
- mlnx-fw-updater
- ofed-scripts
- srp-dkms
- srptools

**Comment by vtlrazin** [comment]
Hi,

How implemented fast interconnect between containers which deployed on separate Worker nodes? 
DGX-1 nodes equipped with **four Mellanox Connect-4 VPI  single port** adapters.
Are you using hostnework mode in workload deployments or another?

B.R.
Vitaliy

**Comment by dholt** [comment]
Fixed in 19.03
