### ISSUE TITLE
Slurm playbook is missing a required cpu package

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#215]
On an up-to-date DGX station Slurm was failing to run any batch jobs and continually transitioning into a draining state. This was on a single node system where the DGX Station was also a login node.

The error was from the cpu-setup script and can be seen below:

```
root@dgxstation:/shared# bash /etc/slurm/prolog-exclusive.d/50-cpu-setup
+ type cpupower
cpupower is /usr/bin/cpupower
+ cpupower frequency-info
+ grep -e 'governors: Not Available'
WARNING: cpupower not found for kernel 4.15.0-42

  You may need to install the following packages for this specific kernel:
    linux-tools-4.15.0-42-generic
    linux-cloud-tools-4.15.0-42-generic

  You may also want to install one of the following packages to keep up to date:
    linux-tools-generic
    linux-cloud-tools-generic
+ cpupower frequency-set -g performance
WARNING: cpupower not found for kernel 4.15.0-42

  You may need to install the following packages for this specific kernel:
    linux-tools-4.15.0-42-generic
    linux-cloud-tools-4.15.0-42-generic

  You may also want to install one of the following packages to keep up to date:
    linux-tools-generic
    linux-cloud-tools-generic
```

The missing package that resolves the issue:
`apt-get install -y linux-tools-$(uname -r)`

This potentially looks like a dupe of https://github.com/NVIDIA/deepops/issues/158 which has been closed/resolved.

Running off of master @ 6f7353d3ec045f92d052240c97ecc7f09f2c4d22.

Installed slurm via ` ansible-playbook -i config/inventory playbooks/slurm-cluster.yml`

**Comment by dholt** [comment]
It gets installed here [1]

Did you maybe get an updated kernel or something? I think a reboot/update would probably clear it up.

[1] https://github.com/NVIDIA/deepops/blob/master/roles/slurm/tasks/prolog_epilog.yml#L6

**Comment by supertetelman** [comment]
Addressed the issue here:
https://github.com/NVIDIA/deepops/pull/216

Chime in if you think this isn't the best way to fix this or if anything should be modified for RHEL.

**Comment by supertetelman** [comment]
A reboot wasn't necessary when I used the patch above.

Do you think a reboot would have worked with the generic version (instead of kernel specific)?

**Comment by supertetelman** [comment]
Okay, after uninstalling the kernel specific version, re-installing the generic version via the playbook and then `rebooting` my machine the sbatch jobs are running. Seems like rebooting was the missing step here and the packages are fine.
