### ISSUE TITLE
Vagrant and Virsh issues if virt* installed by vagrant_setup

### ISSUE THREAD

**Issue by ScottESanDiego** [NVIDIA/deepops#217]
If virt packages are installed as part of vagrant_startup.sh, then the calling shell isn't aware of the membership in the `libvirt` group.  This means that the steps in https://github.com/NVIDIA/deepops/blob/master/virtual/README.md  after `./vagrant_startup.sh` won't work, and indeed the `virsh list` at the end of that script doesn't work either. (See attached log)

[vagrant_startup_sh_NoVirtManager.log](https://github.com/NVIDIA/deepops/files/3060316/vagrant_startup_sh_NoVirtManager.log)

The script should probably check the group membership and inform the user they need to logout/login before proceeding, and potentially the README should be updated as well with a note that the user may need to logout/login to pick up the `libvirt` membership before attempting the other `vagrant ssh` calls, etc.

**Comment by supertetelman** [comment]
We recently made a bunch of updates and upgrades to the virsh/vagrant installation. I haven' seen this behavior again, so I'm closin this issue as stale.
