### ISSUE TITLE
kubectl create secrete docker registry fails to accept documented arguments

### ISSUE THREAD

**Issue by pmcgraw-lucidyne** [NVIDIA/deepops#226]
Hello,

I recently pulled 19.03 and setup a temporary k8s cluster to test the setup process. I tried following the usage documentation here https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-usage.md. I reached the point where I was ready to register the NGC docker repository so I could more easily deploy nvidia containers to the cluster, but I reached step 2 of the documentation for this task and the cli seems to be fighting me. The command I am running minus my email and docker password:

`kubectl create secret docker-registry nvcr.dgxkey –-docker-server=nvcr.io.com --docker-username=\$oauthtoken --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL` 

The cli prints the following error:

`error: exactly one NAME is required, got 2
See 'kubectl create secret docker-registry -h' for help and examples.`

Yes I checked the help documentation, which looking at the usage section:
`Usage:
  kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] [options]`

I see that the --docker-server parameter is optional. This lead me to omit this parameter, and instead use the input to the --docker-server parameter as the NAME parameter, and it works. This was just a little annoying so I figured I would make an issue explaining it.

**Comment by dholt** [comment]
Thanks for the report; the docs definitely look wrong and I see they have an incorrect `-` character as well.

**Comment by pmcgraw-lucidyne** [comment]
Np. Quick note about another typo: The kubectl command for creating the
secret dropped the first '-' in the cli option for the docker server name
in the git docs, but not the kubectl help ( to be clear).

**Comment by mwalden2004** [comment]
Has this not been fixed yet? I'm having a problem with the command with a NAME error.

**Comment by supertetelman** [comment]
I was able to get this working copy/pasting from the README. This is the command I used (and I first set the username/passord variables).

`kubectl create secret docker-registry nvcr.io -n anonymous --docker-server=nvcr.io --docker-username=\$oauthtoken --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL`

And don't forget to include the key in your Pod spec:

```
    spec:
      imagePullSecrets:
      - name: nvcr.io
```
