### ISSUE TITLE
PROXY - DeepOps scripts

### ISSUE THREAD

**Issue by prakashmstpt** [NVIDIA/deepops#248]
I have setup password less ssh to all the boxes i am planning install deep ops with proxy environment variable in basrc. 
Question : 
1. Do we need to set up any internal repo for if you what.
2. How can we force docker/helm/elk/ceph storage to a default directory ? 
3. is there a good way to clean up if the Ansible scripts fail.

**Comment by ajdecon** [comment]
Regarding HTTP proxy config:

If you're setting up k8s with Kubespray, you can set the proxy for Docker and Helm using Ansible variables `http_proxy` and `https_proxy`: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/proxy.md

If not using Kubespray, or for other scripts, DeepOps currently doesn't support setting an HTTP proxy. (This would be a good addition!) However, it shouldn't interfere with any such config either, so if you use a custom playbook to insert this config, it should probably work fine.

Answering your numbered questions:

1. An internal repo shouldn't be necessary.
1. Regarding storage locations:
    1. Docker (and containers which use Docker volumes) stores volume data by default in `/var/lib/docker/volumes`. You can change the root path (`/var/lib/docker`) using the `--data-root` flag on `dockerd`. If you want to change just the volume location, your best bet is probably to symlink `/var/lib/docker/volumes`.
    1. For Ceph storage: DeepOps uses Rook to build a Ceph cluster using [this deployment script](/scripts/k8s_deploy_rook.sh) and [this service definition](/services/rook-cluster.yml). Your best bet to make changes to how Ceph stores data is probably to look at the [Rook documentation](https://rook.io/docs/rook/v0.9/ceph-storage.html), probably in the [OSD config](https://rook.io/docs/rook/v0.9/advanced-configuration.html#osd-information).
1. Not really. Ansible modules are generally idempotent, so if you can fix the issue and re-run the scripts, you should end up in your intended state. But if an Ansible playbook fails partway through, there's no good way to roll back to the previous state. My usual procedure, when I have a good automated provisioning system, is to just tear down and rebuild the box.

Let me know if this helps, or if you have additional questions.

**Comment by prakashmstpt** [comment]
Thanks Adam for the info. I will go over additional documentation.
