### ISSUE TITLE
failing not finding  cluster.yml

### ISSUE THREAD

**Issue by prakashmstpt** [NVIDIA/deepops#251]
ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml
ERROR! Unable to retrieve file contents
Could not find or access '/data01/deepops-master/kubespray/cluster.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

1. Do we need to download kubespray separately ? My kubespray folder is empty.
2. Will the existing script rebuild the cluster.yaml from inventory or do we need to explicitly modify in kubespray

**Comment by ajdecon** [comment]
We include Kubespray as a submodule in the DeepOps repo. You should be able to make sure Kubespray is cloned, as well as making sure all DeepOps dependencies are installed, by running `scripts/setup.sh` as stated in the docs.

Please let us know if that script doesn't work for you, or if something else is going on.

**Comment by prakashmstpt** [comment]
May be I did not explain properly
when we "git clone https://github.com/NVIDIA/deepops" it  is not pulling "kubespary. So i can pull it separate and keep it under kubespray directory.

I am following instruction from - https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md

I finished setup step manually - setup script has bug reported in #247 - Setup step is just setting up Ansible,Git and requirements. it is copying config Dir which need inventory change which i did.

ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml - is failing - my question there is nothing in script that will make changes from inventory to cluster.yml

Code block: k8s-cluster.yml
=====
# Install Kubernetes
- include: ../kubespray/cluster.yml
  vars:
    ansible_become: true
    kubeadm_enabled: true
    kube_api_anonymous_auth: true
    kubectl_localhost: true
    kubeconfig_localhost: true
    helm_enabled: true
    tiller_node_selectors: "node-role.kubernetes.io/master=''"
    docker_dns_servers_strict: no
    docker_storage_options: -s overlay2

# Disable swap (required for k8s), kubespray method doesn't quite cut it
=====

**Comment by ajdecon** [comment]
I apologize, I missed the other issue!

One of the other steps in `setup.sh` is to run:

```
git submodule update --init
```

That step should clone kubespray into the correct location as a submodule. The `cluster.yml` in kubespray is a playbook and shouldn't need any additional updates once the submodule has been cloned.

**Comment by prakashmstpt** [comment]
Thanks that worked Adam. But stuck with different issue which I will open as separate issue.

**Comment by ajdecon** [comment]
@prakashmstpt : Glad to hear it. Closing this issue, but feel free to re-open when it makes sense. I'll watch for the new issue as well.
