### ISSUE TITLE
Docker packages install - TCP connection reset by peer

### ISSUE THREAD

**Issue by prakashmstpt** [NVIDIA/deepops#252]
**Error:**
TASK [container-engine/docker : ensure docker packages are installed] ****************************************************
FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
failed: [mgmt] (item={u'yum_conf': u'/etc/yum_docker.conf', u'name': u'docker-ce-18.06.2.ce-3.el7'}) => {"attempts": 4, "cd": false, "item": {"name": "docker-ce-18.06.2.ce-3.el7", "yum_conf": "/etc/yum_docker.conf"}, "msg": "Failure talking to failure: repodata/repomd.xml from docker-engine: [Errno 256] No more mirrors to try.\nhttps://yum.dockerproject.org/repo/mentos/7/repodata/repomd.xml: [Errno 14] curl#35 - \"TCP connection reset by peer\""}
...ignoring

TASK [container-engine/docker : get available packages on Ubuntu] ********************************************************
skipping: [mgmt]

TASK [container-engine/docker : show available packages on ubuntu] *******************************************************
skipping: [mgmt]

TASK [container-engine/docker : Set docker pin priority to apt_preferences on Debian family] *****************************
skipping: [mgmt]

TASK [container-engine/docker : ensure service is started if docker packages are already present] ************************
fatal: [mgmt]: FAILED! => {"changed": false, "msg": "Could not find the requested service docker: host"}

NO MORE HOSTS LEFT *******************************************************************************************************
        to retry, use: --limit @/data01/deepops/playbooks/k8s-cluster.retry

---PLAY RECAP --------------------------------------------------------------------------------------------
mgmt                       : ok=106  changed=18   unreachable=0    failed=1
----------------------------------------------------------------------------------------------------------
_This is clearly a proxy issue you can see below that environment variables have proxy settings.
Still the install fails. I used correct such a problem in a manual install by creating /etc/systemd/system/docker.service.d/http-proxy.conf and recycling the docker.service as indicated in docker documentation (https://docs.docker.com/config/daemon/systemd/)
But i am not sure how to proceed with playbooks.
1. Even if I create this file the playbook may not recycle the service when installing
2.  Are this playbooks self healing. What I mean can I rerun the scripts with out any clean up. if I have to try some options._
-------------------------------------------------------------------------------------------------------
environment variables for reference.
XDG_SESSION_ID=18916
HOSTNAME=nnn.corpnet2.com
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.138.48.27 59826 22
UMASK=027
QTDIR=/usr/lib64/qt-3.3
OLDPWD=/root/.ssh
QTINC=/usr/lib64/qt-3.3/include
SSH_TTY=/dev/pts/0
QT_GRAPHICSSYSTEM_CHECKED=1
http_proxy=http://xxx:yyy@zzz.corpnet2.com:800
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
FTP_PROXY=http://xxx:yyy@zzz.corpnet2.com:800
ftp_proxy=http://xxx:yyy@zzz.corpnet2.com:800
ALL_PROXY=socks://xxx:yyy@zzz.corpnet2.com:800
all_proxy=socks://xxx:yyy@zzz.corpnet2.com:800
MAIL=/var/spool/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin
PWD=/data01/deepops
JAVA_HOME=/usr/java/latest
LANG=en_US.UTF-8
KDEDIRS=/usr
HTTPS_PROXY=http://xxx:yyy@zzz.corpnet2.com:800
https_proxy=http://xxx:yyy@zzz.corpnet2.com:800
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
HTTP_PROXY=http://xxx:yyy@zzz.corpnet2.com:800
LOGNAME=root
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=10.138.48.27 59826 10.138.42.101 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
_=/bin/env

**Comment by ajdecon** [comment]
The Kubespray Ansible playbooks include a optional variables for setting an HTTP(S) proxy: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/proxy.md

You should be able to override these variables in your Ansible run to set the proxy, and the container playbook appears to handle restarting the service correctly: https://github.com/kubernetes-sigs/kubespray/blob/424e59805f4e871cfe11b5a1a05eb43c37aaf1c6/roles/container-engine/docker/tasks/systemd.yml#L7

I have not tested this directly, but you should be able to set these variables in `config/group_vars/all.yml` and have them picked up in Kubespray if you're using DeepOps master.
