### ISSUE TITLE
RHEL - failing with docker dependencies container-selinux >= 2.9

### ISSUE THREAD

**Issue by prakashmstpt** [NVIDIA/deepops#254]
When installing on RHEL 7.4 failing on container-engine/docker. To my understanding this is fixed in kubespray. Not sure why i am getting this error.

TASK [container-engine/docker : ensure docker packages are installed] ***********************************************
FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
failed: [gpu02] (item={u'yum_conf': u'/etc/yum_docker.conf', u'name': u'docker-ce-18.06.2.ce-3.el7'}) => {"attempts": 4, "changed": false, "item": {"name": "docker-ce-18.06.2.ce-3.el7", "yum_conf": "/etc/yum_docker.conf"}, "msg": "Error: Package: docker-ce-18.06.2.ce-3.el7.x86_64 (docker-ce)\n           Requires: container-selinux >= 2.9\n", "rc": 1, "results": ["Loaded plugins: enabled_repos_upload, langpacks, package_upload, product-id,\n              : search-disabled-repos, subscription-manager\nResolving Dependencies\n--> Running transaction check\n---> Package docker-ce.x86_64 0:18.06.2.ce-3.el7 will be installed\n--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-18.06.2.ce-3.el7.x86_64\n--> Processing Dependency: libseccomp >= 2.3 for package: docker-ce-18.06.2.ce-3.el7.x86_64\n--> Processing Dependency: libseccomp.so.2()(64bit) for package: docker-ce-18.06.2.ce-3.el7.x86_64\n--> Running transaction check\n---> Package docker-ce.x86_64 0:18.06.2.ce-3.el7 will be installed\n--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-18.06.2.ce-3.el7.x86_64\n---> Package libseccomp.x86_64 0:2.3.1-3.el7 will be installed\n--> Finished **Dependency Resolution\nError: Package: docker-ce-18.06.2.ce-3.el7.x86_64 (docker-ce)\n           Requires: container-selinux >= 2.9\n************************************************************************\nyum can be configured to try to resolve such errors by temporarily enabling\ndisabled repos and searching for missing dependencies.\nTo enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf\n**********************************************************************\n\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\nUploading Enabled Repositories Report\nLoaded plugins: langpacks, product-id, subscription-manager\n"]}

**Comment by supertetelman** [comment]
We've resolved most of these older Docker issues. Closing this issue.
