### ISSUE TITLE
Cache builder inventory entry causes playbooks using `all` to run on localhost

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#265]
https://github.com/NVIDIA/deepops/blob/6819034327098fd350f79c7861f21827cd81d1f7/config.example/inventory#L70

Having `localhost` in the inventory causes any playbook using `hosts: all` to run on the local host. We should probably remove this entry from the inventory and delegate tasks to localhost instead.

**Comment by ajdecon** [comment]
Ack. I'll take a look at this later today.
