### ISSUE TITLE
Improvements to scripts/k8s_deploy_binderhub.sh

### ISSUE THREAD

**Issue by michael-balint** [NVIDIA/deepops#266]
ATTN: @supertetelman 

The `k8s_deploy_binderhub.sh` script should be modified with the following improvements...

* Instead of a `while` loop during stand up, use a `wait for` conditional with `kubectl`. This will make it less confusing to the user when running the script. As it is right now, the stand up text repeats itself and it seems like things are failing with retries.

* Detect whether we are using a `LoadBalancer` or a `NodePort` setup for the service. An example of how to do this is in the `k8s_deploy_kubeflow.sh` script.

**Comment by supertetelman** [comment]
Deprecated feature, closing this issue.
