### ISSUE TITLE
tiller init --upgrade is failing in airgapped cluster bootstrapping

### ISSUE THREAD

**Issue by hightoxicity** [NVIDIA/deepops#27]
Command is failing, not using proxy env to fetch outside.
Maybe you should upgrade kubespray pinned commit hash since it is fixed upstream :

https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubernetes-apps/helm/tasks/main.yml#L79

Thx.

**Comment by ryanolson** [comment]
Thanks for the report.  I think @dholt just tested upstream last night.  Stay tuned.

**Comment by hightoxicity** [comment]
Nice, great news :-) Thx

**Comment by dholt** [comment]
Kubespray has been updated to v2.7.0 in the dev branch (https://github.com/NVIDIA/deepops/tree/dev).

Be sure to read the first part of the README as you'll need to install the Ansible hashivault module via pip.

Also updated Kubernetes to v1.11.3, Etcd to v3.3.10, Helm to v2.11.0, and Docker to 18.06.1

The next Kubespray version looks like it will have official support for Kubernetes v1.12 and Docker 18.06

**Comment by hightoxicity** [comment]
Nice job thx!
