### ISSUE TITLE
Any plan to add NFS for storage support  

### ISSUE THREAD

**Issue by kumareshan11** [NVIDIA/deepops#272]
Hello Team, 

Just want to know, do we have any plan to add NFS for persistent storage for k8's cluster. 

We are trying to do implementation with NFS instead of chepfs. just curious is you guys have any specific reason for choosing chepfs ?

**Comment by michael-balint** [comment]
NFS is supported as well. Rook + Ceph is a bit easier to use with Kubernetes as block storage. With NFS, you will have to manage PersistentVolumes (PVs) and PersistentVolumeClaims (PVCs) yourself. With Rook + Ceph, there is a dynamic provisioner which will handle this.

To use NFS, change your inventory file to add an `nfs-server` and connecting `nfs-clients`...

```
[nfs-server]
login01

[nfs-clients]
gpu01
gpu02
```

Then, deploy the `playbooks/nfs.yml` playbook via Ansible.
