### ISSUE TITLE
syntax error in running playbooks/k8s-cluster.yml

### ISSUE THREAD

**Issue by yusuke0324** [NVIDIA/deepops#276]
I'm running into an issue that says `deepops/kubespray/roles/kubernetes-apps/cluster_roles/tasks/main.yml': line 42, column 3, but may
be elsewhere in the file depending on the exact syntax problem.`
after executing `$.cluster_up.sh` on virtual machine.
```
$ ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

Does anyone have an idea why I'm getting this error?
I'm working with `19.03` tag

**Comment by dholt** [comment]
You'll need to downgrade to the latest ansible 2.7 for now
