### ISSUE TITLE
Timeout (62s) waiting for privilege escalation prompt

### ISSUE THREAD

**Issue by Nozomeister** [NVIDIA/deepops#282]
Dear DeepOps team,
I want to raise an issue that I encountered recently when trying to set up DGX-pod configuration on our cluster.
When I tried to deploy kubernetes on management nodes, it seems that I cannot connect to the gpu cluster with the error:
fatal: [gpu01]: FAILED! => {"msg": "Timeout (62s) waiting for privilege escalation prompt: "}

I only tried with 1 gpu cluster, and provision node acting as management node.
I have attached my ansible inventory configuration. The ansible_host IP is corresponding LAN IP addr of the 2 nodes.
Can you help me with this?
Best regards,
[configuration.zip](https://github.com/NVIDIA/deepops/files/3239377/configuration.zip)
Edited: after reconfiguring my LAN, i got this error:
fatal: [gpu01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '10.80.42.253' (ECDSA) to the list of known hosts.\r\nubuntu@10.80.42.253: Permission denied (publickey,password).", "unreachable": true}

I have run ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml -K and key in my gpu server sudo password, but it still said that permission denied.

**Comment by dholt** [comment]
Do you have SSH key auth enabled on the `gpu01` server? If not, you'll need to also add the `-k` flag which will prompt for the user password. The playbook will create an SSH keypair for you and copy it to the remote machine, so subsequent runs won't need either `-k` or `-K` flags

**Comment by Nozomeister** [comment]
> Do you have SSH key auth enabled on the `gpu01` server? If not, you'll need to also add the `-k` flag which will prompt for the user password. The playbook will create an SSH keypair for you and copy it to the remote machine, so subsequent runs won't need either `-k` or `-K` flags

Hi @dholt ,
I have already solved the problem and manage to deploy on the mgmt01 nodes. but when I tried to run the kubectl apply -f services/apt.yml command to deploy the internal apt package, the server was not responding and when I tried to debug it, it appeared that the pod was still pending. 
I have attached the output of kubectl get nodes and kubectl get pods:

> NAME     STATUS   ROLES    AGE   VERSION
mgmt01   Ready    master   41h   v1.12.5
>NAME                         READY   STATUS    RESTARTS   AGE
apt-server-bbf658cd7-rsxfx   0/1     Pending   0          41h
Did this problem happen because I only deployed on the management node?
Thank you.
