### ISSUE TITLE
k8s-cluster.yml needs to be able to support configuring Docker's daemon.json via config/group_vars/all.yml

### ISSUE THREAD

**Issue by fidot1983** [NVIDIA/deepops#288]
At the moment, if one sets up a structure similar to this:

```
docker_daemon_json: 
  docker_opt: opt_val
```
then /etc/docker/daemon.json does not even appear. 

Expected behavior: to be able to specify options for `daemon.json` in the group_vars.

**Comment by supertetelman** [comment]
This is outdated. We've removed this and are not relying on Kubespray to control Docker options.
