### ISSUE TITLE
docker.yml playbook does not respect docker_daemon_json option in group_vars/all.yml

### ISSUE THREAD

**Issue by fidot1983** [NVIDIA/deepops#289]
Setting up `docker_daemon_json` section in `group_vars/all.yml` does not seem to have any effect on `docker_daemon_json` applied during execution of `playbooks/docker.yml` playbook. 

What's interesting is that modifying the `docker_daemon_json` variable _inside_ the playbook works just fine. However, from what I understand the expectation is not to have users have to change provided code; but rather stay within the `config` directory :)

**Comment by dholt** [comment]
Should be fixed in https://github.com/NVIDIA/deepops/pull/350
