### ISSUE TITLE
Questions: ipxe boot from enp1s0f1 (second interface) / air gapped cluster ubuntu

### ISSUE THREAD

**Issue by hightoxicity** [NVIDIA/deepops#29]
Doc is made to retrieve mac adress of the first interface with ipmitool... It's not a blocker for me since I have already an os running on my DGX nodes and I can get mac address of my enp1s0f1 (second interface) but it would be great to have a command to get any other interface IP if possible with ipmi, the only one interface up/plugged in our environment  (I did not find it in dgx user guide, maybe I missed it). I tested manualy the dhcp running on my master (launched using helm ipxie chart) with the current running os of my dgx and using dhclient and I can get my static lease. But ipxe install is currently failing. Are the ipmi commands suitable to install the OS from second network interface?

Other question: I used the netboot ubuntu installer (indicated in the doc for dgx nodes) but I have no route to go to internet (aim is to only use proxies to go outside), is it something which will block me for proper os installation with the ubuntu-installer?

I hopped I could test it using ipxe boot from vagrant but it seems like you are using a dgx box, is it something planned for you to be implemented  (virtual env ipxe boot for DGX)?

Great thanks for your help.

**Comment by hightoxicity** [comment]
I found my answer for second interface in the doc :-)

> # interface 2
> ipmitool -I lanplus -U <username> -P <password> -H <DGX BMC IP> raw 0x30 0x19 0x00 0x12 | tail -c 18 | tr ' ' ':'

**Comment by hightoxicity** [comment]
#30

**Comment by dholt** [comment]
Think we got all of this resolved? Feel free to re-open

**Comment by hightoxicity** [comment]
I added #31 PR
When there is no interface to hit a "got to" public gateway; there is no need to put NAT rules (having the dgxie running on mgmt node).
In previous case, specified gateway in conf should be the one used as dhcp router config.

Maybe I forgot something...
