### ISSUE TITLE
"default-shm-size": "1G" conflicts with DGX BaseOS setting

### ISSUE THREAD

**Issue by bulldude** [NVIDIA/deepops#305]
On the DGX BaseOS (tested on 4.1.0) default-shm-size": "1G" set in /etc/systemd/system/docker.service.d/docker-override.conf conflicts with the DeepOps value set in /etc/docker/daemon.json.  

The conflict stops the node from participating in GPU jobs (CPU/MEM still work).   Removing from either and restarting kubelet and docker.service resolves the issue.

Without the change you can run a docker GPU job locally on the DGX, but cannot launch any jobs with kubectl.

**Comment by dholt** [comment]
Should be fixed in https://github.com/NVIDIA/deepops/pull/351
