### ISSUE TITLE
Unable to run slurm playbook with single targeted host

### ISSUE THREAD

**Issue by kumareshan11** [NVIDIA/deepops#307]
Hi Team,

When we are trying to run  playbooks/slurm.yml with targeting single host, we are encountering the below issue :
https://github.com/ansible/ansible/issues/58925

To reproduce issue : 
$ ansible-playbook -l "dgx-node" playbooks/slurm.yml

Error :
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_local'"

if we run as below, we don't see any issues:
$ ansible-playbook playbooks/slurm.yml
But seems running slurm playbook over cluster all the time, seem not good.

**Comment by dholt** [comment]
You need at least two nodes to run Slurm, a management/login node and a compute/worker node. It doesn't make sense to try and run the scheduler on a single node since it can't control that node's resources.

If you're unable to install on multiple nodes, can you share your configuration and inventory file?

**Comment by supertetelman** [comment]
I saw the same problem with this config:

```
[all]
mgmt1 ansible_host=192.168.1.100
gpu0 ansible_host=192.168.1.101
[slurm-master]
mgmt1
[slurm-node]
mgmt1
gpu0
```

**Comment by dholt** [comment]
We’re going to need more info about your setup, I can’t reproduce this

**Comment by kumareshan11** [comment]
When we run "ansible-playbook playbooks/slurm.yml -vvv" we encountering this issue, It shows there is no attribute "ansible_local" not able to fetch ansible local facts 
https://github.com/NVIDIA/deepops/tree/master/roles/facts/files

But when i add debug parameter on playbook, i am able see the local facts as output. 
Due to this issue, we had to set static values on slurm.conf 
https://github.com/NVIDIA/deepops/blob/e26fbdde127b4e25e6fbe0cdcaad3480c34779ff/roles/slurm/templates/slurm.conf#L108
```
dgx-node1 failed: {
    "changed": true,
    "msg": "All items completed",
    "results": [
        {
            "ansible_loop_var": "item",
            "changed": false,
            "failed": true,
            "item": "slurm.conf",
            "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_local'"
        },
        {
            "ansible_loop_var": "item",
            "changed": true,
            "checksum": "c874732adaa2e5931730c54327018c8058b1794a",
            "dest": "/etc/slurm/topology.conf",
            "diff": [],
            "failed": false,
            "gid": 0,
            "group": "root",
            "invocation": {
                "module_args": {
                    "_original_basename": "topology.conf",
                    "attributes": null,
                    "backup": false,
                    "checksum": "c874732adaa2e5931730c54327018c8058b1794a",
                    "content": null,
                    "delimiter": null,
                    "dest": "/etc/slurm/topology.conf",
                    "directory_mode": null,
                    "follow": false,
                    "force": true,
                    "group": null,
                    "local_follow": null,
                    "mode": null,
                    "owner": null,
                    "regexp": null,
                    "remote_src": null,
                    "selevel": null,
                    "serole": null,
                    "setype": null,
                    "seuser": null,
                    "src": "/local/home/draco/.ansible/tmp/ansible-tmp-1565019673.440287-235821350407306/source",
                    "unsafe_writes": null,
                    "validate": null
                }
            },
            "item": "topology.conf",
            "md5sum": "a139a5c19fc107e364db731b597c7530",
            "mode": "0644",
            "owner": "root",
            "size": 802,
            "src": "/local/home/draco/.ansible/tmp/ansible-tmp-1565019673.440287-235821350407306/source",
            "state": "file",
            "uid": 0
        }
    ]
}
```

**Comment by dholt** [comment]
Are you running Ansible from the same host you're trying to provision? If so, can you try running from another machine?

**Comment by santos-lucas** [comment]
Hello @kumareshan11, how did you fixed this? I am having the exact same issue, I am trying to add an node to my existing slurm clsuter
