### ISSUE TITLE
Failed at  "TASK [slurm : create users]"

### ISSUE THREAD

**Issue by jxdn** [NVIDIA/deepops#312]
Hi Team,

I face this issue when i run :
ansible-playbook -l slurm-cluster playbooks/slurm-cluster.yml 

TASK [slurm : create users] ****************************************************
fatal: [login01]: FAILED! => 
  msg: '''dict object'' has no attribute ''SUDO_USER'''

Any idea why this issue happen?

**Comment by supertetelman** [comment]
I'll take a look at this.

For now you can get past this by adding the '-u ubuntu' flag to the ansible command.
