### ISSUE TITLE
Set default nodePort values for additional built in services.

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#318]
We currently pre-configure nodePorts for ELK and monitoring.

Should we do the same for the Ceph dashboard, Dask example, Kubeflow, etc.?

This would be easy to change/modify if it get's in the way of existing infrastructure and it would have the added benefit of creating more seamless documentation and demos.

**Comment by ajdecon** [comment]
This seems like a good idea to me, though we should also make sure to document the defaults and make it clear where to change them.

**Comment by supertetelman** [comment]
Updated for kubeflow.

**Comment by supertetelman** [comment]
Kubeflow is all set and the Dask deployment has been removed. We are also moving away from Ceph. I'm closing this issue for now until new services are added that require this.
