### ISSUE TITLE
PXE boot phase (pixiecore) finishing on OK on imgfetch --name ready http://mgmtip:81/_/booting?mac=00%3A00%3A00%3A00%3A00%3A00

### ISSUE THREAD

**Issue by hightoxicity** [NVIDIA/deepops#32]
pixiecore is currently serving:

> #!ipxe
> kernel --name kernel http://mgmtip:81/_/file?name=ka431WTrnWITmnBXhXVgvDdXkyFj-0U_QQdisp483ClJhLdqjHhnenoUL9458ylvN84McvgRB6ioIX1nTY4YG8jjkPqonGTVa1x3e8y8lC5N05qs9QjKHsfjb3a86_SYu5wBw5WyCkjqPx4xngqa&type=kernel&mac=00%3A00%3A00%3A00%3A00%3A00
> initrd --name initrd0 http://mgmtip:81/_/file?name=zFaDKSwrlxyZH3XOY-BTRr8f5JieKkTikgPPGR4c51dULsy8ZmKTERR3AUbFZ720nj66VM51vYZSvESFf1w7GEl2VFOOSnTMI46VnyNPF0FEoBGF7U0vs7ApxkxKBvq-wWvhLwDfLq9P4LlnFHVwl2xS4g%3D%3D&type=initrd&mac=00%3A00%3A00%3A00%3A00%3A00
> imgfetch --name ready http://mgmtip:81/_/booting?mac=00%3A00%3A00%3A00%3A00%3A00 ||
> imgfree ready ||
> boot kernel initrd=initrd0 quiet url=http://mgmtip:81/_/file?name=i6d4oz7hmc9ICZzU9Lfm-5Hg8ZQf7OifqKKf-X44heR8uVLG0jv7Jkgd_U9aGU-DcvdVqYuwEHZKTIVM11pCaLRmnPwjAoA%3D ramdisk_size=100000 locale=fr_FR.UTF-8 auto=true priority=critical kbd-chooser/method=fr netcfg/choose_interface=enp1s0f1 netcfg/get_hostname=my-hostname netcfg/dhcp_timeout=120

when my DGX fetches: http://mgmtip:81/_/ipxe?arch=1&mac=00%3A00%3A00%3A00%3A00%3A00

And following logic here: https://github.com/google/netboot/blob/cc33920b4f3296801a64d731d269978116f40d92/pixiecore/http.go#L202

But DGX is printing at client side:
...

> http://mgmtip:81/_/booting?mac=00%3A00%3A00%3A00%3A00%3A00... OK

This call in http is giving a http response code of 200 with a # Booting body

Then nothing is happening on this server, it is currently stuck on:

> http://mgmtip:81/_/booting?mac=00%3A00%3A00%3A00%3A00%3A00... OK

Do you know what could explain this weird behavior?

 Thanks

**Comment by hightoxicity** [comment]
I will try to remove quiet on boot command, if nothing happen I will re-open the ticket.
Sorry for this.

**Comment by hightoxicity** [comment]
It seems that :
boot kernel initrd=initrd0 .... is never called. I tried to debug dgxie but there is no fetch of the preseed file.

**Comment by hightoxicity** [comment]
I hacked pixiecore to get a pxe shell, from here I launched the boot command manualy, it is getting stuck on this.

**Comment by hightoxicity** [comment]
![pxe](https://user-images.githubusercontent.com/11333624/49020149-0538e700-f190-11e8-9926-2e63db06c513.png)

**Comment by hightoxicity** [comment]
Far more strange, I decided to skip this machine and trying with another one (same boot config), it is properly working...

**Comment by dholt** [comment]
weird... that looks like a DGX, do you have the latest BIOS/BMC firmware?

**Comment by dholt** [comment]
Did you ever get this working?

**Comment by hightoxicity** [comment]
Hi guy the strange thing is that the server is now able to pxe boot with dgxie ha mechanism described in #41 , the important thing to know is that master nodes are vmware virtual machines, maybe it comes from the virtual network...

**Comment by dholt** [comment]
I do my testing on VMs but haven't seen this necessarily, but I have seen issues with virtual networking and Openstack network nodes, so who knows. Glad it's working.

**Comment by hightoxicity** [comment]
:-)
Thanks for your help!
