### ISSUE TITLE
Not able to install Kubernetes using Ansible and Kubespray.

### ISSUE THREAD

**Issue by SarthakGarg13** [NVIDIA/deepops#324]
I started with Kubernetes Deployment Guide,  completed steps 1 and 2 then ran into error in step 3, I changed the config/inventory file:
Changes made:

>                         Under [all] "mgmt0 ansible_host=<login/master-node address>"
>                         Under [all]  "gpu01 ansible_host=<compute/slave-node address>"
>                         Under [kube-master] Removed comment "mgmt01"
>                         Under [etcd] Removed comment "#mgmt01"
>                         Under [kube-node] Removed comment "#gpu01"
>                         Under [all:vars] "ansible_user = <username>
>                         Under [all:vars] ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q 
>                          <username-compute-node>@<compute-node-address>"'

Step 4: Ran this command: `ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml`

Got the following error:

> TASK [kubernetes/preinstall : Create kubernetes kubeadm compat cert dir (kubernetes/kubeadm issue 1498)] ***
> fatal: [gpu01]: FAILED! => changed=false 
>   gid: 0
>   group: root
>   mode: '0755'
>   msg: refusing to convert from directory to symlink for /etc/kubernetes/pki
>   owner: root
>   path: /etc/kubernetes/pki
>   size: 4096
>   state: directory
>   uid: 0
> fatal: [mgmt01]: FAILED! => changed=false 
>   gid: 0
>   group: root
>   mode: '0755'
>   msg: refusing to convert from directory to symlink for /etc/kubernetes/pki
>   owner: root
>   path: /etc/kubernetes/pki
>   size: 4096
>   state: directory
>   uid: 0

Last few lines show
mgmt01 changed ok=72 not_reachable=0 failed=1
gpu01 changed ok =20 not_reachable=0 failed =1

`kubectl get nodes`

Shows only master node as ready.
What am I missing?

_Master node was running on Ubuntu 16.04
And Compute node on Ubuntu 18.04.
Docker Version - 18.09_

**Comment by dholt** [comment]
It seems like you had an existing install, please try resetting the cluster and trying again: https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md#reset-the-cluster

We also don't support Ubuntu 16.04 so can't say for sure if it will work as your master node.
