### ISSUE TITLE
configmaps "rook-ceph-mon-endpoints" not found

### ISSUE THREAD

**Issue by vinayjain15** [NVIDIA/deepops#329]
rook-ceph-tools is failing with error: MountVolume.SetUp failed for volume "mon-endpoint-volume" : configmaps "rook-ceph-mon-endpoints" not found

 image: rook/ceph:master

[svctnsas@n01apl496 OpenShift]$ ./oc -n rook-ceph get configmap
NAME                                       DATA      AGE
local-device-n1                    1         11m
local-device-n2   1         11m
local-device-n3   1         11m
rook-config-override                       1         6m

**Comment by dholt** [comment]
Unfortunately we don't support OpenShift and have no way to test.

You might try to re-add that configmap manually and see if there's a noticeable issue.
