### ISSUE TITLE
Disable StrictHostKeyChecking by default or document the need

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#332]
We recommend that users install DeepOps on freshly provisioned systems.

If you are running through the setup guide on a freshyly provisioned system the initial connection will always fail due to StrictHostKeyChecking.

A quick fix around this is just to ssh to each node. A better fix would be to document this or to disable StrictHostKeyChecking in the config somewhere.

**Comment by dholt** [comment]
Is this using DGX OS? I have never run into this problem with MAAS.

Can you issue a PR or describe what you'd like the documentation to say? We can't disable StrictHostKeyChecking.

**Comment by dholt** [comment]
The only thing I can determine is that this is a control path issue stemming from multiplexed SSH connections. I'm going to document removing the socket. If you have more info, please re-open.
