### ISSUE TITLE
AWS Enviroments

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#347]
I would like to know the way to install  the deepops on AWS instance. Would anyway guide me the way to do it? I followed the quick start guide and readme, but I got off on the wrong foot at the ansible running. Especially, I would like to be clear the setting for Ansible in case of using the Key pair.

**Comment by ScottESanDiego** [comment]
What I do is edit config/inventory and set:

```
ansible_user=ubuntu
ansible_ssh_private_key_file=~/DeepOps.pem
private_key_file=~/DeepOps.pem
```

(Where ~/DeepOps.pem is a the private key corresponding to the one you provisioned the nodes with)

**Comment by Kaka1127** [comment]
Thank. I’ll give it a try.

**Comment by Kaka1127** [comment]
I added the your comment to config/inventory and put the Key pair file on "~/kaka1127.pem" but showed the error. It seems this configuration was looking for the kaka1127.pem.pub file... Any idea?

config/inventory file
***********************
######
# SSH connection configuration
######
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/kaka.pem
private_key_file=~/kaka.pem
***********************

Error message.
*************************
fatal: [gpu01]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/kaka.pem.pub"}
*************************

**Comment by ScottESanDiego** [comment]
Did you copy `kaka.pem` to the root of where you are running the playbook?

**Comment by Kaka1127** [comment]
When I copy the kaka.pem file to /home/ubuntu/deepops/ directory, it was progressed. Thanks!
Mainly I have used the Key pair file which AWS console generated. Is it correct? Or should I generate the Key file with following [this](https://github.com/NVIDIA/deepops/blob/master/docs/ANSIBLE.md) link?
But I met other permission error.

```
TASK [bootstrap-os : Bootstrap | Install python 2.x and pip] ******************************************************************
fatal: [mgmt]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 100, "stderr": "Shared connection to 54.199.165.153 closed.\r\n", "stderr_lines": ["Shared connection to 54.199.165.153 closed."], "stdout": "\rReading package lists... 0%\r\rReading package lists... 100%\r\rReading package lists... Done\r\r\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\r\nE: Unable to lock directory /var/lib/apt/lists/\r\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\r\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\r\n", "stdout_lines": ["", "Reading package lists... 0%", "", "Reading package lists... 100%", "", "Reading package lists... Done", "", "E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)", "E: Unable to lock directory /var/lib/apt/lists/", "W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)", "W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)"]}
fatal: [gpu01]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 100, "stderr": "Shared connection to 13.231.221.200 closed.\r\n", "stderr_lines": ["Shared connection to 13.231.221.200 closed."], "stdout": "\rReading package lists... 0%\r\rReading package lists... 100%\r\rReading package lists... Done\r\r\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\r\nE: Unable to lock directory /var/lib/apt/lists/\r\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\r\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\r\n", "stdout_lines": ["", "Reading package lists... 0%", "", "Reading package lists... 100%", "", "Reading package lists... Done", "", "E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)", "E: Unable to lock directory /var/lib/apt/lists/", "W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)", "W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)"]}
```

**Comment by ScottESanDiego** [comment]
It's up to you how you want to do it.

What I do is:
1) Make a keypair in AWS
2) Download the private key (e.g., `mykey.pem`)
3) Spin up an instance using that key, and grab the public key from `known_hosts` (save it as `mykey.pem.pub`)
4) Copy both the public and private key to the root of the instance (e.g., `~ubuntu/mykey.pem` and `~ubuntu/mykey.pem.pub`)
5) `chmod go-rwx ~/*.pem`
6) Clone the DeepOps GIT onto the system
7) `./deepops/scripts/setup.sh`
8) Edit the `config/inventory` file as I described above
9) Run the playbooks, etc.

I don't quite understand the nature of the permissions error you're getting above though, I can't see why it would be failing at that step due to a key issue. :-/

**Comment by Kaka1127** [comment]
Thank you for your comment. I gave a try but I met the same error which I reported you. Could you please help me?
Here is the my procedure.

1. Make a key pair(kaka.pem) in AWS and download it.
2. Login the AWS with Macbook.
3. Make the public key file(kaka.pem.pub) from know_hosts file.
4. Copy the public and private key file to the instance at the following directory.
```
   /home/ubuntu/kaka.pem
   /home/ubuntu/kaka.pem.pub
```
5. Change the file permission.
```
    chmod 400 kaka.pem
```
6. Install the git and clone the deepops and clone and did the checkout
```
git clone  https://github.com/NVIDIA/deepops.git
cd deepops
git checkout tags/19.03
./scripts/setup.sh
```
     Note: When I run this script from root of instance, I met the error that there is not config.example folder.
7. Edit the config/inventory file as below.
```
   ansible_user=ubuntu
   ansible_ssh_private_key_file=~/kaka.pem
   private_key_file=~/kaka.pem
```    
8. Run the playbook.
```
ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml
```

**Comment by Kaka1127** [comment]
Thank you for your information! I could run the playbook by using the '19.07'.
