### ISSUE TITLE
Installation of deepops

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#353]
Hi team,

Need your support in installation of deepops.

Thank You

**Comment by ajdecon** [comment]
Are you running into any particular issues? Unfortunately we can't help directly with each individual install via Github, but if you're running into specific problems we can try to help solve the issue.

If you're at the beginning of your DeepOps setup, I'd suggest taking a look at our [Getting Started](https://github.com/NVIDIA/deepops/blob/master/docs/getting-started.md) doc.

**Comment by ajdecon** [comment]
This issue isn’t asking for anything concrete, and no reply in 3 days. I’m going to close this, but please feel free to reopen (or open a new issue) if you have specific questions. Thanks!
