### ISSUE TITLE
Proposed design for a DeepOps CLI tool

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#364]
We're discussing building a DeepOps CLI tool to simplify some common use cases. This CLI isn't intended to replace direct use of the Ansible playbooks, but instead automate some frequent tasks for regular DeepOps users.

For our initial implementation, we are aiming to support some *single-node* tasks, such as:

* Installing the NVIDIA driver on a new system
* Setting up Docker and nvidia-docker for running GPU-enabled containers
* Setting up single-node clusters for k8s or slurm

Future extensions to this tool will support targeting remote nodes, or provisioning new resources using cloud providers for similar testing.

<hr/>

## Basic user interface

The overall design will be consistent with a `deepops <verb> <noun>` pattern, where the verb is some action we want to take and the noun is an entity we wish to manage or provision.

For example, our existing proposed use cases on local nodes would have simple commands such as:

`deepops install deepops-dependencies`

`deepops install nvidia-driver`

`deepops install nvidia-docker`

`deepops install k8s`

`deepops install slurm`

The default assumption for all of these use cases is that we would be targeting a single node, `localhost`. The actual implementation is expected to be pretty simple -- in most cases, this is just a wrapper around an `ansible-playbook` command -- but should simplify workflows in some common use cases.

## Proposed extensions

We already expect a few simple extensions to this design, once the base case of running against localhost is implemented.

### Targeting remote hosts

The first proposed extension to this design is to perform the same task against one or more remote hosts where we have `ssh` access. For example,

`deepops install nvidia-docker --target=<hostname>,<hostname>,<hostname>,...`

For some installations, such as the Slurm and Kubernetes cluster implementations, we may provide multiple options to accommodate the multi-node implementation of these services. Where we are specifying node groups, we should use the same naming as the inventory file.

For example, to build a single-node slurm cluster on a remote host we should use:

`deepops install slurm --target=<hostname>`

But to build a multi-node slurm cluster we should use:

`deepops install slurm --slurm-master=<hostname> --slurm-node=<node1>,<node2>,...`

This extension can be implemented incrementally on a command-by-command basis.

### Setting up common example applications or demos

Another common use case is "one command setup" of common applications such as a demo. For example, to launch the "flowers" demo on a single-node kubernetes cluster, we would use a command such as:

`deepops application flowers`

For each app, this should implement installing the necessary resources for the app to run such as the NVIDIA driver, Docker, and Kubernetes.

### Provisioning cloud resources

We'd also like to use this tool to make provisioning cloud resources easier.

This will require some configuration step:

`deepops config aws --access-key=<key> --secret-key=<key>`

After which we can launch resources using an interface such as:

`deepops provision aws ec2 [--num-nodes=<x>] [--ami=<ami-xxxxxx>]`

**Comment by ekaakurniawan** [comment]
Dear @ajdecon, I have tried both DeepOps and Kubeadm (which is in CLI) but both are having similar issue for me. The details are in #355 for DeepOps and #367 for Kubeadm. The complete setup steps are in #367. It seems to me that having the CLI is easier to describe the steps in case of issues. Thx.

**Comment by ajdecon** [comment]
WIP pull request for starting this implementation: #368
