### ISSUE TITLE
k8s_deploy_kubeflow.sh assumes helm is installed on the provisioning node

### ISSUE THREAD

**Issue by kkersten** [NVIDIA/deepops#373]
The latest update to k8s_deploy_kubeflow.sh assumes helm is installed on the provisioning node, but this may not be true.

Should helm be installed on the provisioning node with the setup.sh script?

If not, we should point to docs/helm.md for manual install before deploying kubeflow in the Kubernetes Guide.

**Comment by michael-balint** [comment]
Helm can be installed on the provisioning node with the `scripts/install_helm.sh` script.

If the suggestion is to enable a check (as we do in other scripts) for helm, then @supertetelman might have a comment.

**Comment by supertetelman** [comment]
Yeah. I think the correct thing to do here is to check for helm, halt the process, and have the user manually install helm using a different script before re-starting the install.

I'll work that into the next v0.7 update

**Comment by John-P** [comment]
I have been going through the deployment guide myself but got stuck when the tiller-deploy pod became stuck pending. After being confused for half an hour this appears to have resolved the issue.

**Comment by supertetelman** [comment]
Looking through this, the current Kubeflow installation script does not have any dependencies on helm and there are now checks in place for all the required packages (along with some better error messages and documentation here: https://github.com/NVIDIA/deepops/blob/master/docs/kubeflow.md).
