### ISSUE TITLE
Deplouy Kubeflow script needs to be modified for RHEL

### ISSUE THREAD

**Issue by kmwm3** [NVIDIA/deepops#374]
In the script "scripts/k8s_deploy_kubeflow.sh" there is a function that looks for "ID_LIKE" = rhel* or debian*, but with a RHEL 7.6 OS, the ID_LIKE is "fedora", resulting in a message "Unsupported Operating System fedora" message. The script needs to account for ID_LIKE = "fedora*"

Script function:
function install_dependencies() {
  # Install dependencies
  . /etc/os-release
  case "$ID_LIKE" in
      rhel*)
          type curl >/dev/null 2>&1
          if [ $? -ne 0 ] ; then
              sudo yum -y install curl wget
          fi
          ;;
      debian*)
          type curl >/dev/null 2>&1
          if [ $? -ne 0 ] ; then
              sudo apt -y install curl wget
          fi
          ;;
      *)
          echo "Unsupported Operating System $ID_LIKE"
          exit 1
          ;;
  esac

RHEL 7.6 /etc/os-release:
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

**Comment by supertetelman** [comment]
It looks like that line should be more like:

```
case "$ID" in
    rhel*|centos*)
```

I'll check in a fix.

**Comment by kmwm3** [comment]
Same problem in the scripts/install_helm.sh script.

**Comment by supertetelman** [comment]
Addressed in 4e97c848864616664b8c7e3cc736fe11bcaf1c78
