### ISSUE TITLE
GPU operator

### ISSUE THREAD

**Issue by jaimehrubiks** [NVIDIA/deepops#376]
Are there any plans to start using this? 
https://devblogs.nvidia.com/nvidia-gpu-operator-simplifying-gpu-management-in-kubernetes/

It looks promising. Or, did any of you try to use it with the current deepops version?

**Comment by michael-balint** [comment]
Yes, there are plans to, but the current version of the gpu-operator is a "technical preview release". The GPU driver, NVIDIA container runtime, and the NVIDIA K8s device plugin are all already installed via Ansible playbooks in DeepOps. So essentially, all that is missing in a DeepOps K8s deployment is the automatic node labeling.
