### ISSUE TITLE
Usage of Inventory file 

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#377]
Hi Team,

Please let me confirm the following question.
Would you please teach me the way to use the inventory file when one master and one node are used on this script?

Here is the settings for clusters.
 Master: IP 10.123.192.10
               ansible_user=mgmt
               ansible_ssh_user=mgmt
               ansible_ssh_pass=mgmt
               ansible_sudo_pass=mgmt
               ansible_ssh_private_key_file=~/mgmt.pem
               private_key_file=~/mgmt.pem
 Worker: IP 10.123.192.20
               ansible_user=nvidia
               ansible_ssh_user=nvidia
               ansible_ssh_pass=nvidia
               ansible_sudo_pass=nvidia
               ansible_ssh_private_key_file=~/dgx.pem
               private_key_file=~/dex.pem

In this case, the user name and password and so on are different on each nodes.  How should I write the Inventory file?
If possible, please provide the example code.

Best regards.
Kaka

**Comment by michael-balint** [comment]
Check out the [ansible docs](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) on building an inventory.

It's possible to do something like...

```
master-server    ansible_host=10.123.192.10    ansible_user=mgmt    ansible_password=mgmt
worker-server    ansible_host=10.123.192.20    ansible_user=nvidia  ansible_password=nvidia
```

Although be careful about plaintext passwords ;-).
