### ISSUE TITLE
Show the issue with DeepOps on DGX Station

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#378]
I tried to installed the latest DeepOps(19.10) on DGX-Station (OS: 4.1.0).
But I met the issue as below. Do you have any solution to resolve it?

```
coredns
0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.
```

If you need more information, please let me know.
Best regards.
Kaka

**Comment by michael-balint** [comment]
@Kaka1127 - This is typically not a real issue since two coredns pods are launched and on a single-node deployment one of them will be stuck in a "pending" state. Everything else should work on the cluster.

```
$ kubectl get pods -n kube-system
NAME                                        READY   STATUS    RESTARTS   AGE
...
coredns-74c9d4d795-bmcvh                    0/1     Pending   0          12m
coredns-74c9d4d795-fgxbc                    1/1     Running   0          12m
...
```

**Comment by Kaka1127** [comment]
Thank you! I got it!
