### ISSUE TITLE
K8S non-gpu node

### ISSUE THREAD

**Issue by SpontaneousDuck** [NVIDIA/deepops#379]
Is there a way to add nodes without a GPU (on-chip Intel GPU only or older unsupported NVIDIA GPU) to the Kubernetes cluster through deep-ops for purpose of storage or processing nodes? Or will I have to add those nodes manually through Kubernetes? Thanks!

**Comment by dholt** [comment]
You can add any type of node you like to k8s, the deepops playbook will detect supported GPUs and automatically set them up to work in k8s. With a CPU-only node, those parts will get skipped and the node will be added to k8s.

**Comment by SpontaneousDuck** [comment]
It work! Thanks for fixing that guys!
