### ISSUE TITLE
Failed at TASK [bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)] 

### ISSUE THREAD

**Issue by yujunz** [NVIDIA/deepops#401]
```
TASK [bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)] **************************************************************************************************************************************
fatal: [i-085a99802ef88b59b]: FAILED! => changed=false
  msg: |-
    Command failed rc=1, out=, err=Could not set property: Interactive authentication required.
```

**Comment by ajdecon** [comment]
> Could not set property: Interactive authentication required.

Based on this error, I'm guessing this is an issue with needing a password for either `ssh` or `sudo`. I'd suggest making sure you can SSH and sudo on these hosts without a password.

If this doesn't work, can you provide a more verbose error log to help debug?

**Comment by yujunz** [comment]
I can ssh and sudo on these hosts without a password. It is probably because this is delegated to localhost and it does require password for sudo on my Mac.

**Comment by supertetelman** [comment]
Seems lack a `-kK` would have resolved this and the documentation around this has been improved. Marking this issue as stale/resolved.

**Comment by Fencherr** [comment]
in my case i solved it with --become --ask-become-pass option
