### ISSUE TITLE
k8s_deploy_kubeflow.sh script is broken due to kfctl issue #167

### ISSUE THREAD

**Issue by mboglesby** [NVIDIA/deepops#408]
See https://github.com/kubeflow/kfctl/issues/167. It doesn't look like they plan to fix this issue in the kfctl v0.6 branch, so the only workaround would be to use kfctl v0.7.2-rc.0 or above.

**Comment by supertetelman** [comment]
Yeah, it's unfortunate. It looks like 6.2 will remain broken and we'll need to bump up to the v1.0-rc.  I'm working on a fix right now and hoping to get something out soon. 

Although v1.0 is due to come out by the end of the month, depending on timing we might just jump straight there and skip the v7 release.

Luckily, the v0.5.1 script is still working.

**Comment by supertetelman** [comment]
I'm having a lot of trouble actually getting the latest release to launch successfully.

I have this branch https://github.com/supertetelman/deepops/tree/kubeflow-0.7.0 but I haven't been able to actually get the Kubeflow GUI running, I keep getting issues with the mysql database and the webcert manager pods.

**Comment by mboglesby** [comment]
I was able to get 0.7.1 deployed yesterday using the manual deployment process (https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/) and the v1.0-rc.1 kfctl binary. The GUI is working fine and I haven't noticed any issues with any pods spinning up correctly, but my pipelines have been running excruciatingly slow.

**Comment by supertetelman** [comment]
Okay, not sure why my deployment was failing. I may have been running on an older version.

I have an update checked in that works to install, delete, and re-install kubeflow v0.7.1 with the kfctl v1.0-rc1 file.  Hopefully this PR will help the upgrade to v1.0 go smoother as well.

**Comment by michael-balint** [comment]
This should be working now, thanks to #415 and @supertetelman
