### ISSUE TITLE
mpirun for example after slurm install fails

### ISSUE THREAD

**Issue by lebonez** [NVIDIA/deepops#409]
I ran into an issue where the package provided for openmpi in ubuntu 18.04 is compiled without slurm support. When I run mpirun -np 10 ./mpi-hello i get:

An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).

srun ./mpi_hello runs as expected across multiple nodes.
After compiling openmpi from source to prefix /usr/local then doing this:
export LD_LIBRARY_PATH=/usr/local/lib
mpirun -np 10 -x LD_LIBRARY_PATH ./mpi-hello

Finally it works across multiple nodes. 
Hello from process 2 of 10 on host gpu01
Hello from process 7 of 10 on host gpu02

I am not sure if anyone else has run into this. if so maybe changing the test to srun would be better?

**Comment by supertetelman** [comment]
It sounds like the `srun` command worked for you.

A lot of these dependency issues with Slurm were fixed with our big Slurm update this week. I'm going to close this issue for now since there is a workaround and we've likely fixed this.

**Comment by zyndagj** [comment]
I'm seeing this issue on the latest version of deepops as well.

**Comment by zyndagj** [comment]
While using `mpirun` from in a job does not work, allocating a job with

```
salloc -N 2 -n 4 -G 4
```

and then running MPI tasks with

```
srun --mpi=pmix mpi_app
```

worked as expected.
