### ISSUE TITLE
CoreOS Helm Chart repo => 403 Forbidden

### ISSUE THREAD

**Issue by nvhans** [NVIDIA/deepops#418]
Running ./scripts/build_offline_cache.sh, variable HELM_COREOS_CHARTS_URL results in the following:

+ get_all_helm_tgzs https://s3-eu-west-1.amazonaws.com/coreos-charts/stable
+ local repo_url=https://s3-eu-west-1.amazonaws.com/coreos-charts/stable
+ rm -f index.yaml
+ wget https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml
--2020-01-27 12:49:46--  https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.109.139
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.109.139|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-01-27 12:49:47 ERROR 403: Forbidden.

**Comment by alleny87** [comment]
I experienced the same issue, but was able to get past it by:
Commenting out line 56 and line 59 of 'scripts/build_offline_cache.sh'

I also commented out all docker images related to CoreOS from:
'roles/offline-repo-mirrors/defaults/main.yml'

but I don't know the implications of doing so. Have not gotten as far as deploying deepops in my offline environment

**Comment by ajdecon** [comment]
Fixed in #458
