### ISSUE TITLE
Move requirements.yml file to roles/ directory

### ISSUE THREAD

**Issue by medzin** [NVIDIA/deepops#444]
Could you move the `requirements.yml` file to the `roles/` directory? It will allow to easily use this repository as a [AWX](https://github.com/ansible/awx/) project because dependencies are automatically downloaded by it if the file is in `roles/` dir. Files in other locations require some hacking to force AWX to download dependencies from it.

**Comment by supertetelman** [comment]
@dholt, any reason we can't/shouldn't do this? IT seems like a quick update.

**Comment by dholt** [comment]
Done in #653
