### ISSUE TITLE
Ansible playbook

### ISSUE THREAD

**Issue by anmol039w** [NVIDIA/deepops#445]
I'm trying to install kubernetes using Deeops and followed the following

copy ssh id of login and compute into each other
swapoff -a
cloning github repo for deepops and git checkout 19.10
ran /.scripts/setup.sh

Now when i'm running nsible all -m raw -a "hostname"

I'm getting the following error
frontier@frontier:~/deepops$ ansible all -m raw -a "hostname"

PLAY [Ansible Ad-Hoc] *******************************************************************************************************************

TASK [raw] ******************************************************************************************************************************
fatal: [frontier]: FAILED! => changed=true
  msg: non-zero return code
  rc: 1
  stderr: |-
    Warning: Permanently added '10.0.0.242' (ECDSA) to the list of known hosts.
    Shared connection to 10.0.0.242 closed.
  stderr_lines:
  - 'Warning: Permanently added ''10.0.0.242'' (ECDSA) to the list of known hosts.'
  - Shared connection to 10.0.0.242 closed.
  stdout: |-
    sudo: a password is required
  stdout_lines: <omitted>

PLAY RECAP ******************************************************************************************************************************
frontier                   : ok=0    changed=0    unreachable=0    failed=1

Need help to understand why this is happening as there are no proxy restrictions on both the devices

**Comment by dholt** [comment]
You'll need to add the `-K` flag since sudo requires a password. If you're following the Slurm guide, the documentation gives you more info in the next step:

```
# NOTE: If SSH requires a password, add: `-k`
# NOTE: If sudo on remote machine requires a password, add: `-K`
# NOTE: If SSH user is different than current user, add: `-u ubuntu`
```
