### ISSUE TITLE
Ansible reports "environment" is not a valid attribute for a "IncludeRole" 

### ISSUE THREAD

**Issue by pinglin** [NVIDIA/deepops#460]
During `ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml` (Release 20.02), Ansible will report Error `"environment" is not a valid attribute for a "IncludeRole"`

This failure can be reproduced with Ansible version `2.9.5` and `2.8.10` but for version `2.7.11`, it's totally fine. No idea what has been changed on Ansible's side. 

BTW, the Ansible version shown in the release page is `2.8.11`, which I think could be a typo as there is no version number `2.8.11` for Ansible.

**Comment by dholt** [comment]
We're still only supporting ansible 2.7.11 and lower in 20.02. In the upcoming release we'll support Ansible 2.9. We have seen this too and are making sure it works. Thanks for bringing it up!

**Comment by cupdike** [comment]
Am I missing more detailed instructions/documentation somewhere?  So far I've been following the docs (or so I think) and have hit the "Ansible <= 2.7.11 issue for 20.02 and the must stick with Python 2 issue on Centos 7.
