### ISSUE TITLE
Job Scheduling

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#463]
Hi Team,

Please give us your comments.
Do you know the way to deploy the job in the order of creation time?
When I created the training job to DGX-S with deploying the Deepops, the deployment of job did not sort by creation time.(i.e. It has been randomly deployed.) Here is the manifest file.

Case1:
----
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-1
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-2
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-3
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-4
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-5
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
----

Case2:
 pytorch-mnist-1 -> pytorch-mnist-3 or pytorch-mnist-4 or pytorch-mnist-5 -pytorch-mnist-2
----
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-1
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 3
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-2
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 2
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-3
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-4
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-mnist-5
spec:
  containers:
    - name: pytorch-container
      image: nvcr.io/nvidia/pytorch:20.02-py3
      command: ["/bin/sh", "-c"]
      args: ["python /opt/pytorch/examples/upstream/mnist/main.py --epochs 1"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath: 
        path: /data
  restartPolicy: Never
----

If you have any question, please let me know.
Best reagrds.
Kaka

**Comment by michael-balint** [comment]
What you are witnessing is not a function of DeepOps, but the behavior of Kubernetes. If you are asking to guarantee order of execution with the pods that you are deploying, you will likely need to look at creating [pod priority classes](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/). I also recommend looking into [k8s jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/).
