### ISSUE TITLE
Ansible-playbook failure. Can't connect to new control master

### ISSUE THREAD

**Issue by GdMacmillan** [NVIDIA/deepops#475]
https://github.com/NVIDIA/deepops/blob/master/docs/getting-started.md

> Pick a provisioning node to deploy from. This is where the Ansible scripts should be run from and is often a development laptop that has a connection to the target cluster. On this provisioning node, clone the DeepOps repository...

I'm running into problems provisioning a networked GPU workstation for Kubernetes workloads using deepops. I want to use my MacBook as a controller to run the ansible-playbook but since it appears the guide is written for Ubuntu I decided to do this in a docker container I created. In this container, I cloned the deepops repo in the containers setup ssh key authentication and am able to access the remote host using `ssh gmacmillan@<public-ip>:<open-port>`

The host machine is currently running PopOS by system76. Since this is a ubuntu linux distro I figured it might be fine. Following the instructions in the video I'm able to run the ansible-playbook but it fails to install saying the control master is unreachable. I removed my ip and port in the logs below and replaced with <my-ip> and <my-port>. What is the network configuration supposed to be or is my use case possible?

Error logs
```
root@9313aacf4612:/workspace/deepops# ansible-playbook -l k8s-cluster -k -e ansible_ssh_port=<my-port> -vvv -u gmacmillan -K playbooks/k8s-cluster.yml
ansible-playbook 2.9.5
  config file = /workspace/deepops/ansible.cfg
  configured module search path = ['/workspace/deepops/kubespray/library']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Using /workspace/deepops/ansible.cfg as config file
SSH password:
BECOME password[defaults to SSH password]:
PLAYBOOK: k8s-cluster.yml ********************************************************************************************
34 plays in playbooks/k8s-cluster.yml

PLAY [all] ***********************************************************************************************************
META: ran handlers

TASK [install python (no proxy)] *************************************************************************************
task path: /workspace/deepops/playbooks/bootstrap-python.yml:7
<my-ip> ESTABLISH SSH CONNECTION FOR USER: gmacmillan
<my-ip> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=<my-port> -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="gmacmillan"' -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' -tt <my-ip>'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vvnzpgwllfjzlidvwtjqcaustcmqwylv ; test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)'"'"''
<my-ip> (255, b'', b"Warning: Permanently added '[<my-ip>]:<my-ip>' (ECDSA) to the list of known hosts.\r\nControl socket connect(/root/.ssh/ansible-gmacmillan@<my-ip>:<my-port>): Connection refused\r\nFailed to connect to new control master\r\n")
fatal: [pop-os-station]: UNREACHABLE! => changed=false
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '[<my-ip>]:<my-port>' (ECDSA) to the list of known hosts.
    Control socket connect(/root/.ssh/ansible-gmacmillan@<my-ip>:<my-port>): Connection refused
    Failed to connect to new control master
  unreachable: true

PLAY RECAP ***********************************************************************************************************
pop-os-station             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

In the inventory file, I added my host ip and named my host machine pop-os-station.

**Comment by dholt** [comment]
Hi, are you mounting your `~/.ssh` directory in the container? That's where SSH stores the control sockets (`'ControlPath=~/.ssh/ansible-%r@%h:%p'`). It looks like you may have a stale socket or permission issue (`Control socket connect(/root/.ssh/ansible-gmacmillan@<my-ip>:<my-port>): Connection refused`). You can safely remove old control sockets if you need to, they persist for 5 minutes and can cause SSH to break if access to the host has changed in some way.

**Comment by GdMacmillan** [comment]
Hey @dholt I am mounting my ~/.ssh directory. I was able to figure this out. But I had to do what was suggested by the second answer here: https://stackoverflow.com/questions/31649421/ansible-wont-let-me-connect-through-ssh

By setting:
```
[ssh_connection]
control_path_dir=/dev/shm/ansible_control_path
```
This allowed me to ping my server. 

So finally I am able to run the ansible command!
