### ISSUE TITLE
scripts/setup.sh

### ISSUE THREAD

**Issue by alleny87** [NVIDIA/deepops#479]
An additional line should be included on Line 67 of scripts/setup.sh should include:
    # Install ruamel.yaml
            as_user 'pip3 install ruamel.yaml'

ruamel.yaml is needed as a dependancy for kubespray

This Error was produced on Centos7 when trying to run ./scripts/build_offline_cache.sh
Error:
/scripts/k8s_inventory.sh 127.0.0.1
Traceback (most recent call last):
  File "kubespray/contrib/inventory_builder/inventory.py", line 40, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'

**Comment by alleny87** [comment]
An Additional line should include python 2's version of pip which is required for ansible on CentOS 7 after line 48:

`        # Install pip`
`        if ! which pip >/dev/null 2>&1; then`
`            echo "Installing python 2-pip..."`
`            as_sudo 'yum -y install python-pip' >/dev/null`
`        fi`

**Comment by dholt** [comment]
Hi, thanks for filing the issue! Should be fixed in #481
