### ISSUE TITLE
Permit to use an internal NTP server for node time syncing

### ISSUE THREAD

**Issue by hightoxicity** [NVIDIA/deepops#48]
In air gapped cluster, k8s nodes are not syncing themselves on NTP servers.
Time sync is needed for example for ceph.

As a quick workaround, I did following tasks:
- ansible all -k -b -a "apt-get install ntp ntpdate"
- ansible all -k -b -a "ntpd 10.0.7.10"
- ansible all -k -b -a "timedatectl set-ntp true"

**Comment by dholt** [comment]
Sort-of unrelated but I'm wondering what else you've done for air-gapped support. We'd love to have anything you can contribute.

**Comment by supertetelman** [comment]
This has been addressed by this PR: https://github.com/NVIDIA/deepops/pull/356
