### ISSUE TITLE
Deepops Ansible playbook failing at add key for Nvidia drivers

### ISSUE THREAD

**Issue by GdMacmillan** [NVIDIA/deepops#480]
I am trying to provision a single node GPU cluster using deepops on my home server. The playbook runs but stops short of completion at the following step:
```
TASK [nvidia.nvidia_driver : add key] ********************************************************************************************************************************************************************************************************
fatal: [deepops-station]: FAILED! => changed=false
  msg: 'Failed to download key at https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1910/x86_64/7fa2af80.pub: HTTP Error 404: Not Found' 
```

I looked up the index at https://developer.download.nvidia.com/compute/cuda/repos/ and unfortunately it doesn't appear my os is listed. My OS is actually PopOS by system 76 which is based on ubuntu 19.10. Is there a way around this error? Or can I not actually provision a Kubernetes node with Ubuntu 19.10 Eoan?

**Comment by GdMacmillan** [comment]
In fact I'm looking at skipping the CUDA Toolkit and Nvidia driver add as they are provided by system 76 and therefore already installed https://support.system76.com/articles/cuda

Is there a flag somewhere for this?

**Comment by dholt** [comment]
Hi, unfortunately we don't have a tag that will let you just skip the driver install. For now you can comment out the lines in `playbooks/k8s-cluster.yml`:

```
108 # Install NVIDIA driver on GPU servers
109 - include: nvidia-driver.yml
110   tags:
111     - nvidia
112   when: deepops_gpu_operator_enabled | default('false') | bool == false
```
