### ISSUE TITLE
HA Deployment

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#489]
Hi Team,

We are trying to deploy the deepops as per the documents, but we are unable to achieve the stable deployment.
Objective: 4 Nodes Deployment

S No. | Hostname | Role 1 | Role 2 | Role 3
-- | -- | -- | -- | --
1 | server11 | kube-master | etcd | slurm-master
2 | server22 | kube-master | etcd | slurm-master
3 | server33 | kube-node
4 | server44 | slurm-node

But We are getting error.
length is not divisible by 2

Deepops Version: 20.02

Thank You
Atul Yadav

**Comment by supertetelman** [comment]
Hello Atul,

Kubernetes requires an odd number of master nodes to be running for etcd. In an HA deployment this typically means you will have 3 master nodes so that if 1 goes down they can still form a quorum while the third reboots.

Are you able to try deployment again with a 3rd node?

**Comment by atulyadavtech** [comment]
Hi Adam,

Thank You for providing your input.
Is there any method we can deploy and configure the 2 node solution.
Objective: Reduce the costing.

Thank You
Atul Yadav

**Comment by ajdecon** [comment]
The odd number of master nodes is part of the architecture of how etcd works. See this part of their FAQ: [Why an odd number of cluster members?](https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#why-an-odd-number-of-cluster-members)
