### ISSUE TITLE
slurm deployment

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#496]
Hi

I met the following issue when deployed the slurm on GPUserver at AWS.
```
TASK [slurm : start slurmd] *********************************************************************************************
fatal: [gpu]: FAILED! => changed=false 
  msg: 'Could not find the requested service slurmd: host'
```
Also, I checked the systemd on GPU server and it was showed the following output.
```
ubuntu@gpu:~$ sudo systemd start slurmd
Excess arguments.
ubuntu@gpu:~$ sudo systemd daemon-reload
Excess arguments.
```
Note: 
 - Used the master branch. ( When used the other branch like tags.19.10, met the issue.)
 - Installed the slurm on one gpu server. (i.e. installed the master and node on one gpu server)

Others
 - I met the issue that need to prepare the "id_rsa.pem" file on development node before applying the playbook. 

Also you have any other questions, please let me know.
Best regards.
Kaka

**Comment by supertetelman** [comment]
I recently ran into some of these issues and opened a more detailed bug about getting Slurm up and running here: https://github.com/NVIDIA/deepops/issues/601

We've pushed a few changes, you may want to retry in AWS now and use some of the workaround in that bug.

I'm going to close this issue for now, if you are still hitting errors, would feel free to re-open this or add additional details to that newer bug. This is running on master of what will soon be 20.08.
