### ISSUE TITLE
Installation with error "Sorry, unxnn.users was not found on https://galaxy.ansible.com

### ISSUE THREAD

**Issue by billyw-dynasys** [NVIDIA/deepops#499]
To whom it may concern, 

I tried to download the Deepops package and installed it today. (April 16, 2020) 
However, I found that the setup failded with the messages below:
[WARNING]: - unxnn.user was NOT installed successfully: sorry, unxnn.users was not found on https://galaxy.ansible.com.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list. 

I tired to re-execute setup with ./setup.sh --ignore-errors and the setup still failed. 
Please advise if there is anyway to resolve the setup issue. Thanks. 

Regards,

Billy

**Comment by dholt** [comment]
Hi Billy, we've just released version 20.02.1 that should fix this issue: https://github.com/NVIDIA/deepops/releases/tag/20.02.1
