### ISSUE TITLE
 The error was: no test named 'equalto'

### ISSUE THREAD

**Issue by jxdn** [NVIDIA/deepops#501]
When I tried to run this  on CentOS : 

`ansible-playbook -l kube-master playbooks/k8s-cluster.yml`

It returned with :

>       fatal:` [mgmt01]: FAILED! => 
>       msg: |-
>       The conditional check 'gen_node_certs[inventory_hostname] or (not etcdcert_node.results[0].stat.exists|default(false)) or (not etcdcert_node.results[1].stat.exists|default(false)) or (etcdcert_node.results[1].stat.checksum|default('') != etcdcert_master.files|selectattr("path", "equalto", etcdcert_node.results[1].stat.path)|map(attribute="checksum")|first|default(''))' failed. The error was: no test named 'equalto'
>   
>     The error appears to be in '/root/deepops/kubespray/roles/etcd/tasks/check_certs.yml': line 57, column 3, but may
>     be elsewhere in the file depending on the exact syntax problem.
>   
>     The offending line appears to be:
>   
>   
>     - name: "Check_certs | Set 'sync_certs' to true"
>       ^ here
> 

Updating jinja2 to the latest version (2.11.2) won't help.
You need to specify the version to 2.11.1

`python -m pip install -U jinja2==2.11.1`

**Comment by jaimehrubiks** [comment]
Thank you
