### ISSUE TITLE
how to add GPU nodes to existing deepops k8s cluster?

### ISSUE THREAD

**Issue by ozota1** [NVIDIA/deepops#502]
There is a document for [adding k8s node](https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md#adding-nodes).
It seems that this is using kubespray directly and this will not setup nvidia-docker.

Is it possible to add  GPU nodes to existing deepops k8s cluster?
Or do I have to recreate my cluster?

**Comment by supertetelman** [comment]
Adding a new GPU node is relatively simple.

If you just add the new GPU worker nodes to your inventory file under the appropriate sections (I'm assuming `all` and `kube-node` in your case) just re-run `playbooks/kubenetes-cluster.yml`. It should have no/minimal impact on the existing nodes, setup your new nodes with drivers/docker/etc. and join the new nodes to the existing cluster.

**Comment by ozota1** [comment]
@supertetelman thank you for replying.

I have tried some procedure to adding a gpu node. Some procedure are failed and  the another is succeeded.
I guess the failed procedure is caused by [kubespray scale.yml bug](https://github.com/kubernetes-sigs/kubespray/issues/5141). But I have no time to troubleshooting about it. I just inform failed procedure and succeeded procedure at now.
I will check more and inform details later. 

# failed procedure
* edit inventory to add gpu node on `all` and `kube-node`
* run `ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml`
* ansible shows no errors. But `kubectl get nodes` does not show the new node.

# failed procedure2
* edit inventory to add gpu node on `all` and `kube-node`
* ansible-playbook -l k8s-cluster kubespray/scale.yml
* error occers at join to cluster like `kubelet cgroup driver: "systemd" is different from docker cgoup driver: "cgroupfs"`

# succeeded procedure
* edit inventory to add gpu node on `all` and `kube-node`
* run `ansible-playbook -l k8s-cluster kubespray/scale.yml` **-e kubelet_cgroup_driver=cgroupfs**
* run `ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml`
* `kubectl get nodes` showes GPU node and `kubectl get node -o yaml` shows GPU nubmer of added node.

**Comment by supertetelman** [comment]
Thank you for the procedure. I'm glad to hear it is now working.
