### ISSUE TITLE
ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml result in error

### ISSUE THREAD

**Issue by billyw-dynasys** [NVIDIA/deepops#503]
To whom it may concern, 

I found that I had issue when execute command step 5 in the URL: https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md
However, I found that the system reported error that missing sudo password. 
Therefore, I had attached my command result and the ssh user configuration in inventory file. 
Please advise if the configuration setting is correct or any pre-configuration step is required. Thanks. 

Regards,

Billy

1. - Command Executions & Result: 
dynasys@ubuntu:~/deepops$ ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details

PLAY [all] *********************************************************************

TASK [install python (no proxy)] ***********************************************
fatal: [ubuntu]: FAILED! =>
  msg: Missing sudo password

PLAY RECAP *********************************************************************
ubuntu                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

dynasys@ubuntu:~/deepops$

2: SSH user parameter setting in inventory file: 
[all:vars]
# SSH User
#ansible_user=ubuntu
#ansible_ssh_private_key_file='~/.ssh/id_rsa'
# SSH bastion/jumpbox
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@10.0.0.1"'
ansible_connection=ssh
ansible_user=dynasys
ansible_ssh_user=dynasys
ansible_ssh_pass=P@ssw0rd
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root

**Comment by billyw-dynasys** [comment]
To whom it may concern, 
For your update, I changed the configuration file as below and execute the same command and ended with different error as below: 

1. Error of the command result: 
TASK [install sudo package] ****************************************************
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [ubuntu]: FAILED! => changed=false
  cmd: apt-get update
  msg: |-
    E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    E: Unable to lock directory /var/lib/apt/lists/
    W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
    W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
  rc: 100
  stderr: |-
    E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    E: Unable to lock directory /var/lib/apt/lists/
    W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
    W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
ubuntu                     : ok=11   changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0


2. SSH parameter setting for Inventory 
######
# SSH connection configuration
######
[all:vars]
# SSH User
#ansible_user=ubuntu
#ansible_ssh_private_key_file='~/.ssh/id_rsa'
# SSH bastion/jumpbox
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@10.0.0.1"'
ansible_connection=ssh
ansible_user=dynasys
ansible_ssh_user=dynasys
ansible_ssh_pass=P@ssw0rd
ansible_become=true
ansible_become_method=sudo
ansible_become_user=dynasys
ansible_become_pass=P@ssw0rd

**Comment by billyw-dynasys** [comment]
To whom it may concern,
I tried to execute the command "ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml"
with root and the result also returned error message below.
So far, I tried to use admin user dynasys and specified the setting for sudo & sudo to user root or dynasys. I also tried to execute the same command with root with settings for sudo / ssh dynasys user. However, I found that I kept getting result in error. 
I would like to clarify the installation is expected from normal user or need to use root and if the current setting inventory is correct or any setting need to be configured. 
Thank you for your help. 

1. Error message after the execution of the command. 
TASK [Create SSH directory if it doesn't exist] ********************************
fatal: [ubuntu -> 127.0.0.1]: FAILED! => changed=false
  msg: 'There was an issue creating /root/.ssh as requested: [Errno 13] Permission denied: ''/root/.ssh'''
  path: /root/.ssh

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
ubuntu                     : ok=3    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

root@ubuntu:/home/dynasys/deepops#

2 - SSH parameter setting for Inventory
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@10.0.0.1"'
ansible_connection=ssh
ansible_user=dynasys
ansible_ssh_user=dynasys
ansible_ssh_pass=P@ssw0rd
ansible_become=true
ansible_become_method=sudo
ansible_become_user=dynasys
ansible_become_pass=P@ssw0rd

**Comment by jaimehrubiks** [comment]
I think you are having issues with ssh and ansible, not with deepops. Can you try it the same way you did in your first post but with this flag (-K)

ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml -K

So the thing is that if you use ansible_become=true but your user is not set in sudoers that it can do passwordless sudo then you need to provide -K with his password.

You don't need to be root in your local.

**Comment by supertetelman** [comment]
It seems like this was an issue with access/ssh and the bug is stale.

Closing for now, feel free to re-open the issue or open a new one if you are still having issues.
