### ISSUE TITLE
Removal of nodes deletes all containers

### ISSUE THREAD

**Issue by nwalker-nvidia** [NVIDIA/deepops#506]
Using the playbook to remove nodes from a k8s cluster, will also remove all container instances (active or stopped), even the ones that might've been there before the k8s implementation and are neither k8s services/components or been created by k8s.

**Comment by supertetelman** [comment]
The `remove-node.yml` is a part of the Kubespray project and it might be worth opening up a feature request over [there ](https://github.com/kubernetes-sigs/kubespray/issues) for that.

In general, it is not advised to be running Docker containers on a K8S node outside the scope of the cluster as it may cause resource contention issues and in some cases, the Kubernetes deployment may cause networking configuration changes that change the behavior of native Docker containers.

I am surprised that it cleans up stopped containers. That seems like a bug or at least something that should have a flag in the playbook.
