### ISSUE TITLE
No DGX BaseOS 4.4.0 support

### ISSUE THREAD

**Issue by nwalker-nvidia** [NVIDIA/deepops#507]
Release 20.02

The following aspects or feature do not work out of the box with DGX Server BaseOS 4.4.0:
- DeepOps will deploy a Docker runtime older than the current one available in DGX (19.03), which also impacts the use of the new "--gpus" flag in Docker
- There is no dedicated support to add "existing" nodes to the cluster
- Menu to specify options and customisation when deploying worker nodes would be useful to take into account specific requirement of existing installs
- An option to deploy K8s leveraging existing DNS infrastructure (dns mgm is a bit messy ...)

**Comment by dholt** [comment]
> DeepOps will deploy a Docker runtime older than the current one available in DGX (19.03), which also impacts the use of the new "--gpus" flag in Docker
We now install 19.03 by default

> There is no dedicated support to add "existing" nodes to the cluster
You can add nodes to the cluster by adding them to the inventory file and re-running a cluster playbook

> Menu to specify options and customisation when deploying worker nodes would be useful to take into account specific requirement of existing installs
Please open a feature request if this is something you want us to add. If this is a k8s feature, we use the kubespray project as-is so it would have to go to them.

> An option to deploy K8s leveraging existing DNS infrastructure (dns mgm is a bit messy ...)
K8s will use existing DNS on the nodes by default. If there's a specific bug please open another issue with details
