### ISSUE TITLE
No GPU Operator support for DGX

### ISSUE THREAD

**Issue by nwalker-nvidia** [NVIDIA/deepops#508]
A new functionality or playbook to deploy GPU Operator on new or "existing" DGX nodes.
Including the
1. uninstall of the GPU driver,
2. deployment of K8s, NVIDIA Device Plugin, Official DGX GPU Driver container (alignment table of BaseOS/Driver ver requireD), DCGM

Ensure NVSM can work (might have to be moved into container ?)

**Comment by supertetelman** [comment]
It sounds like this would just be running a command to uninstall the NVIDIA driver and then re-running the kubernetes-cluster.yml with the GPU Operator flag set. Is that right?

**Comment by supertetelman** [comment]
After talking to a few teams it sounds like this is a feature we will not be introduced. Any DGX OS / GPU Operator integration will take place in the GPU Operator project moving forward.
