### ISSUE TITLE
multi-node ngc containers in google cloud

### ISSUE THREAD

**Issue by denfromufa** [NVIDIA/deepops#510]
Is deepops a suitable approach to deploy multi-node ngc containers in google cloud for distributed training with Horovod / MPI / SLURM? Would you recommend pyxis for this instead?

**Comment by ajdecon** [comment]
DeepOps is a tool for setting up the OS dependencies and cluster management stack. So, for example, you can use DeepOps to set up Kubernetes or Slurm, and install the NVIDIA driver and other necessary tools.

Pyxis is a little different: it's a plugin for Slurm that makes it easy to run containers on a Slurm cluster. So you could, for example, use DeepOps to set up your Slurm cluster, and then install Pyxis after the DeepOps run is complete to enable that workflow.

We don't have any specific integrations with Google Cloud in DeepOps. It should likely work on Google Cloud VMs in the same way it would work on a set of on-premise machines, but it's not a workflow we regularly test.
