### ISSUE TITLE
unxnn.users

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#511]
Hi Team,

While installing Deepops getting below error:-
ENV Details:
root@server11:~/deepops# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

git clone --recurse-submodules https://github.com/NVIDIA/deepops.git
git submodule update
git checkout tags/20.02
./scripts/setup.sh
Error "unxnn.users was NOT installed successfully: - sorry, unxnn.users was not found on https://galaxy.ansible."
![Deep2](https://user-images.githubusercontent.com/13992953/81373795-3191ba80-911b-11ea-8dfb-f3394eea93e3.JPG)

![Deep1](https://user-images.githubusercontent.com/13992953/81373710-014a1c00-911b-11ea-97af-dac97ca835aa.JPG)

Looking forward for your response

Thank You
Atul yadav

**Comment by ajdecon** [comment]
This should be fixed in [DeepOps release 20.02.1](https://github.com/NVIDIA/deepops/releases/tag/20.02.1).
