### ISSUE TITLE
External NFS Server

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#512]
Hi Team,

How we can integrate external NFS server in the deepops environment.
3 Directory
Home Directory: Only Owned by the user with RW.
Input Directory: Read Only by all the users.
Share Directory: Read/Write by all the users.

Thank You
Atul Yadav

**Comment by dholt** [comment]
You can use the nfs-client playbook: https://github.com/NVIDIA/deepops/blob/master/config.example/group_vars/all.yml#L82

i.e in `config/group_vars/all.yml`:

`
external_nfs_server: 10.0.0.1
nfs_mounts:
  - mountpoint: /home
    server: '{{ external_nfs_server }}'
    path: /home
    options: async,vers=3
  - mountpoint: /mnt/input
    server: '{{ external_nfs_server }}'
    path: /export/input
    options: async,vers=3,ro`
  - mountpoint: /mnt/share
    server: '{{ external_nfs_server }}'
    path: /export/share
    options: async,vers=3`
`
