### ISSUE TITLE
Host doesn't support passthrought of host pci devices

### ISSUE THREAD

**Issue by dtordera** [NVIDIA/deepops#515]
Hello, 

Please before all, excuse my english.

I did correct passthrough of my Radeon RX 550, gpu, from two years ago until now, when I changed motherboard + cpu.

Then, previous motherboard+cpu was amd, currently one is intel 

So, this is the card (with integrated sound): lspci -nn
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] [1002:699f] (rev c7)
01:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] [1002:aae0]

This grub launcher configuration nowadays: 
 quiet splash amd_iommu=on vfio-pci.ids=1002:699f,1002:aae0

Amdgpu drivers are not loaded, blacklisted amdgpu & snd_hda_intel, and so, at first, ubuntu had not considered gpu group on boot: 

lspci -nnk 
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] [1002:699f] (rev c7)
	Subsystem: Gigabyte Technology Co., Ltd Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] [1458:22f3]
	Kernel modules: amdgpu
01:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] [1002:aae0]
	Subsystem: Gigabyte Technology Co., Ltd Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] [1458:aae0]
	Kernel modules: snd_hda_intel

This is what my modules files contain:

vfio
vfio_iommu_type1
vfio_pci
vhost-net
amdgpu
pci-stub
kvm
kvm_intel

I'm suspecting about BIOS, but shows Intel virtualization enabled, and in fact previous motherboard was more antique and simple. 

Please, if you can give me a clue about, 

Thanks,
Best regards,

**Comment by ajdecon** [comment]
Sorry, but we can't really help with configuration issues specific to setting up your hardware for virtualization. In particular, we don't really have any experience with AMD GPUs or what configuration you would need for pass-through.

I'd suggest getting help via either your Linux distribution (Ubuntu), or the hardware vendor for your machine.
