### ISSUE TITLE
Open OnDemand Install Ubuntu

### ISSUE THREAD

**Issue by SpontaneousDuck** [NVIDIA/deepops#540]
I am having issues getting Open OnDemand to work on my setup. I installed it with v20.06 of deepops on Ubuntu18.04 with slurm. I am able to use slurm perfectly and do everything I expect. I receive no errors during the install. When I visit http://<IP of slurm-master>:9050 I get an ERR_CONNECTION_REFUSED error. I am not real sure where to go and what to look at. Thank for your help!

**Comment by SpontaneousDuck** [comment]
The issue ended up being that the portal generator currently does not work on Ubuntu. It tries to generate the config file for RedHat httpd and fails because the directories do not exist. Fixing by setting an ubuntu only flag ```ood_portal_generator: false```

**Comment by dholt** [comment]
I'm not able to duplicate this, do you end up with a generated portal config when you set `ood_portal_generator: false`?

**Comment by dholt** [comment]
Fixed in https://github.com/NVIDIA/deepops/pull/541
