### ISSUE TITLE
Open OnDemand for Enroot/Pyxis

### ISSUE THREAD

**Issue by tkg61** [NVIDIA/deepops#548]
Will there be support for the Slurm-perf cluster playbooks with Open Ondemand? It seems like the Open Ondemand will only run on singularity. 

With all the other [NvidiaDeepLearning](https://github.com/NVIDIA/DeepLearningExamples) examples that utilize Enroot/Pyxis instead of Singularity it would be great to be able to run those examples on Open Ondemand

**Comment by dholt** [comment]
The only part of OOD in DeepOps that uses Singularity is the Linuxhost adapter: https://osc.github.io/ood-documentation-test/linuxhostadapter/installation/resource-manager/linuxhost.html

You would have to check with the OOD folks to see if they want to support another container runtime.

**Comment by tkg61** [comment]
So if we wanted to use both enroot/pyxis with OOD in the same cluster is that possible?

**Comment by dholt** [comment]
Absolutely, enroot/pyxis shouldn't have any incompatibilities with OOD. I can't say whether the OOD wrapper role in deepops will work with the Slurm-perf playbook, at some point we want to merge that back in to the regular slurm-cluster playbook, which is what the OOD playbook was tested with.

**Comment by tkg61** [comment]
Ok thanks! I’ll try testing with running the slurm-cluster playbook first and then run slurm-perf after to test
