### ISSUE TITLE
GPU Operator installing failed

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#549]
Hi 

When installed the deepops for AWS environments, I met the error as below.

```
fatal: [dgx]: FAILED! => 
  msg: 'An unhandled exception occurred while running the lookup plugin ''url''. Error was a <class ''ansible.errors.AnsibleError''>, original message: Received HTTP error for https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/manifests/cr/sro_cr_sched_none.yaml : HTTP Error 404: Not Found'
```

So, the yaml file on this URL did not present now. And now the version of gpu-operator is 1.1.7 and did not present the manifest folder on this project.

https://raw.githubusercontent.com/NVIDIA/gpu-operator/1.0.0/manifests/cr/sro_cr_sched_none.yaml
https://github.com/NVIDIA/gpu-operator

Would you please teach me the way to resolve this issue?
Does it just replace it to version 1.0.0 one?

Best regards.
Kaka

**Comment by iamharim** [comment]
Have you solved this problem? I have the same error.

**Comment by Kaka1127** [comment]
No, yet.

**Comment by supertetelman** [comment]
Closing his issue as we are in the process of upgrading to a much newer GPU Operator version and seem to have resolved this particular issue.

I'll re-open this or a new one if we being seeing issues again with GPU Operator 1.3 (https://ngc.nvidia.com/catalog/helm-charts/nvidia:gpu-operator)
