### ISSUE TITLE
DeepOps.hosts role is fragile to inventory configuration

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#550]
Errors like this are easy to run into:

```
fatal: [host1]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_interfaces'''
```

This is sometimes an issue with the inventory configuration, but this isn't always very clear. This is also really easy to trigger.

The role should be made more robust when generating the hosts file.

**Comment by tkg61** [comment]
Just ran into this error during a slurm-cluster initial setup. Failed on all nodes. Any advice? Inventory file hasn't change for a while.

**Comment by jxdn** [comment]
I got this error in the fresh installation.


`TASK [DeepOps.hosts : Install custom hosts file] *************************************************************************fatal: [mgmt01]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_interfaces'''
fatal: [mgmt02]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_interfaces'''
fatal: [mgmt03]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_interfaces'''
`
OS:
`NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"`

`ansible 2.9.5
  config file = /root/deepops/ansible.cfg
  configured module search path = ['/root/deepops/submodules/kubespray/library']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`

**Comment by kalaluthien** [comment]
I suffered this problem when I ran playbook with proper subset of all nodes, which made `'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_interfaces'` because ansible cannot collect interface informations from nodes that are not participating current play.

**Comment by jxdn** [comment]
For me solved with add ansible_interfaces and specify the interfaces in config/inventory file.

mgmt01     ansible_host=Xxx.xxx.xxx.101 ansible_interfaces=eth0

**Comment by captain-sysadmin** [comment]
I bumped into this issue because I had hosts in my inventory that were offline. @kalaluthien correctly observed that the error is because its trying to dump the IP of the primary network adaptor of *every* host into /etc/hosts. if the host is offiline, then the fact won't exist and you'll get an error. 

either make sure all your hosts are online, or remove the dead ones from the inventory
