### ISSUE TITLE
Setup.sh script showed error

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#565]
Hi Team,

I met the following error while running the setup.sh script on host pc.

```
Updating Ansible Galaxy roles...
 [ERROR]: failed to download the file: HTTP Error 500: Internal Server Error
[WARNING]: - geerlingguy.ntp was NOT installed successfully.
```

Would you please give us your advice to resolve this issue?
Here is my environments.
 OS: Ubuntu 18.04.4
 deepops: tags/20.06
 ansible 2.9.5
 git version 2.17.1

Best regards.
Kaka

**Comment by supertetelman** [comment]
This looks like it was a download error, I seem to recall a few intermittent erros for certain Galaxy packages a few weeks ago.

Have you retried this recently? I expect it would work now.

**Comment by Kaka1127** [comment]
Hi
I confirmed this issue today. It worked correctly.

Best regards.
Kaka
