### ISSUE TITLE
Issue installing Rook/Ceph

### ISSUE THREAD

**Issue by almansoorim** [NVIDIA/deepops#570]
Hi,

I am trying to test deepops in VMs (vmware workstation player), and tried to do  a simple setup:
1 VM for provisioning
1 VM is the master/worker node

I am not trying to run any heavy computations, just wanted to make sure deepops installs correctly.
I cant seem to get Rook/Ceph to work.

Used this command on deploy: ./scripts/k8s_deploy_rook.sh
and this command to monitor: ./scripts/ceph_poll.sh

I keep getting this error:
[errno 5] RADOS I/O error (error connecting to the cluster)
command terminated with exit code 1
command terminated with exit code 1

and on master/worker machine:
IPVS: rr: TCP some_IP:3300 - no destination available

Also, tried new installs couple of time making sure bootstrap-rook.yml also is satisfied. 

Is it possible to test the whole deepops system on VMs? or I am missing something else?

**Comment by SpontaneousDuck** [comment]
I am also seeing this same exact issue!

**Comment by guilhermehartmann** [comment]
Same behaviour in my current installation. Removing the namespace fails on cephclusters.ceph.rook.io that holds the state of the namespace alive.

**Comment by shadww** [comment]
Still looking into this issue. I feel like I am missing something tbh.
If I run "ceph status" command inside "rook-ceph-tools-*", I get the same error: "[errno 5] RADOS I/O error (error connecting to the cluster)"

commands:
> kubectl -n rook-ceph exec -ti rook-ceph-tools-856c5bc6b4-vjq72 bash
> ceph status

**Comment by almansoorim** [comment]
Still looking into this issue. I feel like I am missing something tbh.
If I run "ceph status" command inside "rook-ceph-tools-*", I get the same error: "[errno 5] RADOS I/O error (error connecting to the cluster)"

commands:
> kubectl -n rook-ceph exec -ti rook-ceph-tools-856c5bc6b4-vjq72 bash
> ceph status

**Comment by SpontaneousDuck** [comment]
I believe the issue @guilhermehartmann is seeing is related to [https://github.com/rook/rook/issues/5783](rook/rook#5783) which is being solved in the next major release of rook (v1.4). Basically the cephfs is never created and thus errors out on trying to delete. 

Have you tried an older version of rook yet @almansoorim ? I have not gotten around to trying that but was able to set this up successfully with an older version of deepops. I don't know which version increment is causing the problem for me.

**Comment by almansoorim** [comment]
@SpontaneousDuck I have not yet tried an older version (I am using 20.06). Will try to see if 20.02 works.

**Comment by SpontaneousDuck** [comment]
I will try just reverting the rook related changes and see what happens

**Comment by SpontaneousDuck** [comment]
Going back to 20.02.1 and 19.10 did not help me. What OS version are you running?

**Comment by almansoorim** [comment]
so I tried both 20.02.1 and 19.10. also, did not work.
nodes master/worker are on Ubuntu server 18.04, running in vmware.

I think I need to find alternative storage type if possible. like NFS or something.

**Comment by supertetelman** [comment]
In version 20.06 we bumped the ceph version up. This removed the abilitiy to crate Ceph Devices in directories located in `/var/lib/rook` and required that the user have a proper Device that Ceph could initialize and use. This was a fairly breaking change for a lot of users and we have since reverted that change in the `master` branch.

I'd advise not using the rook script in 20.06 and see how that goes. If you are installing/re-installing Ceph I would also point out that you should run `./script/rmrook.sh` inbetween attempt to cleanup any cruft left behind, I have seen this hang at times and require a reboot to clear up block device that appear stuck deleting.

upgrade: https://github.com/NVIDIA/deepops/pull/526
revert: https://github.com/NVIDIA/deepops/pull/538

**Comment by SpontaneousDuck** [comment]
I will try that @supertetelman ! I did do a cluster tear down and tried with the older Ceph version and settings reverted and still received the same error. I will try resetting my whole cluster and doing a completely fresh install.

**Comment by SpontaneousDuck** [comment]
Cluster tear-down and reinstall with reverting those changes did not fix the problem. I am going to try resetting my device's OS to make sure there is nothing residual left that is messing everything up.

**Comment by SpontaneousDuck** [comment]
I just did a clean install of v20.06 with the changes reverted (as shown in #538). This did not solve the problem and I still got:
```
$ kubectl -n rook-ceph exec -ti rook-ceph-tools-856c5bc6b4-lmbnq ceph status
[errno 5] RADOS I/O error (error connecting to the cluster)
command terminated with exit code 1
```

**Comment by SpontaneousDuck** [comment]
Hmm, this must have something to do with some update to Ubuntu 18.04? I set up a cluster with Deepops v19.07 on Ubuntu 18.04 servers last summer and was able to install a functioning rook with the defaults. I just went back and did that again with the same version of Deepops but Ubuntu 18.04 servers that were fully updated and rook ceph did not work. I got the same errors.

**Comment by almansoorim** [comment]
So, I went and tried to install rook and ceph manually using a tutorial based on the official steps:
https://itnext.io/deploy-a-ceph-cluster-on-kubernetes-with-rook-d75a20c3f5b1

It is bit outdated, but worked fine. I just had to enable the dashboard later on, and https://github.com/rook/rook/blob/master/Documentation/ceph-toolbox.md manually

I am now trying to figure why the deepops script did not work, although in the above tutorial I installed updated rook (v1.2) compared to one in deepops (v1.1.1). This tells me there is something else going on....

**Comment by SpontaneousDuck** [comment]
I found it!! So after doing the changes mentioned in #538, you also need to change `services/rook-cluster.yml:83` to be `image: rook/ceph:v1.2.7`. The toolbox pod was still being created with the newest version of rook (v1.3) and thus not working well with the v1.1 or v1.2 rook install. It looks like they dropped the support for in-directory ceph mounts with rook v1.3 so v1.2 will still work as we need it to with a directory. After setting the version of the toolbox properly, I was able to get the expected response from `ceph status`.

**Comment by almansoorim** [comment]
Hey @SpontaneousDuck this is interesting!
I will try it over the weekend and see on my end too. Hope it is all good for you and thanks!

**Comment by SpontaneousDuck** [comment]
One other thing, I did change the filsystem type on line 59 to be ext4 instead of xfs. Don't think that would affect it but logging it for posterity.

**Comment by almansoorim** [comment]
It worked even with ext4. I think this issue is solved.
Should carry one with @SpontaneousDuck workaround until things are updated.
Thanks for all who helped. I will close the issue with this comment.
