### ISSUE TITLE
what should be the configuration of the provisional node? 

### ISSUE THREAD

**Issue by yuvaramsingh94** [NVIDIA/deepops#571]
Hi all,
   we have two DGX1 and like to use Deepops for resource sharing . we have a desktop with intel i5 processor. will it be sufficient to act as the provisional node?. getting a new Intel Xeon server is not an option available for use now . pls share some info on weather we can use desktop/workstation as a provisional node

**Comment by michael-balint** [comment]
Hi @yuvaramsingh94 - the provisioning node can be pretty much any bit of hardware that is connected to your cluster and you can [run DeepOps Ansible scripts from](https://github.com/NVIDIA/deepops/blob/master/docs/ANSIBLE.md#requirements). A desktop with an Intel i5 processor sounds fine.

**Comment by yuvaramsingh94** [comment]
@michael-balint Thanks for quick answer . just a followup question . do we need to enable any visualizer on bios(Hypervisor, etc) on the provisional node. knowing this will save a lot of time for my team.

**Comment by dholt** [comment]
Not on the provisioning node; it's really only running Ansible, so any machine including a laptop would work fine.
