### ISSUE TITLE
HA Slurm clusters with our Ansible Module

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#575]
Hi Team,

Updated the "config/group_vars/all.yml"  for slurm HA.
ansible-playbook -l slurm-cluster playbooks/slurm-cluster.yml -vvvv
But it's SLURM HA configuration, not appearing.
fatal: [server22]: FAILED! => changed=false
  invocation:
    module_args:
      daemon-reload: true
      daemon_reexec: false
      daemon_reload: true
      enabled: true
      force: null
      masked: null
      name: slurmd
      no_block: false
      scope: null
      state: started
      user: null
  msg: 'Could not find the requested service slurmd: host'
PLAY RECAP **********************************************************************************************************************************
server11                   : ok=164  changed=9    unreachable=0    failed=1    skipped=193  rescued=0    ignored=0
server22                   : ok=160  changed=21   unreachable=0    failed=1    skipped=190  rescued=0    ignored=0

Looking for your guidance on configuring the SLURM in HA.

Thank You
Atul Yadav
Locuz

**Comment by dholt** [comment]
There is some Slurm documentation on HA, but it's not something we currently support: https://slurm.schedmd.com/quickstart_admin.html#HA
