### ISSUE TITLE
Feature Request: Pod Priority and Preemption

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#577]
Hi Team,

Is it possible to include the Pod Priority and Preemption method in deepops environment?

Pod Priority and Preemption

> User-Based scheduling 

> User Resource Utilization reoprting 

Thank You
Atul Yadav

**Comment by supertetelman** [comment]
A part of the user resource utilization reporting requires https://github.com/NVIDIA/deepops/issues/395 be completed.

What sort of priority/premption are you looking for? It might be possible to document this or provide some examples, but I think Kubernetes has some official documentation around this. A lot of the pod priority/preemption settings would be contained in the YAML for the workloads you are deploying.

Do you have some more precise use cases you have in mind?

**Comment by atulyadavtech** [comment]
Hi Team,

Just completed the method for achieving the requirement. 

Steps:

1. Created the High and low priority class.
2. Enable the resource quota for the GPU
3. Linked the resource quota with the per user namespace.

Demo#
https://youtu.be/l3dV4SDgr78

Thank You
Atul Yadav
