### ISSUE TITLE
Is OS provisioning DGXIe only for DGX-1 or is it working for DGX-2

### ISSUE THREAD

**Issue by obalouchi1** [NVIDIA/deepops#580]
Is OS provisioning only for DGX-1 or is it working for DGX-2

Thanks a lot

**Comment by supertetelman** [comment]
The DGXie is fairly flexible and should work for both DGX-1 and DGX-2 if you are able to configure the networking correctly.

You just need to make sure that the port names you have configured in the env file (https://github.com/NVIDIA/deepops/blob/master/config.example/pxe/env) correctly correspond to the system you are deploying. The ISO should be the same and there is already a valid configuraiton for DGX-1 and DGX-2 in the machines file (https://github.com/NVIDIA/deepops/blob/master/config.example/pxe/machines/machines.json), so nothing to do there.

Documentation can be found here: https://github.com/NVIDIA/deepops/blob/master/docs/dgxie-container.md
