### ISSUE TITLE
Create an optional section to setup and install Kubeflow

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#61]
Kubeflow is fairly simple to setup and integrate with Kubernetes. It is a very popular tool for deploying and managing DL jobs in Kubernetes clusters.

It would be beneficial to create/integrate additional Kubeflow playbooks so that users can launch Jupyter notebooks easier at the end of a DeepOps install.

**Comment by tlkh** [comment]
I totally agree we should include a note on how to install Kubeflow post-Kubernetes installation as it covers many use cases. However, maybe we should direct readers to the Kubeflow documentation for instructions on how to get started instead of creating a parallel version here?

**Comment by ryanolson** [comment]
Good idea, but let’s make sure our jupyterhub can launch NGC containers by default.

**Comment by supertetelman** [comment]
We already have a few scripts to install helm, ansible, etc.

Staying consistent with that, should we have a blurb on Kubeflow, a link to the official install steps, and a small script using the current install steps and a specific kubeflow version to set things up?

Agreed on NGC integration.

**Comment by dholt** [comment]
Kubeflow deployment script added
