### ISSUE TITLE
GPU Nodes Dashboard not showing the data/metrics,DGX_SWBUILD_VERSION="4.5.0"

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#614]
Hi Team,

Please find the environment overview
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
DGX_SWBUILD_VERSION="4.5.0"
NVIDIA-SMI 450.51.05    
Driver Version: 450.51.05    
CUDA Version: 11.0 

Followed the method as per the "https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md" 
But GPU Dashboard is not showing the GPU Metrics.
![image](https://user-images.githubusercontent.com/13992953/89863824-889aa600-dbc8-11ea-9d30-b05fa2b47a07.png)

![image](https://user-images.githubusercontent.com/13992953/89863852-9819ef00-dbc8-11ea-9528-cb6cf11253a6.png)

Dashboard 
![image](https://user-images.githubusercontent.com/13992953/89863957-c0a1e900-dbc8-11ea-8d41-35e7cd789ac9.png)

Error GPU Metric not avaible.

Thank You
Atul Yadav
Locuz

**Comment by supertetelman** [comment]
Looking at the top left of your last screenshot, it looks like you haven't selected a server to view metrics for.

This could either be that you haven't selected one or that none are available. If the former, have you followed the verification steps to show that GPU workloads are running on your cluster? Can share the output of describe nodes (to verify the GPU resource is available and the mode is properly labeled)?

**Comment by atulyadavtech** [comment]
Hi Team,

Updated/Changed the DeepOps version from 20.06 to 20.06.1.
Post-installation,   GPU Dashboard is visible.

Thank You
Atul Yadav
09980066464
