### ISSUE TITLE
Centos 8 Support

### ISSUE THREAD

**Issue by nate-92** [NVIDIA/deepops#634]
1. Issue or feature description
It doesn't look like there is support for Centos 8. Are there plans  to support CentOS8 by building/tagging/publishing corresponding nvidia/driver container images to Docker Hub.

2. Steps to reproduce the issue
helm install --devel nvidia/gpu-operator --wait --generate-name
NAME: gpu-operator-1597156936
LAST DEPLOYED: Tue Aug 11 09:42:18 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
kubectl get pods -n gpu-operator-resources
NAME                                       READY   STATUS             RESTARTS   AGE
nvidia-container-toolkit-daemonset-zhntc   1/1     Running            0          26m
nvidia-dcgm-exporter-kxl5f                 1/1     Running            0          26m
nvidia-device-plugin-daemonset-wnn69       1/1     Running            0          26m
nvidia-device-plugin-validation            0/1     Completed          0          26m
nvidia-driver-daemonset-nldp4              0/1     ImagePullBackOff   0          26m
nvidia-driver-validation                   0/1     Completed          0          26m
kubectl describe pod -n gpu-operator-resources nvidia-driver-daemonset-nldp4 | tail
Events:
  Type     Reason     Age                  From                                    Message
  ----     ------     ----                 ----                                    -------
  Normal   Scheduled  41m                  default-scheduler                       Successfully assigned gpu-operator-resources/nvidia-driver-daemonset-nldp4 to dcg2111.cas.mnbm01.gd-ais.com
  Normal   Pulling    39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Pulling image "nvidia/driver:440.64.00-centos8"
  Warning  Failed     39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Failed to pull image "nvidia/driver:440.64.00-centos8": rpc error: code = Unknown desc = Error reading manifest 440.64.00-centos8 in docker.io/nvidia/driver: manifest unknown: manifest unknown
  Warning  Failed     39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Error: ErrImagePull
  Warning  Failed     38m (x7 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Error: ImagePullBackOff
  Normal   BackOff    85s (x158 over 41m)  kubelet, dcg2111.cas.mnbm01.gd-ais.com  Back-off pulling image "nvidia/driver:440.64.00-centos8"
3. Information to attach (optional if deemed irrelevant)
Name        : centos-release
Version     : 8.1
Release     : 1.1911.0.8.el8
Architecture: x86_64
Install Date: Wed 26 Feb 2020 11:29:47 AM CST
Group       : System Environment/Base
Size        : 25430
License     : GPLv2
Signature   : RSA/SHA256, Thu 02 Jan 2020 01:33:42 PM CST, Key ID 05b555b38483c65d
Source RPM  : centos-release-8.1-1.1911.0.8.el8.src.rpm
Build Date  : Thu 02 Jan 2020 09:21:12 AM CST
Build Host  : x86-02.mbox.centos.org
Relocations : (not relocatable)
Packager    : CentOS Buildsys bugs@centos.org
Vendor      : CentOS
Summary     : CentOS Linux release file
Description :
CentOS Linux release files

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

(edited)
Show more
Just a style change

1. Issue or feature description
It doesn't look like there is support for Centos 8. Are there plans to  support CentOS8 by building/tagging/publishing corresponding nvidia/driver container images to Docker Hub.

2. Steps to reproduce the issue
helm install --devel nvidia/gpu-operator --wait --generate-name
NAME: gpu-operator-1597156936
LAST DEPLOYED: Tue Aug 11 09:42:18 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
kubectl get pods -n gpu-operator-resources
NAME                                       READY   STATUS             RESTARTS   AGE
nvidia-container-toolkit-daemonset-zhntc   1/1     Running            0          26m
nvidia-dcgm-exporter-kxl5f                 1/1     Running            0          26m
nvidia-device-plugin-daemonset-wnn69       1/1     Running            0          26m
nvidia-device-plugin-validation            0/1     Completed          0          26m
nvidia-driver-daemonset-nldp4              0/1     ImagePullBackOff   0          26m
nvidia-driver-validation                   0/1     Completed          0          26m
kubectl describe pod -n gpu-operator-resources nvidia-driver-daemonset-nldp4 | tail
Events:
  Type     Reason     Age                  From                                    Message
  ----     ------     ----                 ----                                    -------
  Normal   Scheduled  41m                  default-scheduler                       Successfully assigned gpu-operator-resources/nvidia-driver-daemonset-nldp4 to dcg2111.cas.mnbm01.gd-ais.com
  Normal   Pulling    39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Pulling image "nvidia/driver:440.64.00-centos8"
  Warning  Failed     39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Failed to pull image "nvidia/driver:440.64.00-centos8": rpc error: code = Unknown desc = Error reading manifest 440.64.00-centos8 in docker.io/nvidia/driver: manifest unknown: manifest unknown
  Warning  Failed     39m (x4 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Error: ErrImagePull
  Warning  Failed     38m (x7 over 41m)    kubelet, dcg2111.cas.mnbm01.gd-ais.com  Error: ImagePullBackOff
  Normal   BackOff    85s (x158 over 41m)  kubelet, dcg2111.cas.mnbm01.gd-ais.com  Back-off pulling image "nvidia/driver:440.64.00-centos8"
3. Information to attach (optional if deemed irrelevant)
OS
Name        : centos-release
Version     : 8.1
Release     : 1.1911.0.8.el8
Architecture: x86_64
Install Date: Wed 26 Feb 2020 11:29:47 AM CST
Group       : System Environment/Base
Size        : 25430
License     : GPLv2
Signature   : RSA/SHA256, Thu 02 Jan 2020 01:33:42 PM CST, Key ID 05b555b38483c65d
Source RPM  : centos-release-8.1-1.1911.0.8.el8.src.rpm
Build Date  : Thu 02 Jan 2020 09:21:12 AM CST
Build Host  : x86-02.mbox.centos.org
Relocations : (not relocatable)
Packager    : CentOS Buildsys bugs@centos.org
Vendor      : CentOS
Summary     : CentOS Linux release file
Description : CentOS Linux release files

Kubernetes
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by supertetelman** [comment]
CentOS 8 is now supported by the GPU Operator and DeepOps.
