### ISSUE TITLE
ELK Installation/Configuration Issue.

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#638]
Hi Team,

Trying to install/enable the ELK in our environment as per the below link 
https://github.com/NVIDIA/deepops/blob/master/docs/elk.md

But getting  error.
osquery.yml
![image](https://user-images.githubusercontent.com/13992953/90738037-e6776e00-e2eb-11ea-93e9-eae2c8d8e078.png)

Nee your assistance fro resolving the error.

Thank You
Atul Yadav
Locuz

**Comment by wbadart** [comment]
https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/logging.md

Looks like those docs are now here

**Comment by dedysugiarto** [comment]
Dear @wbadart 

there's no osquery.yml in this repos:

Regards,
Dedy

**Comment by wbadart** [comment]
Indeed, there's no more top-level `ansible` directory anymore either. Whatever the original problem was, it now seems to be an issue of outdated docs.
