### ISSUE TITLE
BUG | scheduler | controller-manager |/healthz: dial tcp 127.0.0.1:10251: connect: connection refused

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#650]
Hi Team, 

After deploying the version "20.08.1" Or  "20.08", the scheduler and etc service are unhealthy.
Single Node Deployment 
kubectl get cs
![image](https://user-images.githubusercontent.com/13992953/91589524-72863700-e977-11ea-8bad-b74fbf738973.png)

Error
Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused

kubectl cluster-info dump
[https://gist.github.com/atulyadavtech/b24ca29d28d49fd6775ab030d1e29df3#file-kubectl-cluster-info-dump](url)
Please look into this issue.
Client Version: v1.17.9
Server Version: v1.17.9

Thank You
Atul Yadav
Locuz

**Comment by atulyadavtech** [comment]
Hi Team,

Please find more information on the issue 
[https://github.com/kubernetes/kubeadm/issues/2222](url)

Thank You
Atul Yadav
locuz

**Comment by supertetelman** [comment]
Seems like this issue has been resolved, closing as stale.
