### ISSUE TITLE
Add MOFED to nccl-tests Dockerfile

### ISSUE THREAD

**Issue by avolkov1** [NVIDIA/deepops#652]
The Dockerfile does not install MOFED. When running the container it does not detect infiniband and GDRDMA.
The original dockerfile is:
https://github.com/NVIDIA/deepops/blob/164810cfbe0ea72f16b611c5fd28b6b2cd9ab519/containers/nccl-tests/nccl-tests-cuda11.0-ubuntu18.04/Dockerfile

Container:
https://hub.docker.com/r/deepops/nccl-tests-cuda11.0-ubuntu18.04/tags

To fix the MOFED issue so that the nccl-tests run with GDRDMA I modified the dockerfile. It's attached.

[Dockerfile.nccl-tests-mofed5-cuda11base-deepops.txt](https://github.com/NVIDIA/deepops/files/5151442/Dockerfile.nccl-tests-mofed5-cuda11base-deepops.txt)

**Comment by ajdecon** [comment]
@avolkov1 : Can you please open a PR to add your modified Dockerfile to the repo?

We should probably add this as an alternative Dockerfile (e.g., put it somewhere like `containers/nccl-tests/nccl-tests-cuda11.0-ubuntu18.04-MOFED`), rather than replace the existing file. That way we will have options both with and without MOFED.

**Comment by avolkov1** [comment]
Ok, will do.

FYI, in the examples in deepops nccl-tests with MOFED are always used "deepops/nccl-tests-tf20.06-ubuntu18.04".

https://github.com/NVIDIA/deepops/blob/60adaf7aad69ea2cca4deff06ee83e6e4da7fb33/playbooks/slurm-validation.yml#L5

and

https://github.com/NVIDIA/deepops/blob/94344080d8ff1c3a8700d0bedae4097978e725c3/docs/slurm-perf-cluster.md#L252

I don't think nccl-tests without MOFED are used anywhere at all.

**Comment by joehandzik** [comment]
FWIW, the TF20.06 container was used to ensure parity with something I had been testing outside of Deepops. I agree with @ajdecon - we should make it a separate container. I'm fine with shifting the examples and playbooks to use the new container as well as long as the multinode steps are tested and we hit the target NCCL allreduce performance.

**Comment by joehandzik** [comment]
Also note that our test example works because it relies on Enroot.

**Comment by supertetelman** [comment]
It seems like this has been resolved in the newer CUDA 11 version of the NCCL tests and the original user-demand for this issue no longer exists.
