### ISSUE TITLE
Building a DeepOps cluster offline

### ISSUE THREAD

**Issue by bezero** [NVIDIA/deepops#665]
In offline docs, it says "UNDER CONSTRUCTION". I was wondering when these scripts will be available?

Meanwhile, I tried to run `./scripts/build_offline_cache.sh` it fails at L64 as `HELM_JUPYTER_CHARTS_URL` is not provided.
```
# L64
get_all_helm_tgzs "${HELM_JUPYTER_CHARTS_URL}"
```

**Comment by bezero** [comment]
Are there any updates on this issue?

**Comment by supertetelman** [comment]
Now tracking through https://github.com/NVIDIA/deepops/issues/299.

We are revisiting the official offline support, but this guide is more up to date and should work as a template to follow.
