### ISSUE TITLE
Grafana does not Display GPU Metrics (Ubuntu 18.04, GTX 1060)

### ISSUE THREAD

**Issue by ekaakurniawan** [NVIDIA/deepops#68]
I  tried KONG on my laptop (using Ubuntu 18.04, GTX 1060, 6 GiB) but I cannot get Grafana to display GPU information. CPU, memory and I/O information can be displayed without any issue. Also, the `resnet-gpu-pod` example works fine for me. For the setup, I just use one master node without worker node. For now, this will be the setting for our GPU servers as well.

The link I follow: https://docs.nvidia.com/datacenter/kubernetes/kubernetes-install-guide/index.html

The steps I took in is in this [doc.txt](https://github.com/NVIDIA/deepops/files/2844435/doc.txt) file and node exporter metrics info is in [node_exporter_metrics.txt](https://github.com/NVIDIA/deepops/files/2844439/node_exporter_metrics.txt) file. Following is my Grafana screen shoot.

![grafana](https://user-images.githubusercontent.com/29937520/52469747-e955b680-2bbe-11e9-9d52-4b1d67c79c03.png)

**Comment by ekaakurniawan** [comment]
I discover that my setup does not have following configuration file.
```
/etc/kubeadm/monitoring/kube-prometheus/charts/exporter-node/values.yml
```
Instead, I have the compressed file only.
```
/etc/kubeadm/monitoring/kube-prometheus-0.0.43.tgz
```
Even after I extract the zip file, the config file is `values.yaml` instead of `values.yml`.
```
$ ls
Chart.yaml  templates  values.yaml
```

**Comment by LikeGift** [comment]
Check if all the pods in the namespace monitoring are running and ready. Type the following command:
`kubectl get pods --namespace=monitoring`
It seems dcgm-exporter is not running.

**Comment by ekaakurniawan** [comment]
I think it is the driver issue. Will close for now.
