### ISSUE TITLE
NHC issues

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/deepops#703]
Running the playbook for `slurm-cluster.yaml` leaves my test cluster in a drained state due to issues with the NHS role. Deepops is version 20.10 and there are three nodes (login and two compute nodes). Initially the compute nodes are marked as drained, as there is a bug in the fact gathering script for the gpu count. I have managed to solve that issue.

However, some of the compute nodes are still marked as drained as nhc requires `rpc.statd nfslock` to be running https://github.com/NVIDIA/deepops/blob/26e15d1bd56030cdc97deceb3731915e0cffea5c/roles/nhc/templates/nhc.conf.j2#L20 on all compute nodes. 

I have a nonstandard setup, where one of the compute nodes acts as the nfs server, the others, including the login node, are clients. Since `rpc.statd` is started only on an nfs-server https://github.com/NVIDIA/deepops/blob/26e15d1bd56030cdc97deceb3731915e0cffea5c/roles/nfs/tasks/server.yml#L17 this leaves all my compute nodes, except the one which acts as the nfs server, in a drained state.

Is it possible to programmatically include the check only on the nfs-server?

**Comment by ajdecon** [comment]
This check is actually being removed in #701 which should resolve this issue. :)

Also, please note that you can customize your NHC configuration by specifying a custom config file or template, using the `nhc_config_template` variable.

This is probably something you'll want to do anyway to check for issues specific to your cluster, especially with an unusual setup such as running the NFS server on one of the compute nodes.

**Comment by itzsimpl** [comment]
Got it! Sounds reasonable. Thanks.
