### ISSUE TITLE
Fix k8s GPU device plugin installation

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#710]
Need proper method for installing GPU device plugin with node selectors. Fix for https://github.com/NVIDIA/deepops/pull/700 since it will no longer detect failures in device plugin installation.

**Comment by supertetelman** [comment]
We might just be able to switch the order of GFD/plugin installation. If we install GFD first, we can use the automatically applied annotations as NodeSelectors.

**Comment by supertetelman** [comment]
Addressed here: https://github.com/NVIDIA/deepops/pull/757
