### ISSUE TITLE
Missing libswitch-perl?

### ISSUE THREAD

**Issue by yangatgithub** [NVIDIA/deepops#716]
dgxuser@login01:~$ mpiexec
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /etc/perl /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/mpiexec line 49.
BEGIN failed--compilation aborted at /usr/local/bin/mpiexec line 49.
dgxuser@login01:~$

Saw it in Ubuntu 20.04, solved by adding libswitch-perl

**Comment by dholt** [comment]
That `mpiexec` binary comes from the Slurm contrib. If you need some examples of running MPI jobs, see: https://github.com/NVIDIA/deepops/tree/master/workloads/examples/slurm/mpi-hello
