### ISSUE TITLE
Failed to install the cluster  version 20.10 on centos 7

### ISSUE THREAD

**Issue by jeff-yajun-liu** [NVIDIA/deepops#731]
I have tried twice both on multiple nodes (control node, mgmt01 and gpu) and single - one gpu serer, both failed with following message: 
fatal: [gpu3.local -> localhost]: FAILED! => changed=false
  checksum: 72c3589e31face13aceaad08bdce182597d94265
  msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

**Comment by jeff-yajun-liu** [comment]
also, every time run ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml following message comes up:
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

**Comment by jeff-yajun-liu** [comment]
kubectl_localhost: false -- the problem happened once I changed it to: true. Once I have left it as it was. It works.

**Comment by dholt** [comment]
Reopening so we can take a look
