### ISSUE TITLE
cpupower not available causing slurm epilog failures 

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/deepops#733]
I've come to discover that `linux-tools-generic` in ubuntu 18.04 does not include `cpupower` which is required by the slurm `prolog` and `epilog` scripts. As the `cpupower` command was not installed this lead to non DGX nodes failing after a job finished. The line 
https://github.com/NVIDIA/deepops/blob/e91a0feff99d152af5dd71cc8d72b185e6190ea6/roles/slurm/tasks/prolog_epilog.yml#L6
should be changed either to `- "linux-tools-{{ ansible_kernel }}" ` or `linux-tools-common` (see https://packages.ubuntu.com/search?suite=bionic&arch=any&mode=filename&searchon=contents&keywords=cpupower).

**Comment by ajdecon** [comment]
Hi @itzsimpl : Would you like to [contribute a PR](https://github.com/NVIDIA/deepops/blob/master/CONTRIBUTING.md) for this change? As you appear to have identified the fix, I'd love to let you get the credit for the fix. If not I can look at rolling a PR for this.
