### ISSUE TITLE
deepops k8s namespace

### ISSUE THREAD

**Issue by ryanolson** [NVIDIA/deepops#735]
It might be nice for the components we install via `./scripts/k8s/deploy_*` to use the `deepops_component_name` namespace instead of the `default` namespace.

Just a thought.

**Comment by supertetelman** [comment]
As far as I know, everything except deploy_ingress.sh is already using it's own namespace. Enforcing the name `deepops_*` might be tricky for scripts like `deploy_kubeflow.sh` which is external yml for deployment.

Are you thinking we should rename `monitoring` to `deepops_monitoring`, etc?

**Comment by ryanolson** [comment]
If a project or component already deploys to a namespace, I don't see a need to modify that unless it's easy and safe.  I'm just looking to move things out of `default`.

Add metallb / loadbalancer to the list.

`_` aren't allowed in namespaces, so `deepops-component-name`.

**Comment by supertetelman** [comment]
Along with this we should update the deletion function of the deployment scripts to use this namespace rather than the `default`. I ran into some issues deleting the monitoring stack while using `kubens` and had to add `-a default` to the script..

**Comment by supertetelman** [comment]
PRs are open for ingress and docker registry. Load balancer is fixed. I think that covers everything.

https://github.com/NVIDIA/deepops/pull/841
https://github.com/NVIDIA/deepops/pull/840
