### ISSUE TITLE
kubeflow deletion 

### ISSUE THREAD

**Issue by gpichai** [NVIDIA/deepops#741]
would like to delete the kubeflow deployment as the first installation is giving this error
kubectl get pods --namespace kubeflow
seldon-controller-manager-6d94c47fb-c2sfk   0/1     CrashLoopBackOff   269        24h

[centos@admin k8s]$ sh deploy_kubeflow.sh -d
bash: /home/centos/deepops/scripts/k8s/../../config/kubeflow-install/deepops-delete-kubeflow.sh: No such file or directory
rm: cannot remove ‘/home/centos/deepops/scripts/k8s/../../config/kfctl’: No such file or directory

**Comment by supertetelman** [comment]
Kubeflow is deleted by running `kfctl delete -f CONFIG.yml`.

It looks like your config and kfctl were already deleted.

If you still have components running in K8s, the easiest thing to do would be to attempt to re-install with the script and then delete with the script. I'd recommend putting an `exit 0` on the line before the first `kfctl build` so that it only downloads and I packs everything, not reinstalls it in K8s

**Comment by gpichai** [comment]
I think we dont have permission to access these files, when we do download the repo, this file is not downloaded deepops-delete-kubeflow.sh

**Comment by supertetelman** [comment]
That file is dynamically generated. It essentially just runs the `kfctl` command I described and then deletes local configuration files and some extra K8s namespaces.

**Comment by gpichai** [comment]
Thanks i was able to install it again, looks ok, but I am still having trouble opening the kubeflow inside the browser . Just want to know if  the seldon-controller-manager-6d94c47fb-zlzp4 crash is that an issue?

**Comment by supertetelman** [comment]
Yeah, I noticed that the other day. Something changed/broke in the upstream project and Seldon has been crashing.

This should not have any impact on the overall application however. You should still be able to reach Kubeflow at the URL the script prints out. If you can't hit it with your browser, try simply curling it from the node it is running on to verify there is no firewall issue.

**Comment by gpichai** [comment]
I spent a lot of time opening the kubeflow not successful, but it opens when I just use the cluster IP of the central dashboard. 
I was told from a colleague that there is no firewall, I will find out anyway.  On a different note we are trying this on centos, can you please confirm which OS is preferable.

**Comment by gpichai** [comment]
I tried the same installation in ubuntu with 2 nodes, but I still cannot open the kubeflow, we dont have any firewall , this is what i see in k8s.
istio-system             service/istio-ingressgateway                                NodePort       10.233.30.35    <none>        15020:30494/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31792/TCP,15030:32311/TCP,15031:30293/TCP,15032:32257/TCP,15443:30387/TCP   18h   app=istio-ingressgateway,istio=ingressgateway,release=istio

During install i got this url , 
Kubeflow Dashboard (HTTP NodePort): http://10.1.1.63:31380

Any idea what might be wrong?
I am not able to curl, i get connection refused.
curl 'http://10.1.1.63:31380'
curl: (7) Failed to connect to 10.1.1.63 port 31380: Connection refused

**Comment by supertetelman** [comment]
Are you running that `curl` command from the node that you installed from?

I am going to need a lot more debug information to help here. It sounds like Kubeflow successfully installed and you just are unable to reach the dashboard from your browser. I haven't seen this issue on any of the on-prem/cloud installs lately. I usually run on Ubuntu, but this works on CentOS as well.

Mind providing more debug ... What version DeepOps are you using? How are your nodes set up? Do you have the Grafana dashboard working? Can you share the state of all the pods and svc in the kubeflow/istio namespace? Have you tried installing/re-installing on a fresh K8s deployment? Have you verified that your default storage class is working?

**Comment by gpichai** [comment]
Are you running that curl command from the node that you installed from?

I am going to need a lot more debug information to help here. It sounds like Kubeflow successfully installed 
and you just are unable to reach the dashboard from your browser. I haven't seen this issue on any of the on-prem/cloud installs lately. 
I usually run on Ubuntu, but this works on CentOS as well.

Mind providing more debug ... What version DeepOps are you using? 
How are your nodes set up? 
Do you have the Grafana dashboard working?
 Can you share the state of all the pods and svc in the kubeflow/istio namespace? 
 Have you tried installing/re-installing on a fresh K8s deployment? 
 Have you verified that your default storage class is working?
 
 
 Thank you for response. we just followed the given instructions.
 
#######################################
 I have 2 gpu nodes, 
 a) Node1 -  1 with master and 1 worker
 b) Node2 -  1 worker
 yes kubeflow got installed sucessfully. yes I am unable to reach the dashboard. 
 
 #######################################
   ubuntu@deepops:~/deepops$ git branch
* (HEAD detached at 20.10)
  master
  
#######################################
 #curl from master node
 ubuntu@gpu2:/mnt/data/logs/test$ curl http://10.1.1.63:31380
curl: (7) Failed to connect to 10.1.1.63 port 31380: Connection refused

  
#################node setup##########################  
  #this is our inventory file
  #
# Server Inventory File
#
# Uncomment and change the IP addresses in this file to match your environment
# Define per-group or per-host configuration in group_vars/*.yml

######
# ALL NODES
# NOTE: Use existing hostnames here, DeepOps will configure server hostnames to match these values
######
[all]
gpu2        ansible_host=10.1.1.62
gpu3        ansible_host=10.1.1.63


######
# KUBERNETES
######
[kube-master]
gpu3


# Odd number of nodes required
[etcd]
gpu3


# Also add mgmt/master nodes here if they will run non-control plane jobs
[kube-node]
gpu2
gpu3
[k8s-cluster:children]
kube-master
kube-node

######
# SLURM
######
[slurm-master]
#login01

[slurm-node]
#gpu01
#gpu02
#####################istio-system##################

ubuntu@deepops:~/kubtest$ kubectl get all --all-namespaces | grep istio-system
istio-system             pod/cluster-local-gateway-d7df4cdc8-24b6c                             1/1     Running            0          47h
istio-system             pod/grafana-6875655fd8-2mqht                                          1/1     Running            0          47h
istio-system             pod/istio-citadel-7578b8f8f8-g78fk                                    1/1     Running            0          47h
istio-system             pod/istio-cleanup-secrets-1.1.6-9mnx6                                 0/1     Completed          0          47h
istio-system             pod/istio-egressgateway-594f7cc859-6k4f2                              0/1     Running            57         47h
istio-system             pod/istio-galley-86b744bd79-8rchh                                     1/1     Running            0          47h
istio-system             pod/istio-grafana-post-install-1.1.6-p8fq8                            0/1     Completed          1          47h
istio-system             pod/istio-ingressgateway-5dbccf544-n68nw                              0/1     Running            53         47h
istio-system             pod/istio-pilot-7564c48698-pghb7                                      2/2     Running            0          47h
istio-system             pod/istio-policy-58988894cd-qpvcf                                     2/2     Running            0          47h
istio-system             pod/istio-security-post-install-1.1.6-xcmn6                           0/1     Completed          0          47h
istio-system             pod/istio-sidecar-injector-867f97b975-ctwmf                           1/1     Running            0          47h
istio-system             pod/istio-telemetry-68dddbcd46-8hg6v                                  2/2     Running            0          47h
istio-system             pod/istio-tracing-75fcff7c44-2dpt8                                    1/1     Running            0          47h
istio-system             pod/kiali-79dbdbb6d-dn7zz                                             1/1     Running            0          47h
istio-system             pod/prometheus-5c958dc796-qhqq2                                       1/1     Running            0          47h
istio-system             service/cluster-local-gateway                               ClusterIP      10.233.21.51    <none>        80/TCP,443/TCP,31400/TCP,15011/TCP,8060/TCP,15029/TCP,15030/TCP,15031/TCP,15032/TCP                                                          47h
istio-system             service/grafana                                             ClusterIP      10.233.63.20    <none>        3000/TCP                                                                                                                                     47h
istio-system             service/istio-citadel                                       ClusterIP      10.233.55.34    <none>        8060/TCP,15014/TCP                                                                                                                           47h
istio-system             service/istio-egressgateway                                 ClusterIP      10.233.62.101   <none>        80/TCP,443/TCP,15443/TCP                                                                                                                     47h
istio-system             service/istio-galley                                        ClusterIP      10.233.38.155   <none>        443/TCP,15014/TCP,9901/TCP                                                                                                                   47h
istio-system             service/istio-ingressgateway                                NodePort       10.233.30.35    <none>        15020:30494/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31792/TCP,15030:32311/TCP,15031:30293/TCP,15032:32257/TCP,15443:30387/TCP   47h
istio-system             service/istio-pilot                                         ClusterIP      10.233.25.118   <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       47h
istio-system             service/istio-policy                                        ClusterIP      10.233.62.149   <none>        9091/TCP,15004/TCP,15014/TCP                                                                                                                 47h
istio-system             service/istio-sidecar-injector                              ClusterIP      10.233.0.144    <none>        443/TCP                                                                                                                                      47h
istio-system             service/istio-telemetry                                     ClusterIP      10.233.9.5      <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       47h
istio-system             service/jaeger-agent                                        ClusterIP      None            <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                                   47h
istio-system             service/jaeger-collector                                    ClusterIP      10.233.54.3     <none>        14267/TCP,14268/TCP                                                                                                                          47h
istio-system             service/jaeger-query                                        ClusterIP      10.233.5.164    <none>        16686/TCP                                                                                                                                    47h
istio-system             service/kiali                                               ClusterIP      10.233.51.18    <none>        20001/TCP                                                                                                                                    47h
istio-system             service/prometheus                                          ClusterIP      10.233.63.183   <none>        9090/TCP                                                                                                                                     47h
istio-system             service/tracing                                             ClusterIP      10.233.32.81    <none>        80/TCP                                                                                                                                       47h
istio-system             service/zipkin                                              ClusterIP      10.233.53.119   <none>        9411/TCP                                                                                                                                     47h
istio-system      deployment.apps/cluster-local-gateway                               1/1     1            1           47h
istio-system      deployment.apps/grafana                                             1/1     1            1           47h
istio-system      deployment.apps/istio-citadel                                       1/1     1            1           47h
istio-system      deployment.apps/istio-egressgateway                                 0/1     1            0           47h
istio-system      deployment.apps/istio-galley                                        1/1     1            1           47h
istio-system      deployment.apps/istio-ingressgateway                                0/1     1            0           47h
istio-system      deployment.apps/istio-pilot                                         1/1     1            1           47h
istio-system      deployment.apps/istio-policy                                        1/1     1            1           47h
istio-system      deployment.apps/istio-sidecar-injector                              1/1     1            1           47h
istio-system      deployment.apps/istio-telemetry                                     1/1     1            1           47h
istio-system      deployment.apps/istio-tracing                                       1/1     1            1           47h
istio-system      deployment.apps/kiali                                               1/1     1            1           47h
istio-system      deployment.apps/prometheus                                          1/1     1            1           47h
istio-system      replicaset.apps/cluster-local-gateway-d7df4cdc8                                1         1         1       47h
istio-system      replicaset.apps/grafana-6875655fd8                                             1         1         1       47h
istio-system      replicaset.apps/istio-citadel-7578b8f8f8                                       1         1         1       47h
istio-system      replicaset.apps/istio-egressgateway-594f7cc859                                 1         1         0       47h
istio-system      replicaset.apps/istio-galley-86b744bd79                                        1         1         1       47h
istio-system      replicaset.apps/istio-ingressgateway-5dbccf544                                 1         1         0       47h
istio-system      replicaset.apps/istio-pilot-7564c48698                                         1         1         1       47h
istio-system      replicaset.apps/istio-policy-58988894cd                                        1         1         1       47h
istio-system      replicaset.apps/istio-sidecar-injector-867f97b975                              1         1         1       47h
istio-system      replicaset.apps/istio-telemetry-68dddbcd46                                     1         1         1       47h
istio-system      replicaset.apps/istio-tracing-75fcff7c44                                       1         1         1       47h
istio-system      replicaset.apps/kiali-79dbdbb6d                                                1         1         1       47h
istio-system      replicaset.apps/prometheus-5c958dc796                                          1         1         1       47h
istio-system      horizontalpodautoscaler.autoscaling/cluster-local-gateway   Deployment/cluster-local-gateway   <unknown>/80%    1         5         1          47h
istio-system      horizontalpodautoscaler.autoscaling/istio-egressgateway     Deployment/istio-egressgateway     <unknown>/80%    1         5         1          47h
istio-system      horizontalpodautoscaler.autoscaling/istio-ingressgateway    Deployment/istio-ingressgateway    <unknown>/80%    1         5         1          47h
istio-system      horizontalpodautoscaler.autoscaling/istio-pilot             Deployment/istio-pilot             <unknown>/80%    1         5         1          47h
istio-system      horizontalpodautoscaler.autoscaling/istio-policy            Deployment/istio-policy            <unknown>/80%    1         5         1          47h
istio-system      horizontalpodautoscaler.autoscaling/istio-telemetry         Deployment/istio-telemetry         <unknown>/80%    1         5         1          47h
istio-system   job.batch/istio-cleanup-secrets-1.1.6         1/1           20s        47h
istio-system   job.batch/istio-grafana-post-install-1.1.6    1/1           26s        47h
istio-system   job.batch/istio-security-post-install-1.1.6   1/1           25s        47h

###############################
Icannot curl graphana
ubuntu@deepops:~/kubtest$ curl 'http://10.1.1.63:30200'
curl: (7) Failed to connect to 10.1.1.63 port 30200: Connection refused

#####################################
I think nothing under istio is reachable.
 yes I can redeploy k8s later not a problem, as I am trying to deploy a job in kubeflow
I can create a mnist job using kubeflow. I had to create the pv and the pvc. it wasn't working
fully with dynamic pvc. I create the pv with the mount path then my job passed. 
###############################

Thank you

**Comment by gpichai** [comment]
we are redeploying we noticed this error during deployment of kubeflow "validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0038] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout972173967": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:266"
WARN[0038] Will retry in 18 seconds.                     filename="kustomize/kustomize.go:267"
namespace/cert-manager unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
"

**Comment by supertetelman** [comment]
If it isn't causing problems I would just ignore that. It could just be a timing issue. If you're having issues it might be a recent breaking change in Kubeflow and I would check the issues list on their GitHub.

Were you able to connect this time?

**Comment by gpichai** [comment]
No even  now we have the same problem, at the moment we are not doing anything from the UI so its ok, you are right this time kubeflow fixed the seldon issue, but some other related pod failing. we are good for now. I will update you later for other issues, but so far we are good. thank you.

**Comment by supertetelman** [comment]
Okay, that sounds good. Thank you for keep me posted. I'll close this issue for now, feel free to open it back up or open a new one if you encounter new issues.
