### ISSUE TITLE
DeepOps desktop error with OpenOnDemand

### ISSUE THREAD

**Issue by miketice22** [NVIDIA/deepops#752]
When trying to launch the DeepOps Desktop, I get the following error:

'undefined local variable or method `bc_num_gpus' for #<BatchConnect::SessionContext:0x00000000045435b8>'

I tried to check the session data output in the link it advertised, but nothing was there.

**Comment by miketice22** [comment]
# rpm -qa | grep ondemand
ondemand-nginx-1.17.3-6.p6.0.4.el7.x86_64
ondemand-python-1.8-1.el7.x86_64
ondemand-passenger-6.0.4-6.el7.x86_64
ondemand-1.8.12-1.el7.x86_64
ondemand-nodejs-1.8-1.el7.x86_64
ondemand-apache-1.8-1.el7.x86_64
ondemand-rubygem-bundler-1.17.3-1.el7.noarch
ondemand-release-web-1.8-1.noarch
ondemand-runtime-1.8-1.el7.x86_64
ondemand-gems-1.8.12-1.8.12-1.el7.x86_64
ondemand-dex-2.24.0-8.el7.x86_64
ondemand-ruby-1.8-1.el7.x86_64

**Comment by miketice22** [comment]
solved by adding 
bc_num_gpus to /var/www/ood/apps/sys/bc_desktop/form.yml

**Comment by dholt** [comment]
That variable already exists in the template: https://github.com/NVIDIA/deepops/blob/e4eb01b2abf8ba085cacf7cdc906633c6809f3ef/roles/ood-wrapper/templates/desktop-form.yml.j2#L15

My guess is you can fix the issue in the future by re-running the ansible playbook. I would highly suggest making changes in ansible vs modifying these files by hand.
