### ISSUE TITLE
DeepOps desktop stuck in 'Queued' status

### ISSUE THREAD

**Issue by miketice22** [NVIDIA/deepops#753]
When launching the DeepOps desktop from OpenOnDemand, it stays in the 'queued' state. Are there logs that can help diagnose why?

**Comment by ajdecon** [comment]
The best way to diagnose this is probably at the Slurm level.

- Running "squeue" will show you the list of jobs. Any jobs that are queued should include a reason, such as "Resources" or "Priority".

- Running "scontrol show job $jobid" (with your job's id) will provide more detail about its status

- The logs of the Slurm controller (usually in /var/log/slurm/slurmctld.log) may also provide insight.

For more detail on how to use Slurm itself, I can recommend the Slurm docs at https://slurm.schedmd.com/

**Comment by dholt** [comment]
You can also get help for OOD from their help forum: https://discourse.osc.edu/c/open-ondemand/5
