### ISSUE TITLE
installtion in Ubuntu 20.04

### ISSUE THREAD

**Issue by pankajsahtech** [NVIDIA/deepops#761]
Hi Team,

Can anyone tested deepops with Ubuntu 20.04 release.
#########
root@masterserver:~/deepops# ./scripts/setup.sh
grep: /root/deepops/scripts/proxy.sh: No such file or directory
Updating apt cache...
Installing pip...
E: Unable to locate package python-pip
./scripts/setup.sh: line 160: pip: command not found
Installing setuptools...

**Comment by ajdecon** [comment]
Ubuntu 20.04 support was added in PR #708 , but that was added after the 20.10 release. You can try running from the master branch, otherwise this should be present in the next DeepOps release.
