### ISSUE TITLE
K8s deployment: could not lock config file

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#770]
starting from freshly installed DGX station, the following issue occurs (deployment node is one of these two nodes where k8s is to be installed) 
```
fatal: [dgx-wurselen-1 -> localhost]: FAILED! => changed=true
  cmd:
  - git
  - submodule
  - update
  - --init
  delta: '0:00:00.056536'
  end: '2020-11-27 14:08:03.816795'
  msg: non-zero return code
  rc: 1
  start: '2020-11-27 14:08:03.760259'
  stderr: |-
    error: could not lock config file /home/saelab/deepops/.git/modules/packer-maas/config: File exists
    fatal: could not set 'core.worktree' to '../../../submodules/packer-maas'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

```

Rename /home/saelab/deepops/.git/modules/packer-maas/config solves the issue.

**Comment by supertetelman** [comment]
This looks like it was releated to a bug that was introduced and fixed around the git submodules. Marking this as closed as it was likely a related issue.
