### ISSUE TITLE
nccl-tests container can't use Soft-RoCE interfaces

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/deepops#772]
For reasons not completely known to me the container used for SLURM validation ("deepops/nccl-tests-tf20.06-ubuntu18.04:latest") can't use Soft-RoCE interfaces. I configured Soft-RoCE on 2 CentOS 7 SLURM worker nodes with NVIDIA vGPU according to https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configuring_soft-_roce and can successfully execute ibv_rc_pingpong. Nevertheless the all_reduce_perf test in playbooks/slurm-cluster/slurm-validation.yml can only use TCP MPI transports and executing "ucx_info -d" from the container with srun doesn't show any IB/RoCE interfaces. I used all combinations of NCCL_IB_HCA, NCCL_IB_GID_INDEX, UCX_NET_DEVICES, UCX_IB_GID_INDEX.

I would like to use the described setup as test environment for an upcoming DGX A100 cluster. Thank you.

**Comment by supertetelman** [comment]
Were you able to get past this issue?

**Comment by mathrock74** [comment]
I didn't get past this with CentOS 7 Slurm nodes. In the meantime I switched to deepops 20.12 with Ubuntu 20.04. I haven't tried it there yet, the new way of configuring Soft-RoCE interfaces (rdma-link) scared me off (and I'm short of time). I'll try it ASAP. I'm also waiting for https://github.com/NVIDIA/deepops/issues/785

**Comment by mathrock74** [comment]
Setting up Soft-RoCE interfaces in Ubuntu 20.04 was no big deal, ibv_rc_pingpong works between my two Slurm nodes.
Still I get fatal errors when running 

`srun -N 2 -G 2 --ntasks-per-node=1 --mpi=pmix --exclusive --container-image=${HOME}/deepops+nccl-tests-tf20.06-ubuntu18.04+latest.sqsh all_reduce_perf -b 64 -e 1G -f 2 -g 1`

after setting

`export OMPI_MCA_pml=ucx
 export UCX_NET_DEVICES=rxe0
 export NCCL_IB_HCA=rxe0`

Also running "ucx_info -d" from the container shows now signs of the rxe0 interfaces.
My RDMA knowledge is very limited, I don't know if my setup is _supposed_ to work, I'm glad for any advice.

**Comment by mathrock74** [comment]
I now have DGX A100 machines with IB interconnect, so I don't need RoCE anymore. The need to update the container used for validation has been mentioned elsewhere so I'm closing this report
