### ISSUE TITLE
submodules/kubespray/scale.yml does not set default runtime to nvidia

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#774]
A DGX customer tried to include a newer DGX with the scale.yml according to: 

> ansible-playbook -l k8s-cluster submodules/kubespray/scale.yml

This did not work for the GPU plugins because the default runtime was not set to "nvidia-container-toolkit" by default. 
An upgrade to the documentation is much appreciated.

**Comment by supertetelman** [comment]
This is an artifact of DGX being pre-configured and DeepOps not mucking with the configuration. I believe it should be addressed by this PR: https://github.com/NVIDIA/deepops/pull/758
