### ISSUE TITLE
Document URLs to be whitelisted for deployment

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#777]
A customer has complained about urls not being able to access after deployment of the SLURM cluster: 

time="2020-12-02T00:01:05.190137874Z" level=warning ms g="Error getting v2 registry: Get https://quay.io/v2/: dial tcp
3.223.165.103:443: connect:

COMMAND  PID USER   FD   TYPE   DEVICESIZE/OFF NODE NAME
dockerd 1240 root   21u  IPv4 41136619      0t0  TCP
xxxxxx->ec2-107-23-149-57.compute-1.amazonaws.com:https
(SYN_SENT)

We need to document a list of URLs to be whitelisted in order to use DeepOps.

**Comment by ajdecon** [comment]
@twittidai : It's going to be difficult or impossible to document a stable list of URLs to whitelist. Most container registries and package repositories will rotate through a bunch of different cloud VMs or CDN URLs over time, and tracking their individual hostnames would be a constant challenge.

In the example you gave, we're pulling a container from quay.io and it's redirecting to a particular EC2 instance (ec2-107-23-149-57.compute-1.amazonaws.com). But the next time it could easily be a totally different EC2 instance! 

The right solution, if they don't want to allow general Internet access, would be to create local mirrors for their deployment. That's something we have on our list to support and document, but I don't think we have an ETA yet.

**Comment by twittidai** [comment]
Thanks @ajdecon  - so in the mean time it's a good idea to use something like this?
https://docs.openshift.com/container-platform/4.2/installing/install_config/configuring-firewall.html
(Without the openshift part)  -  and allows to all gcp and aws platforms?

**Comment by ajdecon** [comment]
Yes, that looks like a reasonable list to me! With the addition of NGC
