### ISSUE TITLE
Deploy SLURM results in a brocken docker

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#783]
After deployment with SLURM, the docker daemon has a erroneous DNS override option, so that any docker container running requesting network on both slurm-controller and slurm-nodes will not work. 

These files are located at: 
```
saelab@slurm-compute:/etc/systemd/system/docker.service.d$ ls
docker-dns.conf  docker-options.conf
```

The content of docker-dns.conf:
```
saelab@slurm-compute:/etc/systemd/system/docker.service.d$ cat docker-dns.conf
[Service]
Environment="DOCKER_DNS_OPTIONS=\
    --dns 10.233.0.3 --dns 127.0.0.53  \
    --dns-search default.svc.cluster.local --dns-search svc.cluster.local --dns-search fritz.box  \
    --dns-opt ndots:2 --dns-opt timeout:2 --dns-opt attempts:2  \
```

The options are pulled in with using Kubespray as "bootstraper":
`https://github.com/kubernetes-sigs/kubespray/blob/cc5303e1c8207253c3cc229e63b861fd06b9661e/roles/container-engine/docker/templates/docker-dns.conf.j2`:
```
[Service]
Environment="DOCKER_DNS_OPTIONS=\
    {% for d in docker_dns_servers %}--dns {{ d }} {% endfor %} \
    {% for d in docker_dns_search_domains %}--dns-search {{ d }} {% endfor %} \
    {% for o in docker_dns_options %}--dns-opt {{ o }} {% endfor %} \
"
```

The WAR is to delete this file "docker-dns.conf", and then run:
```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by DarFig** [comment]
I have had the same problem. I have tried what you mention of deleting "docker-dns.conf" and restarting services and it has worked.

As I understand it, the setting that points to "127.0.0.53" is the one used by default with "Ubuntu's netplan" and causes a conflict.

thanks for the help

**Comment by twittidai** [comment]
> I have had the same problem. I have tried what you mention of deleting "docker-dns.conf" and restarting services and it has worked.
> 
> As I understand it, the setting that points to "127.0.0.53" is the one used by default with "Ubuntu's netplan" and causes a conflict.
> 
> thanks for the help

The issue is the 10.233.0.3 entry , which does not exist on the SLURM deployment

**Comment by DarFig** [comment]
> 
> 
> > I have had the same problem. I have tried what you mention of deleting "docker-dns.conf" and restarting services and it has worked.
> > As I understand it, the setting that points to "127.0.0.53" is the one used by default with "Ubuntu's netplan" and causes a conflict.
> > thanks for the help
> 
> The issue is the 10.233.0.3 entry , which does not exist on the SLURM deployment

perfect, thank you very much for the explication.

**Comment by michaelfuckner** [comment]
that's why I prefer dns_mode: none in config.example/group_vars/slurm-cluster.yml
