### ISSUE TITLE
Deploy SLURM with latest DGX OS 5 on DGX-1 is not working

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#822]
This line:
`cuda_dgx_1_version: "cuda-toolkit-10-1"`
need to changed to cuda-toolkit-11-0, as the repository don't have the 10-1 any more. Same for DGX-2
![image](https://user-images.githubusercontent.com/4092787/104336187-6f3db300-54f4-11eb-95a2-0df624d58461.png)

[This line:](https://github.com/NVIDIA/deepops/blob/77da3cc90f5de441e9465c8339baf8b88210387e/roles/nvidia-cuda/defaults/main.yml#L6)

**Comment by arnoldas500** [comment]
Any solution to this yet? Trying to install slurm to system with Ubuntu 20.04 and CUDA 11.0 but latest CUDA version in slurm-cluster.yml is still CUDA 10

**Comment by supertetelman** [comment]
This has been resolved.
