### ISSUE TITLE
Checks may fail due to bug in old ansible version

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#823]
![image](https://user-images.githubusercontent.com/4092787/104352466-027fe400-5507-11eb-9d42-b249b38a1713.png)
![image](https://user-images.githubusercontent.com/4092787/104352534-13305a00-5507-11eb-9014-ebf423859174.png)
![image](https://user-images.githubusercontent.com/4092787/104352566-1e838580-5507-11eb-868d-92f3425415cc.png)

On certain head node, the service state cannot be detected due to [bug in Ansible](https://github.com/ansible/ansible/issues/71528). 

Workaround is to install the latest ansible (i.e., 2.10) manually. 

== System info ===
This was reproduced on a VM with ubuntu20.04.1 and current master from the this repository.

**Comment by ajdecon** [comment]
Closing. This is now fixed in the Ansible version used by DeepOps by default (2.9.21)
