### ISSUE TITLE
Airgap scripts broken after reorganizing scripts

### ISSUE THREAD

**Issue by fredrikand** [NVIDIA/deepops#825]
In this commit scripts was reorganized. This left scripts/airgap/build_offline_cache.sh broken since it references scripts/k8s_inventory.sh, that was removed.

commit e16a62b5aae0fa72e19dadcef8a7a0970866508c
Author: Douglas Holt <dholt@nvidia.com>
Date:   Wed Sep 2 14:53:33 2020 -0700

    re-org scripts dir

**Comment by fredrikand** [comment]
@dholt do you have an idea on how this can be best fixed?

**Comment by DLdvcs** [comment]
Hello, I am also suffering from the same problem. Looks like all of the air-gapped instructions and scripts were for version 20.08. Tried running instructions using the 20.12 branch and most commands fail.
