### ISSUE TITLE
Docker registry mirror deployment result in erroneous docker-options.conf

### ISSUE THREAD

**Issue by twittidai** [NVIDIA/deepops#832]
![image](https://user-images.githubusercontent.com/4092787/104932516-0056d300-59a8-11eb-9459-282da8776b01.png)

See image attached.
The fix is to delete the :5000 and http://:5000 in the option file

**Comment by aslam-mulkin** [comment]
Encounter the same problem with 20.12 with multiple master kubernetes deployment

Fix it by change the Container registry in config/group_vars/k8s-cluster.yml
from (.*) to (.+)

Previous:
`kube_enable_container_registry: true
docker_insecure_registries: "{{ groups['kube-master']|map('regex_replace', '(.*)', '\\1:5000')|list + ['registry.local:31500']}}"
docker_registry_mirrors: "{{ groups['kube-master'] | map('regex_replace', '(.*)', 'http://\\1:5000') | list }}"`

Fix:
`kube_enable_container_registry: true
docker_insecure_registries: "{{ groups['kube-master']|map('regex_replace', '(.+)', '\\1:5000') | list + ['registry.local:31500']}}"
docker_registry_mirrors: "{{ groups['kube-master'] | map('regex_replace', '(.+)', 'http://\\1:5000') | list }}"`
