### ISSUE TITLE
Docker Hub rate limits

### ISSUE THREAD

**Issue by crd477** [NVIDIA/deepops#852]
In November 2020, Docker Hub instituted [rate limiting for anonymous users](https://www.docker.com/increase-rate-limit).  I just got burned by this in my own cluster.

A workaround is to configure the local registry to act as a [pull through cache](https://docs.docker.com/registry/recipes/mirror/).

I think it would worthwhile to consider implementing this behavior, at least as an option if not by default.  It might be in scope for #840.

**Comment by ajdecon** [comment]
We actually have two options included for registry caching already 😄 

1. [Docker registry as pull through cache](https://github.com/NVIDIA/deepops/tree/master/roles/standalone-container-registry). This is enabled for both k8s and Slurm by default in the latest release, controlled by the `standalone_container_registry_cache_enable` var.
2. We also have an optional, alternative [NGINX-based container cache](https://github.com/NVIDIA/deepops/tree/master/roles/nginx-docker-registry-cache). This has the advantage that it can cache more than just Docker Hub, but has some additional deployment wrinkles so we don't enable by default. The NGINX cache is [documented here](https://github.com/NVIDIA/deepops/blob/master/docs/container/nginx-docker-cache.md).

I'm going to close this for now, but please let us know if you run into issues with either of these!

**Comment by crd477** [comment]
Sorry for not noticing those options - I failed to look in the right place!  I actually wound up installing my local registry outside of DeepOps due to #738 at installation time.  I should probably revisit that choice.

Again, sorry for the noise...

**Comment by ajdecon** [comment]
No worries!

And installing outside of DeepOps is totally a valid choice -- I know of others who are using solutions like Artifactory or Nexus for their registries and have good reasons to keep them separate.

If you do decide to keep the registry external to the DeepOps cluster, you can specify its usage using the [docker_registry_mirrors and docker_insecure_registries](https://github.com/NVIDIA/deepops/blob/master/config.example/group_vars/all.yml#L280) vars. (Which are actually just Kubespray vars that we pass through)
