### ISSUE TITLE
msg: No package matching 'cuda-toolkit-10-1' is available 

### ISSUE THREAD

**Issue by arnoldas500** [NVIDIA/deepops#854]
When trying to install SLURM to latest version of DGX-1 with ubuntu 20.04 and cuda 11-0 getting error "msg: No package matching 'cuda-toolkit-10-1' is available". K8s cuda and DGX node cuda version is 11-0. The slurm-cluster.yml file needs to be updated in the latest version of deepops.

**Comment by dholt** [comment]
You might need to update your configuration to pull in any changes, the default in 20.12 is CUDA 11.0: https://github.com/NVIDIA/deepops/blob/3a7c7f01fb7b06e1f5a5c295f1240503f8248d21/config.example/group_vars/all.yml#L111

**Comment by arnoldas500** [comment]
Found the issue, updating group_vars/all.yml will not install the correct cuda version during install for slurm. Need to also update it in deepops/roles/nvidia-cuda/defaults/main.yml from cuda_dgx_1_version: "cuda-toolkit-10-1"  to cuda_dgx_1_version: "cuda-toolkit-11-0". You  can also do cuda_dgx_override_version: "{{ cuda_version }}" in the same file but I have not personally tried it.
