### ISSUE TITLE
docker.socket: Failed with result 'service-start-limit-hit' || Deepops 20.12

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#857]
Hi Team,

Deepops installation is failing due to the docker service issue.

Environment 
Ubuntu 20.04.1 LTS
Deepops 20.12
Docker version 19.03.12, build 48a66213fe
Single Server 
Error Docker Service Fail
server11                   : ok=82   changed=10   unreachable=0    failed=1    skipped=67   rescued=1    ignored=1

Failed to start Docker Application Container Engine
docker.socket: Failed with result 'service-start-limit-hit'

Thank You
Atul Yadav

**Comment by atulyadavtech** [comment]
Found the Solution.
After debugging understood the error.
journalctl -n 5000 -xu docker.service

Updated the file 
"config/group_vars/k8s-cluster.yml"
From  
docker_insecure_registries: "{{ groups['kube-master']|map('regex_replace', '(.*)', '\\1:5000')|list + ['registry.local:31500']}}"
docker_registry_mirrors: "{{ groups['kube-master'] | map('regex_replace', '(.*)', 'http://\\1:5000') | list }}"
To 
docker_insecure_registries: "{{ groups['kube-master']|map('regex_replace', '^(.*)$', '\\1:5000')|list + ['registry.local:31500']}}"
docker_registry_mirrors: "{{ groups['kube-master'] | map('regex_replace', '^(.*)$', 'http://\\1:5000') | list }}"

Closed

**Comment by dholt** [comment]
I believe this was fixed in #818
