### ISSUE TITLE
kubeflow.error Code 400 with message:||  20.12

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/deepops#858]
Hi Team,

Need your assistance in resolving the below error.

Environment

> Ubuntu 20.04.1 LTS
> Deepops 20.12
> Docker version 19.03.12, build 48a66213fe
> Single Server

![image](https://user-images.githubusercontent.com/13992953/106907477-4b047900-6724-11eb-9a59-f657b66ecd25.png)

Thank YOu
Atul Yadav

**Comment by supertetelman** [comment]
Please use the Kubeflow deployment script in the master branch of DeepOps. It looks like this deployment is hitting a bug where the URI is pointing to github.com instead of raw.github.com. It should be possible to just replace the URL string, but I'd recommend always just using the latest script.
