### ISSUE TITLE
Cannot utilize more than the maximum GPUs in a node

### ISSUE THREAD

**Issue by kmmanto** [NVIDIA/deepops#87]
Environment:

4 DGX Stations with 4 GPUs each

How can we do the setup so that we can request for more than 4GPUs (say 8) in a pod request.

**Comment by ryanolson** [comment]
Pods are a collection of containers that can only that are run on a node.  By definition, a Pod can not span more than 1 node.

Multi-node jobs are possible, but they require some level of coordination of multiple Pods scheduled to different nodes to work in conjunction with each other.   One example would be the [Kubeflow MPI operator](https://github.com/kubeflow/mpi-operator).
