### ISSUE TITLE
hvhpc package no longer available? 

### ISSUE THREAD

**Issue by jeff-yajun-liu** [NVIDIA/deepops#880]
TASK [nvidia-hpc-sdk : download nvidia hpc sdk] **********************************************************************************************************
fatal: [k-gpu4]: FAILED! => changed=false
  dest: /tmp/hpc-sdk-install/nvhpc.tar.gz
  elapsed: 0
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  status_code: 404
  url: https://developer.download.nvidia.com/hpc-sdk/nvhpc_2020_207_Linux_x86_64_cuda_11.0.tar.gz

**Comment by jeremyfix** [comment]
Hi, this release does not seem to be available anymore  as well as the one mentioned in #806 

Following these URLs, today, points to 404 error as you mention. 

A valid URL, today, is [https://developer.download.nvidia.com/hpc-sdk/21.3/nvhpc_2021_213_Linux_x86_64_cuda_11.2.tar.gz](https://developer.download.nvidia.com/hpc-sdk/21.3/nvhpc_2021_213_Linux_x86_64_cuda_11.2.tar.gz)

**Comment by jeremyfix** [comment]
actually, the URL is hardcoded in `config.example/group_vars/slurm-cluster.yml`, `virtual/config/group_vars/slurm-cluster.yml` and possibly `config/group_vars/slurm-cluster.yml` which was used to fix #896 but therefore shortcuts the version definition with the `hpcsdk_*` variables.

**Comment by ajdecon** [comment]
Fixed in #931
