### ISSUE TITLE
executing  ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/deepops#889]
TASK [../../submodules/kubespray/roles/container-engine/docker : ensure docker-ce repository is enabled] *****************************************************
failed: [dgxn34-cn] (item=deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
) => changed=false
  ansible_loop_var: item
  item: |-
    deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  msg: apt cache update failed

PLAY RECAP ***************************************************************************************************************************************************
dgxn34-cn                  : ok=67   changed=3    unreachable=0    failed=1    skipped=53   rescued=0    ignored=1

**Comment by dholt** [comment]
You might try running `sudo apt cache update` on the failed machine and debug from there

**Comment by abhisheks1460** [comment]
While executing sudo apt cache update getting this error

E: Invalid operation cache

**Comment by dholt** [comment]
sorry, `sudo apt update`
