### ISSUE TITLE
MIG Slurm support

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [NVIDIA/deepops#894]
Hello,

The gres file https://github.com/NVIDIA/deepops/blob/5a29ea35aa81d766c7b0be32c1a6ef2c5a361468/roles/slurm/templates/etc/slurm/gres.conf seem to use physical files to declare available GPUs. How do it with MIG compute units?

Thank you!

**Comment by ajdecon** [comment]
Slurm currently does not support MIG (yet!)

Once Slurm support exists, we'll update DeepOps to configure it when needed.

**Comment by GuillaumeLeclerc** [comment]
Do you have any insights when this will be available. I see no answers on issues on slurm bug tracker.  We were convinced by NVIDIA sales rep to go for 45xA100 instead of RTX4000 and now we can't deploy them...

In the meantime I was trying to hack a solution where I create an empty file for each MIG compute unit and then create a non-gpu `gres` for each. It works fine for allocation purposes but I can't seem to find a way for the job to know which file was allocated in order to generate the proper `CUDA_VISIBLE_DEVICES` accordingly.
