### ISSUE TITLE
NVIDIA HPC SDK 21.2 has a different download URL

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#896]
The NVIDIA HPC SDK 21.2 uses a slightly different URL scheme for its downloads. The correct URL for this release is `https://developer.download.nvidia.com/hpc-sdk/21.2t/nvhpc_2021_212_Linux_x86_64_cuda_11.2.tar.gz` (note the `21.2t`).

This doesn't match the [calculated version scheme](https://github.com/NVIDIA/deepops/blob/release-20.12/roles/nvidia-hpc-sdk/defaults/main.yml#L43) that we use to determine the download URL from the version number.

**Comment by zyndagj** [comment]
The "t" was removed from the download url and is now

```
https://developer.download.nvidia.com/hpc-sdk/21.2/nvhpc_2021_212_Linux_x86_64_cuda_11.2.tar.gz
```

https://developer.nvidia.com/nvidia-hpc-sdk-212-downloads

**Comment by ajdecon** [comment]
Fixed in https://github.com/NVIDIA/deepops/commit/b3a4f86174b56186c178358a44b561e8eb4fc14b
