### ISSUE TITLE
when running the ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml 

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/deepops#904]
TASK [../../submodules/kubespray/roles/container-engine/docker : ensure docker-ce repository is enabled] *****************************************************
task path: /root/deepops/submodules/kubespray/roles/container-engine/docker/tasks/main.yml:79
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/packaging/os/apt_repository.py
Pipelining is enabled.
<172.50.0.34> ESTABLISH SSH CONNECTION FOR USER: None
<172.50.0.34> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' 172.50.0.34 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dqybxhwvbtozwnowfkkdqgzsrgztgjkd ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<172.50.0.34> (1, b'\n{"msg": "apt cache update failed", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_apt_repository_payload_LVh2eL/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py\\", line 548, in main\\n  File \\"/usr/lib/python2.7/dist-packages/apt/cache.py\\", line 586, in update\\n    raise FetchFailedException(e)\\n", "invocation": {"module_args": {"install_python_apt": true, "filename": null, "repo": "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable\\n", "state": "present", "update_cache": true, "mode": null, "codename": null, "validate_certs": true}}}\n', b'')
<172.50.0.34> Failed to connect to the host via ssh:
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_repository_payload_LVh2eL/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 586, in update
    raise FetchFailedException(e)
failed: [dgxn34-cn] (item=deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
) => changed=false
  ansible_loop_var: item
  invocation:
    module_args:
      codename: null
      filename: null
      install_python_apt: true
      mode: null
      repo: |-
        deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: true
      validate_certs: true
  item: |-
    deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  msg: apt cache update failed

PLAY RECAP ***************************************************************************************************************************************************
dgxn34-cn                  : ok=67   changed=3    unreachable=0    failed=1    skipped=53   rescued=0    ignored=1

**Comment by abhisheks1460** [comment]
If we execute apt cache update 
E: Invalid operation cache

**Comment by ajdecon** [comment]
Ansible's error message isn't great here, but try executing the following on the target hosts:

```
sudo apt-get update
```

If that works, try the playbook again! If not, you may have an Internet connectivity error which needs to be fixed before you can run the playbook.

**Comment by abhisheks1460** [comment]
issue resolved ,it was proxy issue ...
