### ISSUE TITLE
-bash ansible permission denied

### ISSUE THREAD

**Issue by danltw** [NVIDIA/deepops#908]
I am trying to configure my DGX V100 using SLURM.

After configuring using vi config/inventory and editting the SLURM portion, I run the ansible -m ..... command as shown in the readme. However, I get the error: `-bash: /usr/local/bin/ansible: Permission Denied`

It also seems like I do not have the path when I try to change into that directory.

**Comment by ajdecon** [comment]
Here are a few things to try:

- If you haven't already, make sure to run `scripts/setup.sh` from DeepOps to set up its dependencies
- Try closing your shell and opening a new session before attempting to run the Ansible command
- Check to make sure that Ansible is in your path by running `which ansible`

**Comment by danltw** [comment]
> Here are a few things to try:
> 
> * If you haven't already, make sure to run `scripts/setup.sh` from DeepOps to set up its dependencies
> * Try closing your shell and opening a new session before attempting to run the Ansible command
> * Check to make sure that Ansible is in your path by running `which ansible`

`which ansible` returns empty. I also did a `pip3 install ansible` which says it is already installed
