### ISSUE TITLE
prolog and epilog issue when trying to run any slurm job

### ISSUE THREAD

**Issue by harryfwong** [NVIDIA/deepops#919]
When I try to run a slurm batch job all things fail to start.  I followed the steps of running the ansible slurm validation script and it fails too.  All jobs fail and nodes go into the DRAIN mode.  

The prolog-epilog log shows
++ sudo -u root sh -c 'echo "/run/enroot/user-$(id -u)"'
sudo: sh: command not found
+ runtime_path=

After debugging I modified the sh command in the following epilog/prolog scripts

/etc/slurm/epilog.d/50-lastuserjob-all-enroot-dirs
replaced all 'sh -c' with '/usr/bin/sh -c'

/etc/slurm/prolog.d/50-all-enroot-dirs
replaced all 'sh -c' with '/usr/bin/sh -c'

Now slurm jobs and ansible-playbook -l slurm-cluster playbooks/slurm-cluster/slurm-validation.yml -e '{num_gpus: 2}' complete.

**Comment by harryfwong** [comment]
I am running Ubuntu 18/20 servers

**Comment by harryfwong** [comment]
I also made changes 
deepops/roles/slurm/templates/etc/slurm/epilog.d/50-lastuserjob-all-enroot-dirs
deepops/roles/slurm/templates/etc/slurm/prolog.d/50-all-enroot-dirs

**Comment by ajdecon** [comment]
Thanks for reporting this!

Generally, in the Slurm prolog/epilog context, we do expect the `PATH` to include most common binary directories (e.g., `/usr/bin`, `/bin`, etc.).

We haven't seen this issue before on vanilla Ubuntu installs, so I suspect there's something unusual about your configuration that is impacting the environment variables being set for your prolog and epilog scripts. 

If you want to debug this further, you may want to try a few things:

1. Check `/etc/sysconfig/slurmd` which sets up the environment that slurmd runs in
2. Check `/etc/profile` to see if it's doing something weird with `PATH`
3. Add a command to one of the prolog scripts to dump the environment to a file, to understand what `PATH` is being set

----

All of that said, using absolute paths in these scripts is not a bad idea! If you'd like to submit a PR changing `sh` to `/usr/bin/sh` in these scripts, I'd be happy to test and review.

**Comment by harryfwong** [comment]
/etc/sysconfig/slurmd
  PMIX_MCA_ptl=^usock
  PMIX_MCA_psec=none
  PMIX_SYSTEM_TMPDIR=/var/empty
  PMIX_MCA_gds=hash

/etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).
  if [ "${PS1-}" ]; then
    if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
      # The file bash.bashrc already sets the default PS1.
      # PS1='\h:\w\$ '
      if [ -f /etc/bash.bashrc ]; then
        . /etc/bash.bashrc
      fi
    else
      if [ "`id -u`" -eq 0 ]; then
        PS1='# '
      else
        PS1='$ '
      fi
    fi
  fi
  
  if [ -d /etc/profile.d ]; then
    for i in /etc/profile.d/*.sh; do
      if [ -r $i ]; then
        . $i
      fi
    done
    unset i
  fi

**Comment by harryfwong** [comment]
Yeah, this is a vanilla install

I believe adding the full path is the solution.

**Comment by ajdecon** [comment]
Can't reproduce this, unfortunately. Please feel free to reopen if you see this reproduce in 21.06.
