### ISSUE TITLE
Slurm partitions

### ISSUE THREAD

**Issue by harryfwong** [NVIDIA/deepops#935]
What is the proper way for us to setup Slurm partitions via Ansible?

**Comment by ajdecon** [comment]
We currently don't have fine-grained configuration for Slurm partitions in Ansible. `slurm.conf` is a pretty complex file and it would be very difficult to template it enough to support all the possible options!

Instead, we support setting a custom path to the template file you use, via the [`slurm_conf_template` Ansible variable](https://github.com/NVIDIA/deepops/blob/21.06/roles/slurm/defaults/main.yml#L51). This will let you define your own template for `slurm.conf`, or even just point to a static file with your desired config.

This is something we [explicitly recommend for large deployments](https://github.com/NVIDIA/deepops/blob/master/docs/slurm-cluster/large-deployments.md#manually-generate-static-files-for-cluster-wide-configuration). For more information on how to set this kind of variable, see our [documentation on configuring DeepOps](https://github.com/NVIDIA/deepops/blob/master/docs/deepops/configuration.md).
