### ISSUE TITLE
error in /etc/slurm/shared/bin/run-parts.sh

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/deepops#936]
When not specifying memory requirements with sbatch/srun there is an error in /etc/slurm/shared/bin/run-parts.sh which calls prolog/epilog scripts:

`slurmd[177008]: /etc/slurm/shared/bin/run-parts.sh: line 18: 4 *  : syntax error: operand expected (error token is "*  ")`

IMHO this is because of 
`numcpus_sys=$(( $(grep -c ^processor /proc/cpuinfo) * $(scontrol show job "$SLURM_JOBID" | grep -Eio "TRES=.*node=[0-9]+" | cut -d= -f5) ))`
a solution could be
`numcpus_sys=$(( $(grep -c ^processor /proc/cpuinfo) * $(scontrol show job "$SLURM_JOBID" |  perl -ne 'if (/TRES=.*node=([0-9]+)/) {print $1;}') ))`

**Comment by mathrock74** [comment]
IMHO the error is still present in deeops 21.09 and should be resolved

**Comment by commonism** [comment]
still exists:
https://github.com/NVIDIA/deepops/blob/9b80ba22903b6ae5b22b13e28557e88c6d1bafb8/roles/slurm/templates/etc/slurm/shared/bin/run-parts.sh#L18-L21
