### ISSUE TITLE
Open sourcing of deepops container dependencies

### ISSUE THREAD

**Issue by hightoxicity** [NVIDIA/deepops#95]
Hi guys,

Could it be possible for you to share all the container build sources for https://hub.docker.com/search?q=deepops&type=image (I found nowhere something about apt-online) ?

Thx !

**Comment by supertetelman** [comment]
Dockerfiles for most of these containers should be stored in `src/containers`.

@dholt, can you do a quick check of the containers in DockerHub and the ones here: https://github.com/NVIDIA/deepops/tree/master/src/containers.

**Comment by supertetelman** [comment]
At this point all of the DeepOps Docker images have corresponding Dockerfiles in the repo. We are also in the process of migrating the containers to nvcr.io where they will be maintained going forward.
