### ISSUE TITLE
DeepOps instalation info for custom installation DGX

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/deepops#952]
Can we modify the installation directory for DeepOps ,like if i want to install using ansible playbook is it possible to chnge the default location to as our own convenient like the /opt.

Can Slurm script can be modified for scheduling .

I above can be done so how and where we need to make changes.

**Comment by ajdecon** [comment]
Most of the components in DeepOps have Ansible variables you can use to modify the install directory. For example, the Slurm role uses the [`slurm_install_prefix` variable](https://github.com/NVIDIA/deepops/blob/21.06/roles/slurm/defaults/main.yml#L15) to set the install location.

It's no clear which component you want to modify, and there's no one variable you can use to change all the components installed. For any given component, you probably want to check the `defaults/` directory of the relevant role to determine the variable name. See the [documentation on configuring DeepOps](https://github.com/NVIDIA/deepops/blob/master/docs/deepops/configuration.md) for information on how to set different values for these variables.
