### ISSUE TITLE
BIT:launch_hpl_experiment.sh fail to pull container image

### ISSUE THREAD

**Issue by dmonakhov** [NVIDIA/deepops#974]
It'looks like something is broken on nvcr.io , I fail to fetch container image,

login always fails with 502 even with propper API keys 

```
$ ./ngc registry image pull nvcr.io/nvidia/hpc-benchmarks:21.4-hpl
Logging in to https://nvcr.io… login failed.
500 Server Error for http+docker://localhost/v1.41/auth: Internal Server Error (“login attempt to https://nvcr.io/v2/ failed with status: 502 Bad Gateway”)
~$ docker login nvcr.io
Username: $oauthtoken
Password:
Error response from daemon: login attempt to https://nvcr.io/v2/ failed with status: 502 Bad Gateway
```
And it seems I'm not the only one here https://forums.developer.nvidia.com/t/cannot-pull-any-image-from-nvcr-io-502/156048/12

**Comment by andiariffin** [comment]
Got a similar issue a few days back upon pulling certain images from NGC. It seems that it just a temporary server-side issue as I pulled the same image today without any issues.

**Comment by ctierneynv** [comment]
I agree with the previous poster.  Sometimes NGC is not available.  Please try pulling the container again.

**Comment by dmonakhov** [comment]
Agree, registry is now avaiable again.
