### ISSUE TITLE
Grafana Alert e-mail via SMTP configuration

### ISSUE THREAD

**Issue by pankajsahtech** [NVIDIA/deepops#977]
Hi,

Grafana working fine in k8s deployed from deepops, I want to configure the SMTP in grafana for sending alert message to mail id.

Unable to find the defaults.ini file in deepops source. Please help me to configure smtp details in defaults.ini and what the steps to be follow.

Thank you
Pankaj

**Comment by ajdecon** [comment]
Currently we configure Grafana using a [`grafana.ini` file in the role](https://github.com/NVIDIA/deepops/blob/21.06/roles/grafana/templates/grafana.ini.j2).

This is currently pretty basic, and hard-coded in the role, so you'd have to fork the DeepOps repo to add config here.

I've opened #994 to allow setting a custom config file via an Ansible variable.
